// Code generated by cmd/codegen; DO NOT EDIT.

// Package keypadinput implements the Matter Keypad Input cluster (0x0509).
package keypadinput

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Keypad Input.
	ID uint32 = 0x0509
	// Name is the CLI-friendly cluster name.
	Name = "KeypadInput"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Keypad Input"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureNavigationKeyCodes uint32 = 1 << 0 // NV
	FeatureLocationKeys       uint32 = 1 << 1 // LK
	FeatureNumberKeys         uint32 = 1 << 2 // NK
)

// Command IDs.
const (
	CmdSendKey uint32 = 0x00
)

// SendKeyRequest is the request payload for the SendKey command.
type SendKeyRequest struct {
	KeyCode uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "NV", Name: "NavigationKeyCodes"},
			{Bit: 1, Code: "LK", Name: "LocationKeys"},
			{Bit: 2, Code: "NK", Name: "NumberKeys"},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSendKey, Name: "SendKey", DisplayName: "SendKey", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "KeyCode", DisplayName: "KeyCode", Type: "enum8"},
			}},
		},
	})
}
