// Code generated by cmd/codegen; DO NOT EDIT.

// Package commodityprice implements the Matter Commodity Price cluster (0x0095).
package commodityprice

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Commodity Price.
	ID uint32 = 0x0095
	// Name is the CLI-friendly cluster name.
	Name = "CommodityPrice"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Commodity Price"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureForecasting uint32 = 1 << 0 // FORE
)

// Attribute IDs.
const (
	AttrTariffUnit    uint32 = 0x0000
	AttrCurrency      uint32 = 0x0001
	AttrCurrentPrice  uint32 = 0x0002
	AttrPriceForecast uint32 = 0x0003
)

// Command IDs.
const (
	CmdGetDetailedPriceRequest    uint32 = 0x00
	CmdGetDetailedForecastRequest uint32 = 0x02
)

// GetDetailedPriceRequestRequest is the request payload for the GetDetailedPriceRequest command.
type GetDetailedPriceRequestRequest struct {
	Details uint8 `tlv:"0,uint"`
}

// GetDetailedForecastRequestRequest is the request payload for the GetDetailedForecastRequest command.
type GetDetailedForecastRequestRequest struct {
	Details uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "FORE", Name: "Forecasting"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTariffUnit, Name: "TariffUnit", DisplayName: "TariffUnit", Type: "enum8", Readable: true},
			{ID: AttrCurrency, Name: "Currency", DisplayName: "Currency", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCurrentPrice, Name: "CurrentPrice", DisplayName: "CurrentPrice", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrPriceForecast, Name: "PriceForecast", DisplayName: "PriceForecast", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdGetDetailedPriceRequest, Name: "GetDetailedPriceRequest", DisplayName: "GetDetailedPriceRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Details", DisplayName: "Details", Type: "bitmap8"},
			}},
			{ID: CmdGetDetailedForecastRequest, Name: "GetDetailedForecastRequest", DisplayName: "GetDetailedForecastRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Details", DisplayName: "Details", Type: "bitmap8"},
			}},
		},
	})
}
