// Code generated by cmd/codegen; DO NOT EDIT.

// Package colorcontrol implements the Matter Color Control cluster (0x0300).
package colorcontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Color Control.
	ID uint32 = 0x0300
	// Name is the CLI-friendly cluster name.
	Name = "ColorControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Color Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureHueSaturation    uint32 = 1 << 0 // HS
	FeatureEnhancedHue      uint32 = 1 << 1 // EHUE
	FeatureColorLoop        uint32 = 1 << 2 // CL
	FeatureXY               uint32 = 1 << 3 // XY
	FeatureColorTemperature uint32 = 1 << 4 // CT
)

// Attribute IDs.
const (
	AttrCurrentHue                      uint32 = 0x0000
	AttrCurrentSaturation               uint32 = 0x0001
	AttrRemainingTime                   uint32 = 0x0002
	AttrCurrentX                        uint32 = 0x0003
	AttrCurrentY                        uint32 = 0x0004
	AttrDriftCompensation               uint32 = 0x0005
	AttrCompensationText                uint32 = 0x0006
	AttrColorTemperatureMireds          uint32 = 0x0007
	AttrColorMode                       uint32 = 0x0008
	AttrOptions                         uint32 = 0x000F
	AttrNumberOfPrimaries               uint32 = 0x0010
	AttrPrimary1X                       uint32 = 0x0011
	AttrPrimary1Y                       uint32 = 0x0012
	AttrPrimary1Intensity               uint32 = 0x0013
	AttrPrimary2X                       uint32 = 0x0015
	AttrPrimary2Y                       uint32 = 0x0016
	AttrPrimary2Intensity               uint32 = 0x0017
	AttrPrimary3X                       uint32 = 0x0019
	AttrPrimary3Y                       uint32 = 0x001A
	AttrPrimary3Intensity               uint32 = 0x001B
	AttrPrimary4X                       uint32 = 0x0020
	AttrPrimary4Y                       uint32 = 0x0021
	AttrPrimary4Intensity               uint32 = 0x0022
	AttrPrimary5X                       uint32 = 0x0024
	AttrPrimary5Y                       uint32 = 0x0025
	AttrPrimary5Intensity               uint32 = 0x0026
	AttrPrimary6X                       uint32 = 0x0028
	AttrPrimary6Y                       uint32 = 0x0029
	AttrPrimary6Intensity               uint32 = 0x002A
	AttrWhitePointX                     uint32 = 0x0030
	AttrWhitePointY                     uint32 = 0x0031
	AttrColorPointRX                    uint32 = 0x0032
	AttrColorPointRY                    uint32 = 0x0033
	AttrColorPointRIntensity            uint32 = 0x0034
	AttrColorPointGX                    uint32 = 0x0036
	AttrColorPointGY                    uint32 = 0x0037
	AttrColorPointGIntensity            uint32 = 0x0038
	AttrColorPointBX                    uint32 = 0x003A
	AttrColorPointBY                    uint32 = 0x003B
	AttrColorPointBIntensity            uint32 = 0x003C
	AttrEnhancedCurrentHue              uint32 = 0x4000
	AttrEnhancedColorMode               uint32 = 0x4001
	AttrColorLoopActive                 uint32 = 0x4002
	AttrColorLoopDirection              uint32 = 0x4003
	AttrColorLoopTime                   uint32 = 0x4004
	AttrColorLoopStartEnhancedHue       uint32 = 0x4005
	AttrColorLoopStoredEnhancedHue      uint32 = 0x4006
	AttrColorCapabilities               uint32 = 0x400A
	AttrColorTempPhysicalMinMireds      uint32 = 0x400B
	AttrColorTempPhysicalMaxMireds      uint32 = 0x400C
	AttrCoupleColorTempToLevelMinMireds uint32 = 0x400D
	AttrStartUpColorTemperatureMireds   uint32 = 0x4010
)

// Command IDs.
const (
	CmdMoveToHue                      uint32 = 0x00
	CmdMoveHue                        uint32 = 0x01
	CmdStepHue                        uint32 = 0x02
	CmdMoveToSaturation               uint32 = 0x03
	CmdMoveSaturation                 uint32 = 0x04
	CmdStepSaturation                 uint32 = 0x05
	CmdMoveToHueAndSaturation         uint32 = 0x06
	CmdMoveToColor                    uint32 = 0x07
	CmdMoveColor                      uint32 = 0x08
	CmdStepColor                      uint32 = 0x09
	CmdMoveToColorTemperature         uint32 = 0x0A
	CmdEnhancedMoveToHue              uint32 = 0x40
	CmdEnhancedMoveHue                uint32 = 0x41
	CmdEnhancedStepHue                uint32 = 0x42
	CmdEnhancedMoveToHueAndSaturation uint32 = 0x43
	CmdColorLoopSet                   uint32 = 0x44
	CmdStopMoveStep                   uint32 = 0x47
	CmdMoveColorTemperature           uint32 = 0x4B
	CmdStepColorTemperature           uint32 = 0x4C
)

// MoveToHueRequest is the request payload for the MoveToHue command.
type MoveToHueRequest struct {
	Hue             uint8  `tlv:"0,uint"`
	Direction       uint8  `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// MoveHueRequest is the request payload for the MoveHue command.
type MoveHueRequest struct {
	MoveMode        uint8 `tlv:"0,uint"`
	Rate            uint8 `tlv:"1,uint"`
	OptionsMask     uint8 `tlv:"2,uint"`
	OptionsOverride uint8 `tlv:"3,uint"`
}

// StepHueRequest is the request payload for the StepHue command.
type StepHueRequest struct {
	StepMode        uint8 `tlv:"0,uint"`
	StepSize        uint8 `tlv:"1,uint"`
	TransitionTime  uint8 `tlv:"2,uint"`
	OptionsMask     uint8 `tlv:"3,uint"`
	OptionsOverride uint8 `tlv:"4,uint"`
}

// MoveToSaturationRequest is the request payload for the MoveToSaturation command.
type MoveToSaturationRequest struct {
	Saturation      uint8  `tlv:"0,uint"`
	TransitionTime  uint16 `tlv:"1,uint"`
	OptionsMask     uint8  `tlv:"2,uint"`
	OptionsOverride uint8  `tlv:"3,uint"`
}

// MoveSaturationRequest is the request payload for the MoveSaturation command.
type MoveSaturationRequest struct {
	MoveMode        uint8 `tlv:"0,uint"`
	Rate            uint8 `tlv:"1,uint"`
	OptionsMask     uint8 `tlv:"2,uint"`
	OptionsOverride uint8 `tlv:"3,uint"`
}

// StepSaturationRequest is the request payload for the StepSaturation command.
type StepSaturationRequest struct {
	StepMode        uint8 `tlv:"0,uint"`
	StepSize        uint8 `tlv:"1,uint"`
	TransitionTime  uint8 `tlv:"2,uint"`
	OptionsMask     uint8 `tlv:"3,uint"`
	OptionsOverride uint8 `tlv:"4,uint"`
}

// MoveToHueAndSaturationRequest is the request payload for the MoveToHueAndSaturation command.
type MoveToHueAndSaturationRequest struct {
	Hue             uint8  `tlv:"0,uint"`
	Saturation      uint8  `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// MoveToColorRequest is the request payload for the MoveToColor command.
type MoveToColorRequest struct {
	ColorX          uint16 `tlv:"0,uint"`
	ColorY          uint16 `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// MoveColorRequest is the request payload for the MoveColor command.
type MoveColorRequest struct {
	RateX           int16 `tlv:"0,int"`
	RateY           int16 `tlv:"1,int"`
	OptionsMask     uint8 `tlv:"2,uint"`
	OptionsOverride uint8 `tlv:"3,uint"`
}

// StepColorRequest is the request payload for the StepColor command.
type StepColorRequest struct {
	StepX           int16  `tlv:"0,int"`
	StepY           int16  `tlv:"1,int"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// MoveToColorTemperatureRequest is the request payload for the MoveToColorTemperature command.
type MoveToColorTemperatureRequest struct {
	ColorTemperatureMireds uint16 `tlv:"0,uint"`
	TransitionTime         uint16 `tlv:"1,uint"`
	OptionsMask            uint8  `tlv:"2,uint"`
	OptionsOverride        uint8  `tlv:"3,uint"`
}

// EnhancedMoveToHueRequest is the request payload for the EnhancedMoveToHue command.
type EnhancedMoveToHueRequest struct {
	EnhancedHue     uint16 `tlv:"0,uint"`
	Direction       uint8  `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// EnhancedMoveHueRequest is the request payload for the EnhancedMoveHue command.
type EnhancedMoveHueRequest struct {
	MoveMode        uint8  `tlv:"0,uint"`
	Rate            uint16 `tlv:"1,uint"`
	OptionsMask     uint8  `tlv:"2,uint"`
	OptionsOverride uint8  `tlv:"3,uint"`
}

// EnhancedStepHueRequest is the request payload for the EnhancedStepHue command.
type EnhancedStepHueRequest struct {
	StepMode        uint8  `tlv:"0,uint"`
	StepSize        uint16 `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// EnhancedMoveToHueAndSaturationRequest is the request payload for the EnhancedMoveToHueAndSaturation command.
type EnhancedMoveToHueAndSaturationRequest struct {
	EnhancedHue     uint16 `tlv:"0,uint"`
	Saturation      uint8  `tlv:"1,uint"`
	TransitionTime  uint16 `tlv:"2,uint"`
	OptionsMask     uint8  `tlv:"3,uint"`
	OptionsOverride uint8  `tlv:"4,uint"`
}

// ColorLoopSetRequest is the request payload for the ColorLoopSet command.
type ColorLoopSetRequest struct {
	UpdateFlags     uint8  `tlv:"0,uint"`
	Action          uint8  `tlv:"1,uint"`
	Direction       uint8  `tlv:"2,uint"`
	Time            uint16 `tlv:"3,uint"`
	StartHue        uint16 `tlv:"4,uint"`
	OptionsMask     uint8  `tlv:"5,uint"`
	OptionsOverride uint8  `tlv:"6,uint"`
}

// StopMoveStepRequest is the request payload for the StopMoveStep command.
type StopMoveStepRequest struct {
	OptionsMask     uint8 `tlv:"0,uint"`
	OptionsOverride uint8 `tlv:"1,uint"`
}

// MoveColorTemperatureRequest is the request payload for the MoveColorTemperature command.
type MoveColorTemperatureRequest struct {
	MoveMode                      uint8  `tlv:"0,uint"`
	Rate                          uint16 `tlv:"1,uint"`
	ColorTemperatureMinimumMireds uint16 `tlv:"2,uint"`
	ColorTemperatureMaximumMireds uint16 `tlv:"3,uint"`
	OptionsMask                   uint8  `tlv:"4,uint"`
	OptionsOverride               uint8  `tlv:"5,uint"`
}

// StepColorTemperatureRequest is the request payload for the StepColorTemperature command.
type StepColorTemperatureRequest struct {
	StepMode                      uint8  `tlv:"0,uint"`
	StepSize                      uint16 `tlv:"1,uint"`
	TransitionTime                uint16 `tlv:"2,uint"`
	ColorTemperatureMinimumMireds uint16 `tlv:"3,uint"`
	ColorTemperatureMaximumMireds uint16 `tlv:"4,uint"`
	OptionsMask                   uint8  `tlv:"5,uint"`
	OptionsOverride               uint8  `tlv:"6,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "HS", Name: "HueSaturation"},
			{Bit: 1, Code: "EHUE", Name: "EnhancedHue"},
			{Bit: 2, Code: "CL", Name: "ColorLoop"},
			{Bit: 3, Code: "XY", Name: "XY"},
			{Bit: 4, Code: "CT", Name: "ColorTemperature"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCurrentHue, Name: "CurrentHue", DisplayName: "CurrentHue", Type: "uint8", Readable: true},
			{ID: AttrCurrentSaturation, Name: "CurrentSaturation", DisplayName: "CurrentSaturation", Type: "uint8", Readable: true},
			{ID: AttrRemainingTime, Name: "RemainingTime", DisplayName: "RemainingTime", Type: "uint16", Readable: true},
			{ID: AttrCurrentX, Name: "CurrentX", DisplayName: "CurrentX", Type: "uint16", Readable: true},
			{ID: AttrCurrentY, Name: "CurrentY", DisplayName: "CurrentY", Type: "uint16", Readable: true},
			{ID: AttrDriftCompensation, Name: "DriftCompensation", DisplayName: "DriftCompensation", Type: "enum8", Readable: true},
			{ID: AttrCompensationText, Name: "CompensationText", DisplayName: "CompensationText", Type: "string", Readable: true},
			{ID: AttrColorTemperatureMireds, Name: "ColorTemperatureMireds", DisplayName: "ColorTemperatureMireds", Type: "uint16", Readable: true},
			{ID: AttrColorMode, Name: "ColorMode", DisplayName: "ColorMode", Type: "enum8", Readable: true},
			{ID: AttrOptions, Name: "Options", DisplayName: "Options", Type: "bitmap8", Readable: true, Writable: true},
			{ID: AttrNumberOfPrimaries, Name: "NumberOfPrimaries", DisplayName: "NumberOfPrimaries", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary1X, Name: "Primary1X", DisplayName: "Primary1X", Type: "uint16", Readable: true},
			{ID: AttrPrimary1Y, Name: "Primary1Y", DisplayName: "Primary1Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary1Intensity, Name: "Primary1Intensity", DisplayName: "Primary1Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary2X, Name: "Primary2X", DisplayName: "Primary2X", Type: "uint16", Readable: true},
			{ID: AttrPrimary2Y, Name: "Primary2Y", DisplayName: "Primary2Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary2Intensity, Name: "Primary2Intensity", DisplayName: "Primary2Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary3X, Name: "Primary3X", DisplayName: "Primary3X", Type: "uint16", Readable: true},
			{ID: AttrPrimary3Y, Name: "Primary3Y", DisplayName: "Primary3Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary3Intensity, Name: "Primary3Intensity", DisplayName: "Primary3Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary4X, Name: "Primary4X", DisplayName: "Primary4X", Type: "uint16", Readable: true},
			{ID: AttrPrimary4Y, Name: "Primary4Y", DisplayName: "Primary4Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary4Intensity, Name: "Primary4Intensity", DisplayName: "Primary4Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary5X, Name: "Primary5X", DisplayName: "Primary5X", Type: "uint16", Readable: true},
			{ID: AttrPrimary5Y, Name: "Primary5Y", DisplayName: "Primary5Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary5Intensity, Name: "Primary5Intensity", DisplayName: "Primary5Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrPrimary6X, Name: "Primary6X", DisplayName: "Primary6X", Type: "uint16", Readable: true},
			{ID: AttrPrimary6Y, Name: "Primary6Y", DisplayName: "Primary6Y", Type: "uint16", Readable: true},
			{ID: AttrPrimary6Intensity, Name: "Primary6Intensity", DisplayName: "Primary6Intensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrWhitePointX, Name: "WhitePointX", DisplayName: "WhitePointX", Type: "uint16", Readable: true},
			{ID: AttrWhitePointY, Name: "WhitePointY", DisplayName: "WhitePointY", Type: "uint16", Readable: true},
			{ID: AttrColorPointRX, Name: "ColorPointRX", DisplayName: "ColorPointRX", Type: "uint16", Readable: true},
			{ID: AttrColorPointRY, Name: "ColorPointRY", DisplayName: "ColorPointRY", Type: "uint16", Readable: true},
			{ID: AttrColorPointRIntensity, Name: "ColorPointRIntensity", DisplayName: "ColorPointRIntensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrColorPointGX, Name: "ColorPointGX", DisplayName: "ColorPointGX", Type: "uint16", Readable: true},
			{ID: AttrColorPointGY, Name: "ColorPointGY", DisplayName: "ColorPointGY", Type: "uint16", Readable: true},
			{ID: AttrColorPointGIntensity, Name: "ColorPointGIntensity", DisplayName: "ColorPointGIntensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrColorPointBX, Name: "ColorPointBX", DisplayName: "ColorPointBX", Type: "uint16", Readable: true},
			{ID: AttrColorPointBY, Name: "ColorPointBY", DisplayName: "ColorPointBY", Type: "uint16", Readable: true},
			{ID: AttrColorPointBIntensity, Name: "ColorPointBIntensity", DisplayName: "ColorPointBIntensity", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrEnhancedCurrentHue, Name: "EnhancedCurrentHue", DisplayName: "EnhancedCurrentHue", Type: "uint16", Readable: true},
			{ID: AttrEnhancedColorMode, Name: "EnhancedColorMode", DisplayName: "EnhancedColorMode", Type: "enum8", Readable: true},
			{ID: AttrColorLoopActive, Name: "ColorLoopActive", DisplayName: "ColorLoopActive", Type: "uint8", Readable: true},
			{ID: AttrColorLoopDirection, Name: "ColorLoopDirection", DisplayName: "ColorLoopDirection", Type: "enum8", Readable: true},
			{ID: AttrColorLoopTime, Name: "ColorLoopTime", DisplayName: "ColorLoopTime", Type: "uint16", Readable: true},
			{ID: AttrColorLoopStartEnhancedHue, Name: "ColorLoopStartEnhancedHue", DisplayName: "ColorLoopStartEnhancedHue", Type: "uint16", Readable: true},
			{ID: AttrColorLoopStoredEnhancedHue, Name: "ColorLoopStoredEnhancedHue", DisplayName: "ColorLoopStoredEnhancedHue", Type: "uint16", Readable: true},
			{ID: AttrColorCapabilities, Name: "ColorCapabilities", DisplayName: "ColorCapabilities", Type: "bitmap8", Readable: true},
			{ID: AttrColorTempPhysicalMinMireds, Name: "ColorTempPhysicalMinMireds", DisplayName: "ColorTempPhysicalMinMireds", Type: "uint16", Readable: true},
			{ID: AttrColorTempPhysicalMaxMireds, Name: "ColorTempPhysicalMaxMireds", DisplayName: "ColorTempPhysicalMaxMireds", Type: "uint16", Readable: true},
			{ID: AttrCoupleColorTempToLevelMinMireds, Name: "CoupleColorTempToLevelMinMireds", DisplayName: "CoupleColorTempToLevelMinMireds", Type: "uint16", Readable: true},
			{ID: AttrStartUpColorTemperatureMireds, Name: "StartUpColorTemperatureMireds", DisplayName: "StartUpColorTemperatureMireds", Type: "uint16", Readable: true, Writable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdMoveToHue, Name: "MoveToHue", DisplayName: "MoveToHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Hue", DisplayName: "Hue", Type: "uint8"},
				{ID: 1, Name: "Direction", DisplayName: "Direction", Type: "enum8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveHue, Name: "MoveHue", DisplayName: "MoveHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MoveMode", DisplayName: "MoveMode", Type: "enum8"},
				{ID: 1, Name: "Rate", DisplayName: "Rate", Type: "uint8"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdStepHue, Name: "StepHue", DisplayName: "StepHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StepMode", DisplayName: "StepMode", Type: "enum8"},
				{ID: 1, Name: "StepSize", DisplayName: "StepSize", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint8"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveToSaturation, Name: "MoveToSaturation", DisplayName: "MoveToSaturation", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Saturation", DisplayName: "Saturation", Type: "uint8"},
				{ID: 1, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveSaturation, Name: "MoveSaturation", DisplayName: "MoveSaturation", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MoveMode", DisplayName: "MoveMode", Type: "enum8"},
				{ID: 1, Name: "Rate", DisplayName: "Rate", Type: "uint8"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdStepSaturation, Name: "StepSaturation", DisplayName: "StepSaturation", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StepMode", DisplayName: "StepMode", Type: "enum8"},
				{ID: 1, Name: "StepSize", DisplayName: "StepSize", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint8"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveToHueAndSaturation, Name: "MoveToHueAndSaturation", DisplayName: "MoveToHueAndSaturation", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Hue", DisplayName: "Hue", Type: "uint8"},
				{ID: 1, Name: "Saturation", DisplayName: "Saturation", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveToColor, Name: "MoveToColor", DisplayName: "MoveToColor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ColorX", DisplayName: "ColorX", Type: "uint16"},
				{ID: 1, Name: "ColorY", DisplayName: "ColorY", Type: "uint16"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveColor, Name: "MoveColor", DisplayName: "MoveColor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "RateX", DisplayName: "RateX", Type: "int16"},
				{ID: 1, Name: "RateY", DisplayName: "RateY", Type: "int16"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdStepColor, Name: "StepColor", DisplayName: "StepColor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StepX", DisplayName: "StepX", Type: "int16"},
				{ID: 1, Name: "StepY", DisplayName: "StepY", Type: "int16"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveToColorTemperature, Name: "MoveToColorTemperature", DisplayName: "MoveToColorTemperature", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ColorTemperatureMireds", DisplayName: "ColorTemperatureMireds", Type: "uint16"},
				{ID: 1, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdEnhancedMoveToHue, Name: "EnhancedMoveToHue", DisplayName: "EnhancedMoveToHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EnhancedHue", DisplayName: "EnhancedHue", Type: "uint16"},
				{ID: 1, Name: "Direction", DisplayName: "Direction", Type: "enum8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdEnhancedMoveHue, Name: "EnhancedMoveHue", DisplayName: "EnhancedMoveHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MoveMode", DisplayName: "MoveMode", Type: "enum8"},
				{ID: 1, Name: "Rate", DisplayName: "Rate", Type: "uint16"},
				{ID: 2, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 3, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdEnhancedStepHue, Name: "EnhancedStepHue", DisplayName: "EnhancedStepHue", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StepMode", DisplayName: "StepMode", Type: "enum8"},
				{ID: 1, Name: "StepSize", DisplayName: "StepSize", Type: "uint16"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdEnhancedMoveToHueAndSaturation, Name: "EnhancedMoveToHueAndSaturation", DisplayName: "EnhancedMoveToHueAndSaturation", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EnhancedHue", DisplayName: "EnhancedHue", Type: "uint16"},
				{ID: 1, Name: "Saturation", DisplayName: "Saturation", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 4, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdColorLoopSet, Name: "ColorLoopSet", DisplayName: "ColorLoopSet", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UpdateFlags", DisplayName: "UpdateFlags", Type: "bitmap8"},
				{ID: 1, Name: "Action", DisplayName: "Action", Type: "enum8"},
				{ID: 2, Name: "Direction", DisplayName: "Direction", Type: "enum8"},
				{ID: 3, Name: "Time", DisplayName: "Time", Type: "uint16"},
				{ID: 4, Name: "StartHue", DisplayName: "StartHue", Type: "uint16"},
				{ID: 5, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 6, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdStopMoveStep, Name: "StopMoveStep", DisplayName: "StopMoveStep", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 1, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdMoveColorTemperature, Name: "MoveColorTemperature", DisplayName: "MoveColorTemperature", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MoveMode", DisplayName: "MoveMode", Type: "enum8"},
				{ID: 1, Name: "Rate", DisplayName: "Rate", Type: "uint16"},
				{ID: 2, Name: "ColorTemperatureMinimumMireds", DisplayName: "ColorTemperatureMinimumMireds", Type: "uint16"},
				{ID: 3, Name: "ColorTemperatureMaximumMireds", DisplayName: "ColorTemperatureMaximumMireds", Type: "uint16"},
				{ID: 4, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 5, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
			{ID: CmdStepColorTemperature, Name: "StepColorTemperature", DisplayName: "StepColorTemperature", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StepMode", DisplayName: "StepMode", Type: "enum8"},
				{ID: 1, Name: "StepSize", DisplayName: "StepSize", Type: "uint16"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
				{ID: 3, Name: "ColorTemperatureMinimumMireds", DisplayName: "ColorTemperatureMinimumMireds", Type: "uint16"},
				{ID: 4, Name: "ColorTemperatureMaximumMireds", DisplayName: "ColorTemperatureMaximumMireds", Type: "uint16"},
				{ID: 5, Name: "OptionsMask", DisplayName: "OptionsMask", Type: "bitmap8"},
				{ID: 6, Name: "OptionsOverride", DisplayName: "OptionsOverride", Type: "bitmap8"},
			}},
		},
	})
}
