// Code generated by cmd/codegen; DO NOT EDIT.

// Package smokecoalarm implements the Matter Smoke CO Alarm cluster (0x005C).
package smokecoalarm

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Smoke CO Alarm.
	ID uint32 = 0x005C
	// Name is the CLI-friendly cluster name.
	Name = "SmokeCOAlarm"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Smoke CO Alarm"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureSmokeAlarm uint32 = 1 << 0 // SMOKE
	FeatureCOAlarm    uint32 = 1 << 1 // CO
)

// Attribute IDs.
const (
	AttrExpressedState         uint32 = 0x0000
	AttrSmokeState             uint32 = 0x0001
	AttrCOState                uint32 = 0x0002
	AttrBatteryAlert           uint32 = 0x0003
	AttrDeviceMuted            uint32 = 0x0004
	AttrTestInProgress         uint32 = 0x0005
	AttrHardwareFaultAlert     uint32 = 0x0006
	AttrEndOfServiceAlert      uint32 = 0x0007
	AttrInterconnectSmokeAlarm uint32 = 0x0008
	AttrInterconnectCOAlarm    uint32 = 0x0009
	AttrContaminationState     uint32 = 0x000A
	AttrSmokeSensitivityLevel  uint32 = 0x000B
	AttrExpiryDate             uint32 = 0x000C
)

// Command IDs.
const (
	CmdSelfTestRequest uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "SMOKE", Name: "SmokeAlarm"},
			{Bit: 1, Code: "CO", Name: "COAlarm"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrExpressedState, Name: "ExpressedState", DisplayName: "ExpressedState", Type: "enum8", Readable: true},
			{ID: AttrSmokeState, Name: "SmokeState", DisplayName: "SmokeState", Type: "enum8", Readable: true},
			{ID: AttrCOState, Name: "COState", DisplayName: "COState", Type: "enum8", Readable: true},
			{ID: AttrBatteryAlert, Name: "BatteryAlert", DisplayName: "BatteryAlert", Type: "enum8", Readable: true},
			{ID: AttrDeviceMuted, Name: "DeviceMuted", DisplayName: "DeviceMuted", Type: "enum8", Readable: true},
			{ID: AttrTestInProgress, Name: "TestInProgress", DisplayName: "TestInProgress", Type: "bool", Readable: true},
			{ID: AttrHardwareFaultAlert, Name: "HardwareFaultAlert", DisplayName: "HardwareFaultAlert", Type: "bool", Readable: true},
			{ID: AttrEndOfServiceAlert, Name: "EndOfServiceAlert", DisplayName: "EndOfServiceAlert", Type: "enum8", Readable: true},
			{ID: AttrInterconnectSmokeAlarm, Name: "InterconnectSmokeAlarm", DisplayName: "InterconnectSmokeAlarm", Type: "enum8", Readable: true},
			{ID: AttrInterconnectCOAlarm, Name: "InterconnectCOAlarm", DisplayName: "InterconnectCOAlarm", Type: "enum8", Readable: true},
			{ID: AttrContaminationState, Name: "ContaminationState", DisplayName: "ContaminationState", Type: "enum8", Readable: true},
			{ID: AttrSmokeSensitivityLevel, Name: "SmokeSensitivityLevel", DisplayName: "SmokeSensitivityLevel", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrExpiryDate, Name: "ExpiryDate", DisplayName: "ExpiryDate", Type: "uint32", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSelfTestRequest, Name: "SelfTestRequest", DisplayName: "SelfTestRequest"},
		},
	})
}
