// Code generated by cmd/codegen; DO NOT EDIT.

// Package powertopology implements the Matter Power Topology cluster (0x009C).
package powertopology

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Power Topology.
	ID uint32 = 0x009C
	// Name is the CLI-friendly cluster name.
	Name = "PowerTopology"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Power Topology"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureNodeTopology     uint32 = 1 << 0 // NODE
	FeatureTreeTopology     uint32 = 1 << 1 // TREE
	FeatureSetTopology      uint32 = 1 << 2 // SET
	FeatureDynamicPowerFlow uint32 = 1 << 3 // DYPF
)

// Attribute IDs.
const (
	AttrAvailableEndpoints uint32 = 0x0000
	AttrActiveEndpoints    uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "NODE", Name: "NodeTopology"},
			{Bit: 1, Code: "TREE", Name: "TreeTopology"},
			{Bit: 2, Code: "SET", Name: "SetTopology"},
			{Bit: 3, Code: "DYPF", Name: "DynamicPowerFlow"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrAvailableEndpoints, Name: "AvailableEndpoints", DisplayName: "AvailableEndpoints", Type: "list", Readable: true},
			{ID: AttrActiveEndpoints, Name: "ActiveEndpoints", DisplayName: "ActiveEndpoints", Type: "list", Readable: true},
		},
	})
}
