// Code generated by cmd/codegen; DO NOT EDIT.

// Package groupkeymanagement implements the Matter Group Key Management cluster (0x003F).
package groupkeymanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Group Key Management.
	ID uint32 = 0x003F
	// Name is the CLI-friendly cluster name.
	Name = "GroupKeyManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Group Key Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureCacheAndSync uint32 = 1 << 0 // CS
)

// Attribute IDs.
const (
	AttrGroupKeyMap           uint32 = 0x0000
	AttrGroupTable            uint32 = 0x0001
	AttrMaxGroupsPerFabric    uint32 = 0x0002
	AttrMaxGroupKeysPerFabric uint32 = 0x0003
)

// Command IDs.
const (
	CmdKeySetWrite          uint32 = 0x00
	CmdKeySetRead           uint32 = 0x01
	CmdKeySetRemove         uint32 = 0x03
	CmdKeySetReadAllIndices uint32 = 0x04
)

// KeySetWriteRequest is the request payload for the KeySetWrite command.
type KeySetWriteRequest struct {
	GroupKeySet uint8 `tlv:"0,uint"`
}

// KeySetReadRequest is the request payload for the KeySetRead command.
type KeySetReadRequest struct {
	GroupKeySetID uint16 `tlv:"0,uint"`
}

// KeySetRemoveRequest is the request payload for the KeySetRemove command.
type KeySetRemoveRequest struct {
	GroupKeySetID uint16 `tlv:"0,uint"`
}

// KeySetReadAllIndicesRequest is the request payload for the KeySetReadAllIndices command.
type KeySetReadAllIndicesRequest struct {
	DoNotUse uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CS", Name: "CacheAndSync"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrGroupKeyMap, Name: "GroupKeyMap", DisplayName: "GroupKeyMap", Type: "list", Readable: true, Writable: true},
			{ID: AttrGroupTable, Name: "GroupTable", DisplayName: "GroupTable", Type: "list", Readable: true},
			{ID: AttrMaxGroupsPerFabric, Name: "MaxGroupsPerFabric", DisplayName: "MaxGroupsPerFabric", Type: "uint16", Readable: true},
			{ID: AttrMaxGroupKeysPerFabric, Name: "MaxGroupKeysPerFabric", DisplayName: "MaxGroupKeysPerFabric", Type: "uint16", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdKeySetWrite, Name: "KeySetWrite", DisplayName: "KeySetWrite", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySet", DisplayName: "GroupKeySet", Type: "struct"},
			}},
			{ID: CmdKeySetRead, Name: "KeySetRead", DisplayName: "KeySetRead", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySetID", DisplayName: "GroupKeySetID", Type: "uint16"},
			}},
			{ID: CmdKeySetRemove, Name: "KeySetRemove", DisplayName: "KeySetRemove", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySetID", DisplayName: "GroupKeySetID", Type: "uint16"},
			}},
			{ID: CmdKeySetReadAllIndices, Name: "KeySetReadAllIndices", DisplayName: "KeySetReadAllIndices", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DoNotUse", DisplayName: "DoNotUse", Type: "uint8"},
			}},
		},
	})
}
