// Code generated by cmd/codegen; DO NOT EDIT.

// Package administratorcommissioning implements the Matter Administrator Commissioning cluster (0x003C).
package administratorcommissioning

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Administrator Commissioning.
	ID uint32 = 0x003C
	// Name is the CLI-friendly cluster name.
	Name = "AdministratorCommissioning"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Administrator Commissioning"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureBasic uint32 = 1 << 0 // BC
)

// Attribute IDs.
const (
	AttrWindowStatus     uint32 = 0x0000
	AttrAdminFabricIndex uint32 = 0x0001
	AttrAdminVendorId    uint32 = 0x0002
)

// Command IDs.
const (
	CmdOpenCommissioningWindow      uint32 = 0x00
	CmdOpenBasicCommissioningWindow uint32 = 0x01
	CmdRevokeCommissioning          uint32 = 0x02
)

// OpenCommissioningWindowRequest is the request payload for the OpenCommissioningWindow command.
type OpenCommissioningWindowRequest struct {
	CommissioningTimeout uint16 `tlv:"0,uint"`
	PAKEPasscodeVerifier []byte `tlv:"1,bytes"`
	Discriminator        uint16 `tlv:"2,uint"`
	Iterations           uint32 `tlv:"3,uint"`
	Salt                 []byte `tlv:"4,bytes"`
}

// OpenBasicCommissioningWindowRequest is the request payload for the OpenBasicCommissioningWindow command.
type OpenBasicCommissioningWindowRequest struct {
	CommissioningTimeout uint16 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "BC", Name: "Basic"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrWindowStatus, Name: "WindowStatus", DisplayName: "WindowStatus", Type: "enum8", Readable: true},
			{ID: AttrAdminFabricIndex, Name: "AdminFabricIndex", DisplayName: "AdminFabricIndex", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrAdminVendorId, Name: "AdminVendorId", DisplayName: "AdminVendorId", Type: "uint16", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdOpenCommissioningWindow, Name: "OpenCommissioningWindow", DisplayName: "OpenCommissioningWindow", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CommissioningTimeout", DisplayName: "CommissioningTimeout", Type: "uint16"},
				{ID: 1, Name: "PAKEPasscodeVerifier", DisplayName: "PAKEPasscodeVerifier", Type: "octets"},
				{ID: 2, Name: "Discriminator", DisplayName: "Discriminator", Type: "uint16"},
				{ID: 3, Name: "Iterations", DisplayName: "Iterations", Type: "uint32"},
				{ID: 4, Name: "Salt", DisplayName: "Salt", Type: "octets"},
			}},
			{ID: CmdOpenBasicCommissioningWindow, Name: "OpenBasicCommissioningWindow", DisplayName: "OpenBasicCommissioningWindow", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CommissioningTimeout", DisplayName: "CommissioningTimeout", Type: "uint16"},
			}},
			{ID: CmdRevokeCommissioning, Name: "RevokeCommissioning", DisplayName: "RevokeCommissioning"},
		},
	})
}
