// Code generated by cmd/codegen; DO NOT EDIT.

// Package binding implements the Matter Binding cluster (0x001E).
package binding

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Binding.
	ID uint32 = 0x001E
	// Name is the CLI-friendly cluster name.
	Name = "Binding"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Binding"
)

// Attribute IDs.
const (
	AttrBinding uint32 = 0x0000
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrBinding, Name: "Binding", DisplayName: "Binding", Type: "list", Readable: true, Writable: true},
		},
	})
}
