// Code generated by cmd/codegen; DO NOT EDIT.

// Package descriptor implements the Matter Descriptor cluster (0x001D).
package descriptor

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Descriptor.
	ID uint32 = 0x001D
	// Name is the CLI-friendly cluster name.
	Name = "Descriptor"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Descriptor"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTagList uint32 = 1 << 0 // TAGLIST
)

// Attribute IDs.
const (
	AttrDeviceTypeList   uint32 = 0x0000
	AttrServerList       uint32 = 0x0001
	AttrClientList       uint32 = 0x0002
	AttrPartsList        uint32 = 0x0003
	AttrTagList          uint32 = 0x0004
	AttrEndpointUniqueID uint32 = 0x0005
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TAGLIST", Name: "TagList"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrDeviceTypeList, Name: "DeviceTypeList", DisplayName: "DeviceTypeList", Type: "list", Readable: true},
			{ID: AttrServerList, Name: "ServerList", DisplayName: "ServerList", Type: "list", Readable: true},
			{ID: AttrClientList, Name: "ClientList", DisplayName: "ClientList", Type: "list", Readable: true},
			{ID: AttrPartsList, Name: "PartsList", DisplayName: "PartsList", Type: "list", Readable: true},
			{ID: AttrTagList, Name: "TagList", DisplayName: "TagList", Type: "list", Readable: true},
			{ID: AttrEndpointUniqueID, Name: "EndpointUniqueID", DisplayName: "EndpointUniqueID", Type: "string", Readable: true},
		},
	})
}
