// Code generated by cmd/codegen; DO NOT EDIT.

// Package wifinetworkdiagnostics implements the Matter Wi-Fi Network Diagnostics cluster (0x0036).
package wifinetworkdiagnostics

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Wi-Fi Network Diagnostics.
	ID uint32 = 0x0036
	// Name is the CLI-friendly cluster name.
	Name = "WiFiNetworkDiagnostics"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Wi-Fi Network Diagnostics"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePacketCounts uint32 = 1 << 0 // PKTCNT
	FeatureErrorCounts  uint32 = 1 << 1 // ERRCNT
)

// Attribute IDs.
const (
	AttrBSSID                  uint32 = 0x0000
	AttrSecurityType           uint32 = 0x0001
	AttrWiFiVersion            uint32 = 0x0002
	AttrChannelNumber          uint32 = 0x0003
	AttrRSSI                   uint32 = 0x0004
	AttrBeaconLostCount        uint32 = 0x0005
	AttrBeaconRxCount          uint32 = 0x0006
	AttrPacketMulticastRxCount uint32 = 0x0007
	AttrPacketMulticastTxCount uint32 = 0x0008
	AttrPacketUnicastRxCount   uint32 = 0x0009
	AttrPacketUnicastTxCount   uint32 = 0x000A
	AttrCurrentMaxRate         uint32 = 0x000B
	AttrOverrunCount           uint32 = 0x000C
)

// Command IDs.
const (
	CmdResetCounts uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PKTCNT", Name: "PacketCounts"},
			{Bit: 1, Code: "ERRCNT", Name: "ErrorCounts"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrBSSID, Name: "BSSID", DisplayName: "BSSID", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrSecurityType, Name: "SecurityType", DisplayName: "SecurityType", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrWiFiVersion, Name: "WiFiVersion", DisplayName: "WiFiVersion", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrChannelNumber, Name: "ChannelNumber", DisplayName: "ChannelNumber", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrRSSI, Name: "RSSI", DisplayName: "RSSI", Type: "int8", Readable: true, Nullable: true},
			{ID: AttrBeaconLostCount, Name: "BeaconLostCount", DisplayName: "BeaconLostCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrBeaconRxCount, Name: "BeaconRxCount", DisplayName: "BeaconRxCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrPacketMulticastRxCount, Name: "PacketMulticastRxCount", DisplayName: "PacketMulticastRxCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrPacketMulticastTxCount, Name: "PacketMulticastTxCount", DisplayName: "PacketMulticastTxCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrPacketUnicastRxCount, Name: "PacketUnicastRxCount", DisplayName: "PacketUnicastRxCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrPacketUnicastTxCount, Name: "PacketUnicastTxCount", DisplayName: "PacketUnicastTxCount", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrCurrentMaxRate, Name: "CurrentMaxRate", DisplayName: "CurrentMaxRate", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrOverrunCount, Name: "OverrunCount", DisplayName: "OverrunCount", Type: "uint64", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdResetCounts, Name: "ResetCounts", DisplayName: "ResetCounts"},
		},
	})
}
