// Code generated by cmd/codegen; DO NOT EDIT.

// Package soilmeasurement implements the Matter Soil Measurement cluster (0x0430).
package soilmeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Soil Measurement.
	ID uint32 = 0x0430
	// Name is the CLI-friendly cluster name.
	Name = "SoilMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Soil Measurement"
)

// Attribute IDs.
const (
	AttrSoilMoistureMeasurementLimits uint32 = 0x0000
	AttrSoilMoistureMeasuredValue     uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSoilMoistureMeasurementLimits, Name: "SoilMoistureMeasurementLimits", DisplayName: "SoilMoistureMeasurementLimits", Type: "struct", Readable: true},
			{ID: AttrSoilMoistureMeasuredValue, Name: "SoilMoistureMeasuredValue", DisplayName: "SoilMoistureMeasuredValue", Type: "uint8", Readable: true, Nullable: true},
		},
	})
}
