// Code generated by cmd/codegen; DO NOT EDIT.

// Package accountlogin implements the Matter Account Login cluster (0x050E).
package accountlogin

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Account Login.
	ID uint32 = 0x050E
	// Name is the CLI-friendly cluster name.
	Name = "AccountLogin"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Account Login"
)

// Command IDs.
const (
	CmdGetSetupPIN uint32 = 0x00
	CmdLogin       uint32 = 0x02
	CmdLogout      uint32 = 0x03
)

// GetSetupPINRequest is the request payload for the GetSetupPIN command.
type GetSetupPINRequest struct {
	TempAccountIdentifier string `tlv:"0,utf8"`
}

// LoginRequest is the request payload for the Login command.
type LoginRequest struct {
	TempAccountIdentifier string `tlv:"0,utf8"`
	SetupPIN              string `tlv:"1,utf8"`
	Node                  uint64 `tlv:"2,uint"`
}

// LogoutRequest is the request payload for the Logout command.
type LogoutRequest struct {
	Node uint64 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdGetSetupPIN, Name: "GetSetupPIN", DisplayName: "GetSetupPIN", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TempAccountIdentifier", DisplayName: "TempAccountIdentifier", Type: "string"},
			}},
			{ID: CmdLogin, Name: "Login", DisplayName: "Login", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TempAccountIdentifier", DisplayName: "TempAccountIdentifier", Type: "string"},
				{ID: 1, Name: "SetupPIN", DisplayName: "SetupPIN", Type: "string"},
				{ID: 2, Name: "Node", DisplayName: "Node", Type: "uint64", Optional: true},
			}},
			{ID: CmdLogout, Name: "Logout", DisplayName: "Logout", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Node", DisplayName: "Node", Type: "uint64", Optional: true},
			}},
		},
	})
}
