// Code generated by cmd/codegen; DO NOT EDIT.

// Package webrtctransportrequestor implements the Matter WebRTC Transport Requestor cluster (0x0554).
package webrtctransportrequestor

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for WebRTC Transport Requestor.
	ID uint32 = 0x0554
	// Name is the CLI-friendly cluster name.
	Name = "WebRTCTransportRequestor"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "WebRTC Transport Requestor"
)

// Attribute IDs.
const (
	AttrCurrentSessions uint32 = 0x0000
)

// Command IDs.
const (
	CmdOffer         uint32 = 0x00
	CmdAnswer        uint32 = 0x01
	CmdICECandidates uint32 = 0x02
	CmdEnd           uint32 = 0x03
)

// OfferRequest is the request payload for the Offer command.
type OfferRequest struct {
	WebRTCSessionID    uint8  `tlv:"0,uint"`
	SDP                string `tlv:"1,utf8"`
	ICEServers         uint8  `tlv:"2,uint"`
	ICETransportPolicy string `tlv:"3,utf8"`
}

// AnswerRequest is the request payload for the Answer command.
type AnswerRequest struct {
	WebRTCSessionID uint8  `tlv:"0,uint"`
	SDP             string `tlv:"1,utf8"`
}

// ICECandidatesRequest is the request payload for the ICECandidates command.
type ICECandidatesRequest struct {
	WebRTCSessionID uint8 `tlv:"0,uint"`
	ICECandidates   uint8 `tlv:"1,uint"`
}

// EndRequest is the request payload for the End command.
type EndRequest struct {
	WebRTCSessionID uint8 `tlv:"0,uint"`
	Reason          uint8 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCurrentSessions, Name: "CurrentSessions", DisplayName: "CurrentSessions", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdOffer, Name: "Offer", DisplayName: "Offer", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WebRTCSessionID", DisplayName: "WebRTCSessionID", Type: "uint8"},
				{ID: 1, Name: "SDP", DisplayName: "SDP", Type: "string"},
				{ID: 2, Name: "ICEServers", DisplayName: "ICEServers", Type: "list", Optional: true},
				{ID: 3, Name: "ICETransportPolicy", DisplayName: "ICETransportPolicy", Type: "string", Optional: true},
			}},
			{ID: CmdAnswer, Name: "Answer", DisplayName: "Answer", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WebRTCSessionID", DisplayName: "WebRTCSessionID", Type: "uint8"},
				{ID: 1, Name: "SDP", DisplayName: "SDP", Type: "string"},
			}},
			{ID: CmdICECandidates, Name: "ICECandidates", DisplayName: "ICECandidates", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WebRTCSessionID", DisplayName: "WebRTCSessionID", Type: "uint8"},
				{ID: 1, Name: "ICECandidates", DisplayName: "ICECandidates", Type: "list"},
			}},
			{ID: CmdEnd, Name: "End", DisplayName: "End", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WebRTCSessionID", DisplayName: "WebRTCSessionID", Type: "uint8"},
				{ID: 1, Name: "Reason", DisplayName: "Reason", Type: "enum8"},
			}},
		},
	})
}
