// Code generated by cmd/codegen; DO NOT EDIT.

// Package electricalgridconditions implements the Matter Electrical Grid Conditions cluster (0x00A0).
package electricalgridconditions

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Electrical Grid Conditions.
	ID uint32 = 0x00A0
	// Name is the CLI-friendly cluster name.
	Name = "ElectricalGridConditions"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Electrical Grid Conditions"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureForecasting uint32 = 1 << 0 // FORE
)

// Attribute IDs.
const (
	AttrLocalGenerationAvailable uint32 = 0x0000
	AttrCurrentConditions        uint32 = 0x0001
	AttrForecastConditions       uint32 = 0x0002
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "FORE", Name: "Forecasting"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrLocalGenerationAvailable, Name: "LocalGenerationAvailable", DisplayName: "LocalGenerationAvailable", Type: "bool", Readable: true, Writable: true, Nullable: true},
			{ID: AttrCurrentConditions, Name: "CurrentConditions", DisplayName: "CurrentConditions", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrForecastConditions, Name: "ForecastConditions", DisplayName: "ForecastConditions", Type: "list", Readable: true},
		},
	})
}
