// Code generated by cmd/codegen; DO NOT EDIT.

// Package threadborderroutermanagement implements the Matter Thread Border Router Management cluster (0x0452).
package threadborderroutermanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Thread Border Router Management.
	ID uint32 = 0x0452
	// Name is the CLI-friendly cluster name.
	Name = "ThreadBorderRouterManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Thread Border Router Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePANChange uint32 = 1 << 0 // PC
)

// Attribute IDs.
const (
	AttrBorderRouterName        uint32 = 0x0000
	AttrBorderAgentID           uint32 = 0x0001
	AttrThreadVersion           uint32 = 0x0002
	AttrInterfaceEnabled        uint32 = 0x0003
	AttrActiveDatasetTimestamp  uint32 = 0x0004
	AttrPendingDatasetTimestamp uint32 = 0x0005
)

// Command IDs.
const (
	CmdGetActiveDatasetRequest  uint32 = 0x00
	CmdGetPendingDatasetRequest uint32 = 0x01
	CmdSetActiveDatasetRequest  uint32 = 0x03
	CmdSetPendingDatasetRequest uint32 = 0x04
)

// SetActiveDatasetRequestRequest is the request payload for the SetActiveDatasetRequest command.
type SetActiveDatasetRequestRequest struct {
	ActiveDataset []byte `tlv:"0,bytes"`
	Breadcrumb    uint64 `tlv:"1,uint"`
}

// SetPendingDatasetRequestRequest is the request payload for the SetPendingDatasetRequest command.
type SetPendingDatasetRequestRequest struct {
	PendingDataset []byte `tlv:"0,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PC", Name: "PANChange"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrBorderRouterName, Name: "BorderRouterName", DisplayName: "BorderRouterName", Type: "string", Readable: true},
			{ID: AttrBorderAgentID, Name: "BorderAgentID", DisplayName: "BorderAgentID", Type: "octets", Readable: true},
			{ID: AttrThreadVersion, Name: "ThreadVersion", DisplayName: "ThreadVersion", Type: "uint16", Readable: true},
			{ID: AttrInterfaceEnabled, Name: "InterfaceEnabled", DisplayName: "InterfaceEnabled", Type: "bool", Readable: true},
			{ID: AttrActiveDatasetTimestamp, Name: "ActiveDatasetTimestamp", DisplayName: "ActiveDatasetTimestamp", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrPendingDatasetTimestamp, Name: "PendingDatasetTimestamp", DisplayName: "PendingDatasetTimestamp", Type: "uint64", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdGetActiveDatasetRequest, Name: "GetActiveDatasetRequest", DisplayName: "GetActiveDatasetRequest", HasResponse: true},
			{ID: CmdGetPendingDatasetRequest, Name: "GetPendingDatasetRequest", DisplayName: "GetPendingDatasetRequest", HasResponse: true},
			{ID: CmdSetActiveDatasetRequest, Name: "SetActiveDatasetRequest", DisplayName: "SetActiveDatasetRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActiveDataset", DisplayName: "ActiveDataset", Type: "octets"},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdSetPendingDatasetRequest, Name: "SetPendingDatasetRequest", DisplayName: "SetPendingDatasetRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PendingDataset", DisplayName: "PendingDataset", Type: "octets"},
			}},
		},
	})
}
