// Code generated by cmd/codegen; DO NOT EDIT.

// Package electricalenergymeasurement implements the Matter Electrical Energy Measurement cluster (0x0091).
package electricalenergymeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Electrical Energy Measurement.
	ID uint32 = 0x0091
	// Name is the CLI-friendly cluster name.
	Name = "ElectricalEnergyMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Electrical Energy Measurement"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureImportedEnergy   uint32 = 1 << 0 // IMPE
	FeatureExportedEnergy   uint32 = 1 << 1 // EXPE
	FeatureCumulativeEnergy uint32 = 1 << 2 // CUME
	FeaturePeriodicEnergy   uint32 = 1 << 3 // PERE
	FeatureApparentEnergy   uint32 = 1 << 4 // APPE
	FeatureReactiveEnergy   uint32 = 1 << 5 // REAE
)

// Attribute IDs.
const (
	AttrAccuracy                 uint32 = 0x0000
	AttrCumulativeEnergyImported uint32 = 0x0001
	AttrCumulativeEnergyExported uint32 = 0x0002
	AttrPeriodicEnergyImported   uint32 = 0x0003
	AttrPeriodicEnergyExported   uint32 = 0x0004
	AttrCumulativeEnergyReset    uint32 = 0x0005
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "IMPE", Name: "ImportedEnergy"},
			{Bit: 1, Code: "EXPE", Name: "ExportedEnergy"},
			{Bit: 2, Code: "CUME", Name: "CumulativeEnergy"},
			{Bit: 3, Code: "PERE", Name: "PeriodicEnergy"},
			{Bit: 4, Code: "APPE", Name: "ApparentEnergy"},
			{Bit: 5, Code: "REAE", Name: "ReactiveEnergy"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrAccuracy, Name: "Accuracy", DisplayName: "Accuracy", Type: "struct", Readable: true},
			{ID: AttrCumulativeEnergyImported, Name: "CumulativeEnergyImported", DisplayName: "CumulativeEnergyImported", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCumulativeEnergyExported, Name: "CumulativeEnergyExported", DisplayName: "CumulativeEnergyExported", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrPeriodicEnergyImported, Name: "PeriodicEnergyImported", DisplayName: "PeriodicEnergyImported", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrPeriodicEnergyExported, Name: "PeriodicEnergyExported", DisplayName: "PeriodicEnergyExported", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCumulativeEnergyReset, Name: "CumulativeEnergyReset", DisplayName: "CumulativeEnergyReset", Type: "struct", Readable: true, Nullable: true},
		},
	})
}
