// Code generated by cmd/codegen; DO NOT EDIT.

// Package timeformatlocalization implements the Matter Time Format Localization cluster (0x002C).
package timeformatlocalization

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Time Format Localization.
	ID uint32 = 0x002C
	// Name is the CLI-friendly cluster name.
	Name = "TimeFormatLocalization"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Time Format Localization"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureCalendarFormat uint32 = 1 << 0 // CALFMT
)

// Attribute IDs.
const (
	AttrHourFormat             uint32 = 0x0000
	AttrActiveCalendarType     uint32 = 0x0001
	AttrSupportedCalendarTypes uint32 = 0x0002
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CALFMT", Name: "CalendarFormat"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrHourFormat, Name: "HourFormat", DisplayName: "HourFormat", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrActiveCalendarType, Name: "ActiveCalendarType", DisplayName: "ActiveCalendarType", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrSupportedCalendarTypes, Name: "SupportedCalendarTypes", DisplayName: "SupportedCalendarTypes", Type: "list", Readable: true},
		},
	})
}
