// Code generated by cmd/codegen; DO NOT EDIT.

// Package lowpower implements the Matter Low Power cluster (0x0508).
package lowpower

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Low Power.
	ID uint32 = 0x0508
	// Name is the CLI-friendly cluster name.
	Name = "LowPower"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Low Power"
)

// Command IDs.
const (
	CmdSleep uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdSleep, Name: "Sleep", DisplayName: "Sleep"},
		},
	})
}
