// Code generated by cmd/codegen; DO NOT EDIT.

// Package targetnavigator implements the Matter Target Navigator cluster (0x0505).
package targetnavigator

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Target Navigator.
	ID uint32 = 0x0505
	// Name is the CLI-friendly cluster name.
	Name = "TargetNavigator"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Target Navigator"
)

// Attribute IDs.
const (
	AttrTargetList    uint32 = 0x0000
	AttrCurrentTarget uint32 = 0x0001
)

// Command IDs.
const (
	CmdNavigateTarget uint32 = 0x00
)

// NavigateTargetRequest is the request payload for the NavigateTarget command.
type NavigateTargetRequest struct {
	Target uint8  `tlv:"0,uint"`
	Data   string `tlv:"1,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTargetList, Name: "TargetList", DisplayName: "TargetList", Type: "list", Readable: true},
			{ID: AttrCurrentTarget, Name: "CurrentTarget", DisplayName: "CurrentTarget", Type: "uint8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdNavigateTarget, Name: "NavigateTarget", DisplayName: "NavigateTarget", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Target", DisplayName: "Target", Type: "uint8"},
				{ID: 1, Name: "Data", DisplayName: "Data", Type: "string", Optional: true},
			}},
		},
	})
}
