// Code generated by cmd/codegen; DO NOT EDIT.

// Package flowmeasurement implements the Matter Flow Measurement cluster (0x0404).
package flowmeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Flow Measurement.
	ID uint32 = 0x0404
	// Name is the CLI-friendly cluster name.
	Name = "FlowMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Flow Measurement"
)

// Attribute IDs.
const (
	AttrMeasuredValue    uint32 = 0x0000
	AttrMinMeasuredValue uint32 = 0x0001
	AttrMaxMeasuredValue uint32 = 0x0002
	AttrTolerance        uint32 = 0x0003
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMeasuredValue, Name: "MeasuredValue", DisplayName: "MeasuredValue", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMinMeasuredValue, Name: "MinMeasuredValue", DisplayName: "MinMeasuredValue", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMaxMeasuredValue, Name: "MaxMeasuredValue", DisplayName: "MaxMeasuredValue", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrTolerance, Name: "Tolerance", DisplayName: "Tolerance", Type: "uint16", Readable: true},
		},
	})
}
