// Code generated by cmd/codegen; DO NOT EDIT.

// Package rvcoperationalstate implements the Matter RVC Operational State cluster (0x0061).
package rvcoperationalstate

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for RVC Operational State.
	ID uint32 = 0x0061
	// Name is the CLI-friendly cluster name.
	Name = "RVCOperationalState"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "RVC Operational State"
)

// Command IDs.
const (
	CmdGoHome uint32 = 0x80
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdGoHome, Name: "GoHome", DisplayName: "GoHome", HasResponse: true},
		},
	})
}
