// Code generated by cmd/codegen; DO NOT EDIT.

// Package commoditymetering implements the Matter Commodity Metering cluster (0x0B07).
package commoditymetering

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Commodity Metering.
	ID uint32 = 0x0B07
	// Name is the CLI-friendly cluster name.
	Name = "CommodityMetering"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Commodity Metering"
)

// Attribute IDs.
const (
	AttrMeteredQuantity          uint32 = 0x0000
	AttrMeteredQuantityTimestamp uint32 = 0x0001
	AttrTariffUnit               uint32 = 0x0002
	AttrMaximumMeteredQuantities uint32 = 0x0003
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMeteredQuantity, Name: "MeteredQuantity", DisplayName: "MeteredQuantity", Type: "list", Readable: true, Nullable: true},
			{ID: AttrMeteredQuantityTimestamp, Name: "MeteredQuantityTimestamp", DisplayName: "MeteredQuantityTimestamp", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrTariffUnit, Name: "TariffUnit", DisplayName: "TariffUnit", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrMaximumMeteredQuantities, Name: "MaximumMeteredQuantities", DisplayName: "MaximumMeteredQuantities", Type: "uint16", Readable: true, Nullable: true},
		},
	})
}
