// Code generated by cmd/codegen; DO NOT EDIT.

// Package threadnetworkdirectory implements the Matter Thread Network Directory cluster (0x0453).
package threadnetworkdirectory

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Thread Network Directory.
	ID uint32 = 0x0453
	// Name is the CLI-friendly cluster name.
	Name = "ThreadNetworkDirectory"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Thread Network Directory"
)

// Attribute IDs.
const (
	AttrPreferredExtendedPanID uint32 = 0x0000
	AttrThreadNetworks         uint32 = 0x0001
	AttrThreadNetworkTableSize uint32 = 0x0002
)

// Command IDs.
const (
	CmdAddNetwork            uint32 = 0x00
	CmdRemoveNetwork         uint32 = 0x01
	CmdGetOperationalDataset uint32 = 0x02
)

// AddNetworkRequest is the request payload for the AddNetwork command.
type AddNetworkRequest struct {
	OperationalDataset []byte `tlv:"0,bytes"`
}

// RemoveNetworkRequest is the request payload for the RemoveNetwork command.
type RemoveNetworkRequest struct {
	ExtendedPanID []byte `tlv:"0,bytes"`
}

// GetOperationalDatasetRequest is the request payload for the GetOperationalDataset command.
type GetOperationalDatasetRequest struct {
	ExtendedPanID []byte `tlv:"0,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrPreferredExtendedPanID, Name: "PreferredExtendedPanID", DisplayName: "PreferredExtendedPanID", Type: "octets", Readable: true, Writable: true, Nullable: true},
			{ID: AttrThreadNetworks, Name: "ThreadNetworks", DisplayName: "ThreadNetworks", Type: "list", Readable: true},
			{ID: AttrThreadNetworkTableSize, Name: "ThreadNetworkTableSize", DisplayName: "ThreadNetworkTableSize", Type: "uint8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAddNetwork, Name: "AddNetwork", DisplayName: "AddNetwork", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OperationalDataset", DisplayName: "OperationalDataset", Type: "octets"},
			}},
			{ID: CmdRemoveNetwork, Name: "RemoveNetwork", DisplayName: "RemoveNetwork", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ExtendedPanID", DisplayName: "ExtendedPanID", Type: "octets"},
			}},
			{ID: CmdGetOperationalDataset, Name: "GetOperationalDataset", DisplayName: "GetOperationalDataset", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ExtendedPanID", DisplayName: "ExtendedPanID", Type: "octets"},
			}},
		},
	})
}
