// Code generated by cmd/codegen; DO NOT EDIT.

// Package dishwasheralarm implements the Matter Dishwasher Alarm cluster (0x005D).
package dishwasheralarm

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Dishwasher Alarm.
	ID uint32 = 0x005D
	// Name is the CLI-friendly cluster name.
	Name = "DishwasherAlarm"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Dishwasher Alarm"
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
	})
}
