// Code generated by cmd/codegen; DO NOT EDIT.

// Package commissionercontrol implements the Matter Commissioner Control cluster (0x0751).
package commissionercontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Commissioner Control.
	ID uint32 = 0x0751
	// Name is the CLI-friendly cluster name.
	Name = "CommissionerControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Commissioner Control"
)

// Attribute IDs.
const (
	AttrSupportedDeviceCategories uint32 = 0x0000
)

// Command IDs.
const (
	CmdRequestCommissioningApproval uint32 = 0x00
	CmdCommissionNode               uint32 = 0x01
)

// RequestCommissioningApprovalRequest is the request payload for the RequestCommissioningApproval command.
type RequestCommissioningApprovalRequest struct {
	RequestID uint64 `tlv:"0,uint"`
	VendorID  uint16 `tlv:"1,uint"`
	ProductID uint16 `tlv:"2,uint"`
	Label     string `tlv:"3,utf8"`
}

// CommissionNodeRequest is the request payload for the CommissionNode command.
type CommissionNodeRequest struct {
	RequestID              uint64 `tlv:"0,uint"`
	ResponseTimeoutSeconds uint16 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedDeviceCategories, Name: "SupportedDeviceCategories", DisplayName: "SupportedDeviceCategories", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdRequestCommissioningApproval, Name: "RequestCommissioningApproval", DisplayName: "RequestCommissioningApproval", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "RequestID", DisplayName: "RequestID", Type: "uint64"},
				{ID: 1, Name: "VendorID", DisplayName: "VendorID", Type: "uint16"},
				{ID: 2, Name: "ProductID", DisplayName: "ProductID", Type: "uint16"},
				{ID: 3, Name: "Label", DisplayName: "Label", Type: "string", Optional: true},
			}},
			{ID: CmdCommissionNode, Name: "CommissionNode", DisplayName: "CommissionNode", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "RequestID", DisplayName: "RequestID", Type: "uint64"},
				{ID: 1, Name: "ResponseTimeoutSeconds", DisplayName: "ResponseTimeoutSeconds", Type: "uint16"},
			}},
		},
	})
}
