// Code generated by cmd/codegen; DO NOT EDIT.

// Package unitlocalization implements the Matter Unit Localization cluster (0x002D).
package unitlocalization

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Unit Localization.
	ID uint32 = 0x002D
	// Name is the CLI-friendly cluster name.
	Name = "UnitLocalization"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Unit Localization"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTemperatureUnit uint32 = 1 << 0 // TEMP
)

// Attribute IDs.
const (
	AttrTemperatureUnit           uint32 = 0x0000
	AttrSupportedTemperatureUnits uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TEMP", Name: "TemperatureUnit"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTemperatureUnit, Name: "TemperatureUnit", DisplayName: "TemperatureUnit", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrSupportedTemperatureUnits, Name: "SupportedTemperatureUnits", DisplayName: "SupportedTemperatureUnits", Type: "list", Readable: true},
		},
	})
}
