// Code generated by cmd/codegen; DO NOT EDIT.

// Package commoditytariff implements the Matter Commodity Tariff cluster (0x0700).
package commoditytariff

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Commodity Tariff.
	ID uint32 = 0x0700
	// Name is the CLI-friendly cluster name.
	Name = "CommodityTariff"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Commodity Tariff"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePricing        uint32 = 1 << 0 // PRICE
	FeatureFriendlyCredit uint32 = 1 << 1 // FCRED
	FeatureAuxiliaryLoad  uint32 = 1 << 2 // AUXLD
	FeaturePeakPeriod     uint32 = 1 << 3 // PEAKP
	FeaturePowerThreshold uint32 = 1 << 4 // PWRTHLD
	FeatureRandomization  uint32 = 1 << 5 // RNDM
)

// Attribute IDs.
const (
	AttrTariffInfo                 uint32 = 0x0000
	AttrTariffUnit                 uint32 = 0x0001
	AttrStartDate                  uint32 = 0x0002
	AttrDayEntries                 uint32 = 0x0003
	AttrDayPatterns                uint32 = 0x0004
	AttrCalendarPeriods            uint32 = 0x0005
	AttrIndividualDays             uint32 = 0x0006
	AttrCurrentDay                 uint32 = 0x0007
	AttrNextDay                    uint32 = 0x0008
	AttrCurrentDayEntry            uint32 = 0x0009
	AttrCurrentDayEntryDate        uint32 = 0x000A
	AttrNextDayEntry               uint32 = 0x000B
	AttrNextDayEntryDate           uint32 = 0x000C
	AttrTariffComponents           uint32 = 0x000D
	AttrTariffPeriods              uint32 = 0x000E
	AttrCurrentTariffComponents    uint32 = 0x000F
	AttrNextTariffComponents       uint32 = 0x0010
	AttrDefaultRandomizationOffset uint32 = 0x0011
	AttrDefaultRandomizationType   uint32 = 0x0012
)

// Command IDs.
const (
	CmdGetTariffComponent uint32 = 0x00
	CmdGetDayEntry        uint32 = 0x01
)

// GetTariffComponentRequest is the request payload for the GetTariffComponent command.
type GetTariffComponentRequest struct {
	TariffComponentID uint32 `tlv:"0,uint"`
}

// GetDayEntryRequest is the request payload for the GetDayEntry command.
type GetDayEntryRequest struct {
	DayEntryID uint32 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PRICE", Name: "Pricing"},
			{Bit: 1, Code: "FCRED", Name: "FriendlyCredit"},
			{Bit: 2, Code: "AUXLD", Name: "AuxiliaryLoad"},
			{Bit: 3, Code: "PEAKP", Name: "PeakPeriod"},
			{Bit: 4, Code: "PWRTHLD", Name: "PowerThreshold"},
			{Bit: 5, Code: "RNDM", Name: "Randomization"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTariffInfo, Name: "TariffInfo", DisplayName: "TariffInfo", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrTariffUnit, Name: "TariffUnit", DisplayName: "TariffUnit", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrStartDate, Name: "StartDate", DisplayName: "StartDate", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrDayEntries, Name: "DayEntries", DisplayName: "DayEntries", Type: "list", Readable: true, Nullable: true},
			{ID: AttrDayPatterns, Name: "DayPatterns", DisplayName: "DayPatterns", Type: "list", Readable: true, Nullable: true},
			{ID: AttrCalendarPeriods, Name: "CalendarPeriods", DisplayName: "CalendarPeriods", Type: "list", Readable: true, Nullable: true},
			{ID: AttrIndividualDays, Name: "IndividualDays", DisplayName: "IndividualDays", Type: "list", Readable: true, Nullable: true},
			{ID: AttrCurrentDay, Name: "CurrentDay", DisplayName: "CurrentDay", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrNextDay, Name: "NextDay", DisplayName: "NextDay", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCurrentDayEntry, Name: "CurrentDayEntry", DisplayName: "CurrentDayEntry", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCurrentDayEntryDate, Name: "CurrentDayEntryDate", DisplayName: "CurrentDayEntryDate", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrNextDayEntry, Name: "NextDayEntry", DisplayName: "NextDayEntry", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrNextDayEntryDate, Name: "NextDayEntryDate", DisplayName: "NextDayEntryDate", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrTariffComponents, Name: "TariffComponents", DisplayName: "TariffComponents", Type: "list", Readable: true, Nullable: true},
			{ID: AttrTariffPeriods, Name: "TariffPeriods", DisplayName: "TariffPeriods", Type: "list", Readable: true, Nullable: true},
			{ID: AttrCurrentTariffComponents, Name: "CurrentTariffComponents", DisplayName: "CurrentTariffComponents", Type: "list", Readable: true, Nullable: true},
			{ID: AttrNextTariffComponents, Name: "NextTariffComponents", DisplayName: "NextTariffComponents", Type: "list", Readable: true, Nullable: true},
			{ID: AttrDefaultRandomizationOffset, Name: "DefaultRandomizationOffset", DisplayName: "DefaultRandomizationOffset", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrDefaultRandomizationType, Name: "DefaultRandomizationType", DisplayName: "DefaultRandomizationType", Type: "enum8", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdGetTariffComponent, Name: "GetTariffComponent", DisplayName: "GetTariffComponent", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TariffComponentID", DisplayName: "TariffComponentID", Type: "uint32"},
			}},
			{ID: CmdGetDayEntry, Name: "GetDayEntry", DisplayName: "GetDayEntry", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DayEntryID", DisplayName: "DayEntryID", Type: "uint32"},
			}},
		},
	})
}
