// Copyright 2026 matter-cli contributors
// SPDX-License-Identifier: Apache-2.0

package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// clusterTmpl is the Go source template for a generated cluster package.
var clusterTmpl = template.Must(template.New("cluster").Funcs(template.FuncMap{
	"hex": func(v uint32) string { return fmt.Sprintf("0x%04X", v) },
	"hexCmd": func(v uint32) string {
		if v <= 0xFF {
			return fmt.Sprintf("0x%02X", v)
		}
		return fmt.Sprintf("0x%04X", v)
	},
}).Parse(clusterTemplate))

const clusterTemplate = `// Code generated by cmd/codegen; DO NOT EDIT.

// Package {{.PackageName}} implements the Matter {{.DisplayName}} cluster ({{hex .ID}}).
package {{.PackageName}}

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for {{.DisplayName}}.
	ID uint32 = {{hex .ID}}
	// Name is the CLI-friendly cluster name.
	Name = "{{.Name}}"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "{{.DisplayName}}"
)
{{- if .Features}}

// Feature bits for the FeatureMap attribute.
const (
{{- range .Features}}
	Feature{{.Name}} uint32 = 1 << {{.Bit}} // {{.Code}}
{{- end}}
)
{{- end}}
{{- if .Attributes}}

// Attribute IDs.
const (
{{- range .Attributes}}
	Attr{{.Name}} uint32 = {{hex .ID}}
{{- end}}
)
{{- end}}
{{- if .Commands}}

// Command IDs.
const (
{{- range .Commands}}
	Cmd{{.Name}} uint32 = {{hexCmd .ID}}
{{- end}}
)
{{- end}}
{{- range .Commands}}{{if .HasRequest}}

// {{.Name}}Request is the request payload for the {{.Name}} command.
type {{.Name}}Request struct {
{{- range .Fields}}
	{{.Name}} {{.GoType}} ` + "`" + `tlv:"{{.ID}},{{.TLVKind}}"` + "`" + `
{{- end}}
}
{{- end}}{{end}}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
{{- if .Features}}
		Features: []clusters.FeatureInfo{
{{- range .Features}}
			{Bit: {{.Bit}}, Code: "{{.Code}}", Name: "{{.Name}}"},
{{- end}}
		},
{{- end}}
{{- if .Attributes}}
		Attributes: []clusters.AttributeInfo{
{{- range .Attributes}}
			{ID: Attr{{.Name}}, Name: "{{.Name}}", DisplayName: "{{.Name}}", Type: "{{.Type}}", Readable: {{.Readable}}{{if .Writable}}, Writable: true{{end}}{{if .Optional}}, Optional: true{{end}}{{if .Nullable}}, Nullable: true{{end}}},
{{- end}}
		},
{{- end}}
{{- if .Commands}}
		Commands: []clusters.CommandInfo{
{{- range .Commands}}
			{ID: Cmd{{.Name}}, Name: "{{.Name}}", DisplayName: "{{.Name}}"{{if .HasRequest}}, HasRequest: true{{end}}{{if .HasResponse}}, HasResponse: true{{end}}{{if .Fields}}, RequestFields: []clusters.CommandFieldInfo{
{{- range .Fields}}
				{ID: {{.ID}}, Name: "{{.Name}}", DisplayName: "{{.Name}}", Type: "{{.Type}}"{{if .Optional}}, Optional: true{{end}}{{if .Nullable}}, Nullable: true{{end}}},
{{- end}}
			}{{end}}},
{{- end}}
		},
{{- end}}
	})
}
`

// Generate produces the Go source code for a single Cluster.
func Generate(c *Cluster) ([]byte, error) {
	var buf bytes.Buffer
	if err := clusterTmpl.Execute(&buf, c); err != nil {
		return nil, fmt.Errorf("template execute: %w", err)
	}

	// gofmt the output.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source for debugging.
		return buf.Bytes(), fmt.Errorf("gofmt: %w (raw source returned)", err)
	}
	return formatted, nil
}

// WriteCluster generates and writes a cluster Go file to outputDir/<pkgname>/cluster.go.
func WriteCluster(c *Cluster, outputDir string) error {
	src, err := Generate(c)
	if err != nil {
		return err
	}

	dir := filepath.Join(outputDir, c.PackageName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	path := filepath.Join(dir, "cluster.go")
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// GenerateAllImports produces an all/all.go file that blank-imports every
// generated cluster package so their init() functions fire. Consumer packages
// only need to import this one package.
func GenerateAllImports(clusters []Cluster, modulePath, outputDir string) error {
	// Deduplicate by package name.
	seen := make(map[string]bool)
	var pkgs []string
	for _, c := range clusters {
		if seen[c.PackageName] {
			continue
		}
		seen[c.PackageName] = true
		pkgs = append(pkgs, c.PackageName)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/codegen; DO NOT EDIT.\n\n")
	buf.WriteString("// Package all imports every generated Matter cluster package so\n")
	buf.WriteString("// their init() registrations fire.\n")
	buf.WriteString("package all\n\n")
	if len(pkgs) > 0 {
		buf.WriteString("import (\n")
		for _, pkg := range pkgs {
			fmt.Fprintf(&buf, "\t_ \"%s/internal/clusters/%s\"\n", modulePath, pkg)
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt all imports: %w", err)
	}

	dir := filepath.Join(outputDir, "all")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	path := filepath.Join(dir, "all.go")
	return os.WriteFile(path, formatted, 0o644)
}

// GenerateAll parses all XML files in xmlDir and writes generated Go packages
// under outputDir. Returns the list of all generated clusters.
func GenerateAll(xmlDir, outputDir, modulePath string) ([]Cluster, error) {
	entries, err := os.ReadDir(xmlDir)
	if err != nil {
		return nil, fmt.Errorf("read xml dir: %w", err)
	}

	var allClusters []Cluster
	var errs []string

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".xml") {
			continue
		}
		path := filepath.Join(xmlDir, entry.Name())
		clusters, err := ParseFile(path)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", entry.Name(), err))
			continue
		}
		for i := range clusters {
			if err := WriteCluster(&clusters[i], outputDir); err != nil {
				errs = append(errs, fmt.Sprintf("%s (%s): %v", entry.Name(), clusters[i].Name, err))
				continue
			}
			allClusters = append(allClusters, clusters[i])
		}
	}

	if len(errs) > 0 {
		fmt.Fprintf(os.Stderr, "warnings during generation:\n")
		for _, e := range errs {
			fmt.Fprintf(os.Stderr, "  - %s\n", e)
		}
	}

	return allClusters, nil
}
