// Code generated by cmd/codegen; DO NOT EDIT.

// Package jointfabricdatastore implements the Matter Joint Fabric Datastore cluster (0x0752).
package jointfabricdatastore

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Joint Fabric Datastore.
	ID uint32 = 0x0752
	// Name is the CLI-friendly cluster name.
	Name = "JointFabricDatastore"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Joint Fabric Datastore"
)

// Attribute IDs.
const (
	AttrAnchorRootCA        uint32 = 0x0000
	AttrAnchorNodeID        uint32 = 0x0001
	AttrAnchorVendorID      uint32 = 0x0002
	AttrFriendlyName        uint32 = 0x0003
	AttrGroupKeySetList     uint32 = 0x0004
	AttrGroupList           uint32 = 0x0005
	AttrNodeList            uint32 = 0x0006
	AttrAdminList           uint32 = 0x0007
	AttrStatus              uint32 = 0x0008
	AttrEndpointGroupIDList uint32 = 0x0009
	AttrEndpointBindingList uint32 = 0x000A
	AttrNodeKeySetList      uint32 = 0x000B
	AttrNodeACLList         uint32 = 0x000C
	AttrNodeEndpointList    uint32 = 0x000D
)

// Command IDs.
const (
	CmdAddKeySet                        uint32 = 0x00
	CmdUpdateKeySet                     uint32 = 0x01
	CmdRemoveKeySet                     uint32 = 0x02
	CmdAddGroup                         uint32 = 0x03
	CmdUpdateGroup                      uint32 = 0x04
	CmdRemoveGroup                      uint32 = 0x05
	CmdAddAdmin                         uint32 = 0x06
	CmdUpdateAdmin                      uint32 = 0x07
	CmdRemoveAdmin                      uint32 = 0x08
	CmdAddPendingNode                   uint32 = 0x09
	CmdRefreshNode                      uint32 = 0x0A
	CmdUpdateNode                       uint32 = 0x0B
	CmdRemoveNode                       uint32 = 0x0C
	CmdUpdateEndpointForNode            uint32 = 0x0D
	CmdAddGroupIDToEndpointForNode      uint32 = 0x0E
	CmdRemoveGroupIDFromEndpointForNode uint32 = 0x0F
	CmdAddBindingToEndpointForNode      uint32 = 0x10
	CmdRemoveBindingFromEndpointForNode uint32 = 0x11
	CmdAddACLToNode                     uint32 = 0x12
	CmdRemoveACLFromNode                uint32 = 0x13
)

// AddKeySetRequest is the request payload for the AddKeySet command.
type AddKeySetRequest struct {
	GroupKeySet uint8 `tlv:"0,uint"`
}

// UpdateKeySetRequest is the request payload for the UpdateKeySet command.
type UpdateKeySetRequest struct {
	GroupKeySet uint8 `tlv:"0,uint"`
}

// RemoveKeySetRequest is the request payload for the RemoveKeySet command.
type RemoveKeySetRequest struct {
	GroupKeySetID uint16 `tlv:"0,uint"`
}

// AddGroupRequest is the request payload for the AddGroup command.
type AddGroupRequest struct {
	GroupID         uint16 `tlv:"0,uint"`
	FriendlyName    string `tlv:"1,utf8"`
	GroupKeySetID   uint16 `tlv:"2,uint"`
	GroupCAT        uint16 `tlv:"3,uint"`
	GroupCATVersion uint16 `tlv:"4,uint"`
	GroupPermission uint8  `tlv:"5,uint"`
}

// UpdateGroupRequest is the request payload for the UpdateGroup command.
type UpdateGroupRequest struct {
	GroupID         uint16 `tlv:"0,uint"`
	FriendlyName    string `tlv:"1,utf8"`
	GroupKeySetID   uint16 `tlv:"2,uint"`
	GroupCAT        uint16 `tlv:"3,uint"`
	GroupCATVersion uint16 `tlv:"4,uint"`
	GroupPermission uint8  `tlv:"5,uint"`
}

// RemoveGroupRequest is the request payload for the RemoveGroup command.
type RemoveGroupRequest struct {
	GroupID uint16 `tlv:"0,uint"`
}

// AddAdminRequest is the request payload for the AddAdmin command.
type AddAdminRequest struct {
	NodeID       uint64 `tlv:"1,uint"`
	FriendlyName string `tlv:"2,utf8"`
	VendorID     uint16 `tlv:"3,uint"`
	ICAC         []byte `tlv:"4,bytes"`
}

// UpdateAdminRequest is the request payload for the UpdateAdmin command.
type UpdateAdminRequest struct {
	NodeID       uint64 `tlv:"0,uint"`
	FriendlyName string `tlv:"1,utf8"`
	ICAC         []byte `tlv:"2,bytes"`
}

// RemoveAdminRequest is the request payload for the RemoveAdmin command.
type RemoveAdminRequest struct {
	NodeID uint64 `tlv:"0,uint"`
}

// AddPendingNodeRequest is the request payload for the AddPendingNode command.
type AddPendingNodeRequest struct {
	NodeID       uint64 `tlv:"0,uint"`
	FriendlyName string `tlv:"1,utf8"`
}

// RefreshNodeRequest is the request payload for the RefreshNode command.
type RefreshNodeRequest struct {
	NodeID uint64 `tlv:"0,uint"`
}

// UpdateNodeRequest is the request payload for the UpdateNode command.
type UpdateNodeRequest struct {
	NodeID       uint64 `tlv:"0,uint"`
	FriendlyName string `tlv:"1,utf8"`
}

// RemoveNodeRequest is the request payload for the RemoveNode command.
type RemoveNodeRequest struct {
	NodeID uint64 `tlv:"0,uint"`
}

// UpdateEndpointForNodeRequest is the request payload for the UpdateEndpointForNode command.
type UpdateEndpointForNodeRequest struct {
	EndpointID   uint16 `tlv:"0,uint"`
	NodeID       uint64 `tlv:"1,uint"`
	FriendlyName string `tlv:"2,utf8"`
}

// AddGroupIDToEndpointForNodeRequest is the request payload for the AddGroupIDToEndpointForNode command.
type AddGroupIDToEndpointForNodeRequest struct {
	NodeID     uint64 `tlv:"0,uint"`
	EndpointID uint16 `tlv:"1,uint"`
	GroupID    uint16 `tlv:"2,uint"`
}

// RemoveGroupIDFromEndpointForNodeRequest is the request payload for the RemoveGroupIDFromEndpointForNode command.
type RemoveGroupIDFromEndpointForNodeRequest struct {
	NodeID     uint64 `tlv:"0,uint"`
	EndpointID uint16 `tlv:"1,uint"`
	GroupID    uint16 `tlv:"2,uint"`
}

// AddBindingToEndpointForNodeRequest is the request payload for the AddBindingToEndpointForNode command.
type AddBindingToEndpointForNodeRequest struct {
	NodeID     uint64 `tlv:"0,uint"`
	EndpointID uint16 `tlv:"1,uint"`
	Binding    uint8  `tlv:"2,uint"`
}

// RemoveBindingFromEndpointForNodeRequest is the request payload for the RemoveBindingFromEndpointForNode command.
type RemoveBindingFromEndpointForNodeRequest struct {
	ListID     uint16 `tlv:"0,uint"`
	EndpointID uint16 `tlv:"1,uint"`
	NodeID     uint64 `tlv:"2,uint"`
}

// AddACLToNodeRequest is the request payload for the AddACLToNode command.
type AddACLToNodeRequest struct {
	NodeID   uint64 `tlv:"0,uint"`
	ACLEntry uint8  `tlv:"1,uint"`
}

// RemoveACLFromNodeRequest is the request payload for the RemoveACLFromNode command.
type RemoveACLFromNodeRequest struct {
	ListID uint16 `tlv:"0,uint"`
	NodeID uint64 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrAnchorRootCA, Name: "AnchorRootCA", DisplayName: "AnchorRootCA", Type: "octets", Readable: true},
			{ID: AttrAnchorNodeID, Name: "AnchorNodeID", DisplayName: "AnchorNodeID", Type: "uint64", Readable: true},
			{ID: AttrAnchorVendorID, Name: "AnchorVendorID", DisplayName: "AnchorVendorID", Type: "uint16", Readable: true},
			{ID: AttrFriendlyName, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string", Readable: true},
			{ID: AttrGroupKeySetList, Name: "GroupKeySetList", DisplayName: "GroupKeySetList", Type: "list", Readable: true},
			{ID: AttrGroupList, Name: "GroupList", DisplayName: "GroupList", Type: "list", Readable: true},
			{ID: AttrNodeList, Name: "NodeList", DisplayName: "NodeList", Type: "list", Readable: true},
			{ID: AttrAdminList, Name: "AdminList", DisplayName: "AdminList", Type: "list", Readable: true},
			{ID: AttrStatus, Name: "Status", DisplayName: "Status", Type: "struct", Readable: true},
			{ID: AttrEndpointGroupIDList, Name: "EndpointGroupIDList", DisplayName: "EndpointGroupIDList", Type: "list", Readable: true},
			{ID: AttrEndpointBindingList, Name: "EndpointBindingList", DisplayName: "EndpointBindingList", Type: "list", Readable: true},
			{ID: AttrNodeKeySetList, Name: "NodeKeySetList", DisplayName: "NodeKeySetList", Type: "list", Readable: true},
			{ID: AttrNodeACLList, Name: "NodeACLList", DisplayName: "NodeACLList", Type: "list", Readable: true},
			{ID: AttrNodeEndpointList, Name: "NodeEndpointList", DisplayName: "NodeEndpointList", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAddKeySet, Name: "AddKeySet", DisplayName: "AddKeySet", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySet", DisplayName: "GroupKeySet", Type: "struct"},
			}},
			{ID: CmdUpdateKeySet, Name: "UpdateKeySet", DisplayName: "UpdateKeySet", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySet", DisplayName: "GroupKeySet", Type: "struct"},
			}},
			{ID: CmdRemoveKeySet, Name: "RemoveKeySet", DisplayName: "RemoveKeySet", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupKeySetID", DisplayName: "GroupKeySetID", Type: "uint16"},
			}},
			{ID: CmdAddGroup, Name: "AddGroup", DisplayName: "AddGroup", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string"},
				{ID: 2, Name: "GroupKeySetID", DisplayName: "GroupKeySetID", Type: "uint16", Nullable: true},
				{ID: 3, Name: "GroupCAT", DisplayName: "GroupCAT", Type: "uint16", Nullable: true},
				{ID: 4, Name: "GroupCATVersion", DisplayName: "GroupCATVersion", Type: "uint16", Nullable: true},
				{ID: 5, Name: "GroupPermission", DisplayName: "GroupPermission", Type: "enum8"},
			}},
			{ID: CmdUpdateGroup, Name: "UpdateGroup", DisplayName: "UpdateGroup", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string", Nullable: true},
				{ID: 2, Name: "GroupKeySetID", DisplayName: "GroupKeySetID", Type: "uint16", Nullable: true},
				{ID: 3, Name: "GroupCAT", DisplayName: "GroupCAT", Type: "uint16", Nullable: true},
				{ID: 4, Name: "GroupCATVersion", DisplayName: "GroupCATVersion", Type: "uint16", Nullable: true},
				{ID: 5, Name: "GroupPermission", DisplayName: "GroupPermission", Type: "enum8", Nullable: true},
			}},
			{ID: CmdRemoveGroup, Name: "RemoveGroup", DisplayName: "RemoveGroup", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdAddAdmin, Name: "AddAdmin", DisplayName: "AddAdmin", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 1, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 2, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string"},
				{ID: 3, Name: "VendorID", DisplayName: "VendorID", Type: "uint16"},
				{ID: 4, Name: "ICAC", DisplayName: "ICAC", Type: "octets"},
			}},
			{ID: CmdUpdateAdmin, Name: "UpdateAdmin", DisplayName: "UpdateAdmin", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64", Nullable: true},
				{ID: 1, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string", Nullable: true},
				{ID: 2, Name: "ICAC", DisplayName: "ICAC", Type: "octets", Nullable: true},
			}},
			{ID: CmdRemoveAdmin, Name: "RemoveAdmin", DisplayName: "RemoveAdmin", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
			}},
			{ID: CmdAddPendingNode, Name: "AddPendingNode", DisplayName: "AddPendingNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string"},
			}},
			{ID: CmdRefreshNode, Name: "RefreshNode", DisplayName: "RefreshNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
			}},
			{ID: CmdUpdateNode, Name: "UpdateNode", DisplayName: "UpdateNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string"},
			}},
			{ID: CmdRemoveNode, Name: "RemoveNode", DisplayName: "RemoveNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
			}},
			{ID: CmdUpdateEndpointForNode, Name: "UpdateEndpointForNode", DisplayName: "UpdateEndpointForNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint16"},
				{ID: 1, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 2, Name: "FriendlyName", DisplayName: "FriendlyName", Type: "string"},
			}},
			{ID: CmdAddGroupIDToEndpointForNode, Name: "AddGroupIDToEndpointForNode", DisplayName: "AddGroupIDToEndpointForNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint16"},
				{ID: 2, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdRemoveGroupIDFromEndpointForNode, Name: "RemoveGroupIDFromEndpointForNode", DisplayName: "RemoveGroupIDFromEndpointForNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint16"},
				{ID: 2, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdAddBindingToEndpointForNode, Name: "AddBindingToEndpointForNode", DisplayName: "AddBindingToEndpointForNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint16"},
				{ID: 2, Name: "Binding", DisplayName: "Binding", Type: "struct"},
			}},
			{ID: CmdRemoveBindingFromEndpointForNode, Name: "RemoveBindingFromEndpointForNode", DisplayName: "RemoveBindingFromEndpointForNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ListID", DisplayName: "ListID", Type: "uint16"},
				{ID: 1, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint16"},
				{ID: 2, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
			}},
			{ID: CmdAddACLToNode, Name: "AddACLToNode", DisplayName: "AddACLToNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
				{ID: 1, Name: "ACLEntry", DisplayName: "ACLEntry", Type: "struct"},
			}},
			{ID: CmdRemoveACLFromNode, Name: "RemoveACLFromNode", DisplayName: "RemoveACLFromNode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ListID", DisplayName: "ListID", Type: "uint16"},
				{ID: 1, Name: "NodeID", DisplayName: "NodeID", Type: "uint64"},
			}},
		},
	})
}
