// Code generated by cmd/codegen; DO NOT EDIT.

// Package pumpconfigurationandcontrol implements the Matter Pump Configuration and Control cluster (0x0200).
package pumpconfigurationandcontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Pump Configuration and Control.
	ID uint32 = 0x0200
	// Name is the CLI-friendly cluster name.
	Name = "PumpConfigurationAndControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Pump Configuration and Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureConstantPressure    uint32 = 1 << 0 // PRSCONST
	FeatureCompensatedPressure uint32 = 1 << 1 // PRSCOMP
	FeatureConstantFlow        uint32 = 1 << 2 // FLW
	FeatureConstantSpeed       uint32 = 1 << 3 // SPD
	FeatureConstantTemperature uint32 = 1 << 4 // TEMP
	FeatureAutomatic           uint32 = 1 << 5 // AUTO
	FeatureLocalOperation      uint32 = 1 << 6 // LOCAL
)

// Attribute IDs.
const (
	AttrMaxPressure            uint32 = 0x0000
	AttrMaxSpeed               uint32 = 0x0001
	AttrMaxFlow                uint32 = 0x0002
	AttrMinConstPressure       uint32 = 0x0003
	AttrMaxConstPressure       uint32 = 0x0004
	AttrMinCompPressure        uint32 = 0x0005
	AttrMaxCompPressure        uint32 = 0x0006
	AttrMinConstSpeed          uint32 = 0x0007
	AttrMaxConstSpeed          uint32 = 0x0008
	AttrMinConstFlow           uint32 = 0x0009
	AttrMaxConstFlow           uint32 = 0x000A
	AttrMinConstTemp           uint32 = 0x000B
	AttrMaxConstTemp           uint32 = 0x000C
	AttrPumpStatus             uint32 = 0x0010
	AttrEffectiveOperationMode uint32 = 0x0011
	AttrEffectiveControlMode   uint32 = 0x0012
	AttrCapacity               uint32 = 0x0013
	AttrSpeed                  uint32 = 0x0014
	AttrLifetimeRunningHours   uint32 = 0x0015
	AttrPower                  uint32 = 0x0016
	AttrLifetimeEnergyConsumed uint32 = 0x0017
	AttrOperationMode          uint32 = 0x0020
	AttrControlMode            uint32 = 0x0021
	AttrAlarmMask              uint32 = 0x0022
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PRSCONST", Name: "ConstantPressure"},
			{Bit: 1, Code: "PRSCOMP", Name: "CompensatedPressure"},
			{Bit: 2, Code: "FLW", Name: "ConstantFlow"},
			{Bit: 3, Code: "SPD", Name: "ConstantSpeed"},
			{Bit: 4, Code: "TEMP", Name: "ConstantTemperature"},
			{Bit: 5, Code: "AUTO", Name: "Automatic"},
			{Bit: 6, Code: "LOCAL", Name: "LocalOperation"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxPressure, Name: "MaxPressure", DisplayName: "MaxPressure", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxSpeed, Name: "MaxSpeed", DisplayName: "MaxSpeed", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMaxFlow, Name: "MaxFlow", DisplayName: "MaxFlow", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMinConstPressure, Name: "MinConstPressure", DisplayName: "MinConstPressure", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxConstPressure, Name: "MaxConstPressure", DisplayName: "MaxConstPressure", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMinCompPressure, Name: "MinCompPressure", DisplayName: "MinCompPressure", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxCompPressure, Name: "MaxCompPressure", DisplayName: "MaxCompPressure", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMinConstSpeed, Name: "MinConstSpeed", DisplayName: "MinConstSpeed", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMaxConstSpeed, Name: "MaxConstSpeed", DisplayName: "MaxConstSpeed", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMinConstFlow, Name: "MinConstFlow", DisplayName: "MinConstFlow", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMaxConstFlow, Name: "MaxConstFlow", DisplayName: "MaxConstFlow", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrMinConstTemp, Name: "MinConstTemp", DisplayName: "MinConstTemp", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxConstTemp, Name: "MaxConstTemp", DisplayName: "MaxConstTemp", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrPumpStatus, Name: "PumpStatus", DisplayName: "PumpStatus", Type: "bitmap8", Readable: true},
			{ID: AttrEffectiveOperationMode, Name: "EffectiveOperationMode", DisplayName: "EffectiveOperationMode", Type: "enum8", Readable: true},
			{ID: AttrEffectiveControlMode, Name: "EffectiveControlMode", DisplayName: "EffectiveControlMode", Type: "enum8", Readable: true},
			{ID: AttrCapacity, Name: "Capacity", DisplayName: "Capacity", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrSpeed, Name: "Speed", DisplayName: "Speed", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrLifetimeRunningHours, Name: "LifetimeRunningHours", DisplayName: "LifetimeRunningHours", Type: "uint32", Readable: true, Writable: true, Nullable: true},
			{ID: AttrPower, Name: "Power", DisplayName: "Power", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrLifetimeEnergyConsumed, Name: "LifetimeEnergyConsumed", DisplayName: "LifetimeEnergyConsumed", Type: "uint32", Readable: true, Writable: true, Nullable: true},
			{ID: AttrOperationMode, Name: "OperationMode", DisplayName: "OperationMode", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrControlMode, Name: "ControlMode", DisplayName: "ControlMode", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrAlarmMask, Name: "AlarmMask", DisplayName: "AlarmMask", Type: "uint8", Readable: false},
		},
	})
}
