// Code generated by cmd/codegen; DO NOT EDIT.

// Package switchcluster implements the Matter Switch cluster (0x003B).
package switchcluster

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Switch.
	ID uint32 = 0x003B
	// Name is the CLI-friendly cluster name.
	Name = "Switch"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Switch"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureLatchingSwitch            uint32 = 1 << 0 // LS
	FeatureMomentarySwitch           uint32 = 1 << 1 // MS
	FeatureMomentarySwitchRelease    uint32 = 1 << 2 // MSR
	FeatureMomentarySwitchLongPress  uint32 = 1 << 3 // MSL
	FeatureMomentarySwitchMultiPress uint32 = 1 << 4 // MSM
	FeatureActionSwitch              uint32 = 1 << 5 // AS
)

// Attribute IDs.
const (
	AttrNumberOfPositions uint32 = 0x0000
	AttrCurrentPosition   uint32 = 0x0001
	AttrMultiPressMax     uint32 = 0x0002
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "LS", Name: "LatchingSwitch"},
			{Bit: 1, Code: "MS", Name: "MomentarySwitch"},
			{Bit: 2, Code: "MSR", Name: "MomentarySwitchRelease"},
			{Bit: 3, Code: "MSL", Name: "MomentarySwitchLongPress"},
			{Bit: 4, Code: "MSM", Name: "MomentarySwitchMultiPress"},
			{Bit: 5, Code: "AS", Name: "ActionSwitch"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrNumberOfPositions, Name: "NumberOfPositions", DisplayName: "NumberOfPositions", Type: "uint8", Readable: true},
			{ID: AttrCurrentPosition, Name: "CurrentPosition", DisplayName: "CurrentPosition", Type: "uint8", Readable: true},
			{ID: AttrMultiPressMax, Name: "MultiPressMax", DisplayName: "MultiPressMax", Type: "uint8", Readable: true},
		},
	})
}
