// Code generated by cmd/codegen; DO NOT EDIT.

// Package energyevse implements the Matter Energy EVSE cluster (0x0099).
package energyevse

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Energy EVSE.
	ID uint32 = 0x0099
	// Name is the CLI-friendly cluster name.
	Name = "EnergyEVSE"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Energy EVSE"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureChargingPreferences uint32 = 1 << 0 // PREF
	FeatureSoCReporting        uint32 = 1 << 1 // SOC
	FeaturePlugAndCharge       uint32 = 1 << 2 // PNC
	FeatureRFID                uint32 = 1 << 3 // RFID
	FeatureV2X                 uint32 = 1 << 4 // V2X
)

// Attribute IDs.
const (
	AttrState                    uint32 = 0x0000
	AttrSupplyState              uint32 = 0x0001
	AttrFaultState               uint32 = 0x0002
	AttrChargingEnabledUntil     uint32 = 0x0003
	AttrDischargingEnabledUntil  uint32 = 0x0004
	AttrCircuitCapacity          uint32 = 0x0005
	AttrMinimumChargeCurrent     uint32 = 0x0006
	AttrMaximumChargeCurrent     uint32 = 0x0007
	AttrMaximumDischargeCurrent  uint32 = 0x0008
	AttrUserMaximumChargeCurrent uint32 = 0x0009
	AttrRandomizationDelayWindow uint32 = 0x000A
	AttrNextChargeStartTime      uint32 = 0x0023
	AttrNextChargeTargetTime     uint32 = 0x0024
	AttrNextChargeRequiredEnergy uint32 = 0x0025
	AttrNextChargeTargetSoC      uint32 = 0x0026
	AttrApproximateEVEfficiency  uint32 = 0x0027
	AttrStateOfCharge            uint32 = 0x0030
	AttrBatteryCapacity          uint32 = 0x0031
	AttrVehicleID                uint32 = 0x0032
	AttrSessionID                uint32 = 0x0040
	AttrSessionDuration          uint32 = 0x0041
	AttrSessionEnergyCharged     uint32 = 0x0042
	AttrSessionEnergyDischarged  uint32 = 0x0043
)

// Command IDs.
const (
	CmdDisable           uint32 = 0x01
	CmdEnableCharging    uint32 = 0x02
	CmdEnableDischarging uint32 = 0x03
	CmdStartDiagnostics  uint32 = 0x04
	CmdSetTargets        uint32 = 0x05
	CmdGetTargets        uint32 = 0x06
	CmdClearTargets      uint32 = 0x07
)

// EnableChargingRequest is the request payload for the EnableCharging command.
type EnableChargingRequest struct {
	ChargingEnabledUntil uint32 `tlv:"0,uint"`
	MinimumChargeCurrent int64  `tlv:"1,int"`
	MaximumChargeCurrent int64  `tlv:"2,int"`
}

// EnableDischargingRequest is the request payload for the EnableDischarging command.
type EnableDischargingRequest struct {
	DischargingEnabledUntil uint32 `tlv:"0,uint"`
	MaximumDischargeCurrent int64  `tlv:"1,int"`
}

// SetTargetsRequest is the request payload for the SetTargets command.
type SetTargetsRequest struct {
	ChargingTargetSchedules uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PREF", Name: "ChargingPreferences"},
			{Bit: 1, Code: "SOC", Name: "SoCReporting"},
			{Bit: 2, Code: "PNC", Name: "PlugAndCharge"},
			{Bit: 3, Code: "RFID", Name: "RFID"},
			{Bit: 4, Code: "V2X", Name: "V2X"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrState, Name: "State", DisplayName: "State", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrSupplyState, Name: "SupplyState", DisplayName: "SupplyState", Type: "enum8", Readable: true},
			{ID: AttrFaultState, Name: "FaultState", DisplayName: "FaultState", Type: "enum8", Readable: true},
			{ID: AttrChargingEnabledUntil, Name: "ChargingEnabledUntil", DisplayName: "ChargingEnabledUntil", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrDischargingEnabledUntil, Name: "DischargingEnabledUntil", DisplayName: "DischargingEnabledUntil", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrCircuitCapacity, Name: "CircuitCapacity", DisplayName: "CircuitCapacity", Type: "int64", Readable: true},
			{ID: AttrMinimumChargeCurrent, Name: "MinimumChargeCurrent", DisplayName: "MinimumChargeCurrent", Type: "int64", Readable: true},
			{ID: AttrMaximumChargeCurrent, Name: "MaximumChargeCurrent", DisplayName: "MaximumChargeCurrent", Type: "int64", Readable: true},
			{ID: AttrMaximumDischargeCurrent, Name: "MaximumDischargeCurrent", DisplayName: "MaximumDischargeCurrent", Type: "int64", Readable: true},
			{ID: AttrUserMaximumChargeCurrent, Name: "UserMaximumChargeCurrent", DisplayName: "UserMaximumChargeCurrent", Type: "int64", Readable: true, Writable: true},
			{ID: AttrRandomizationDelayWindow, Name: "RandomizationDelayWindow", DisplayName: "RandomizationDelayWindow", Type: "uint32", Readable: true, Writable: true},
			{ID: AttrNextChargeStartTime, Name: "NextChargeStartTime", DisplayName: "NextChargeStartTime", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrNextChargeTargetTime, Name: "NextChargeTargetTime", DisplayName: "NextChargeTargetTime", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrNextChargeRequiredEnergy, Name: "NextChargeRequiredEnergy", DisplayName: "NextChargeRequiredEnergy", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrNextChargeTargetSoC, Name: "NextChargeTargetSoC", DisplayName: "NextChargeTargetSoC", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrApproximateEVEfficiency, Name: "ApproximateEVEfficiency", DisplayName: "ApproximateEVEfficiency", Type: "uint16", Readable: true, Writable: true, Nullable: true},
			{ID: AttrStateOfCharge, Name: "StateOfCharge", DisplayName: "StateOfCharge", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrBatteryCapacity, Name: "BatteryCapacity", DisplayName: "BatteryCapacity", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrVehicleID, Name: "VehicleID", DisplayName: "VehicleID", Type: "string", Readable: true, Nullable: true},
			{ID: AttrSessionID, Name: "SessionID", DisplayName: "SessionID", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrSessionDuration, Name: "SessionDuration", DisplayName: "SessionDuration", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrSessionEnergyCharged, Name: "SessionEnergyCharged", DisplayName: "SessionEnergyCharged", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrSessionEnergyDischarged, Name: "SessionEnergyDischarged", DisplayName: "SessionEnergyDischarged", Type: "int64", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdDisable, Name: "Disable", DisplayName: "Disable"},
			{ID: CmdEnableCharging, Name: "EnableCharging", DisplayName: "EnableCharging", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ChargingEnabledUntil", DisplayName: "ChargingEnabledUntil", Type: "uint32", Nullable: true},
				{ID: 1, Name: "MinimumChargeCurrent", DisplayName: "MinimumChargeCurrent", Type: "int64"},
				{ID: 2, Name: "MaximumChargeCurrent", DisplayName: "MaximumChargeCurrent", Type: "int64"},
			}},
			{ID: CmdEnableDischarging, Name: "EnableDischarging", DisplayName: "EnableDischarging", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DischargingEnabledUntil", DisplayName: "DischargingEnabledUntil", Type: "uint32", Nullable: true},
				{ID: 1, Name: "MaximumDischargeCurrent", DisplayName: "MaximumDischargeCurrent", Type: "int64"},
			}},
			{ID: CmdStartDiagnostics, Name: "StartDiagnostics", DisplayName: "StartDiagnostics"},
			{ID: CmdSetTargets, Name: "SetTargets", DisplayName: "SetTargets", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ChargingTargetSchedules", DisplayName: "ChargingTargetSchedules", Type: "list"},
			}},
			{ID: CmdGetTargets, Name: "GetTargets", DisplayName: "GetTargets", HasResponse: true},
			{ID: CmdClearTargets, Name: "ClearTargets", DisplayName: "ClearTargets"},
		},
	})
}
