// Code generated by cmd/codegen; DO NOT EDIT.

// Package threadnetworkdiagnostics implements the Matter Thread Network Diagnostics cluster (0x0035).
package threadnetworkdiagnostics

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Thread Network Diagnostics.
	ID uint32 = 0x0035
	// Name is the CLI-friendly cluster name.
	Name = "ThreadNetworkDiagnostics"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Thread Network Diagnostics"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePacketCounts uint32 = 1 << 0 // PKTCNT
	FeatureErrorCounts  uint32 = 1 << 1 // ERRCNT
	FeatureMLECounts    uint32 = 1 << 2 // MLECNT
	FeatureMACCounts    uint32 = 1 << 3 // MACCNT
)

// Attribute IDs.
const (
	AttrChannel                           uint32 = 0x0000
	AttrRoutingRole                       uint32 = 0x0001
	AttrNetworkName                       uint32 = 0x0002
	AttrPanId                             uint32 = 0x0003
	AttrExtendedPanId                     uint32 = 0x0004
	AttrMeshLocalPrefix                   uint32 = 0x0005
	AttrOverrunCount                      uint32 = 0x0006
	AttrNeighborTable                     uint32 = 0x0007
	AttrRouteTable                        uint32 = 0x0008
	AttrPartitionId                       uint32 = 0x0009
	AttrWeighting                         uint32 = 0x000A
	AttrDataVersion                       uint32 = 0x000B
	AttrStableDataVersion                 uint32 = 0x000C
	AttrLeaderRouterId                    uint32 = 0x000D
	AttrDetachedRoleCount                 uint32 = 0x000E
	AttrChildRoleCount                    uint32 = 0x000F
	AttrRouterRoleCount                   uint32 = 0x0010
	AttrLeaderRoleCount                   uint32 = 0x0011
	AttrAttachAttemptCount                uint32 = 0x0012
	AttrPartitionIdChangeCount            uint32 = 0x0013
	AttrBetterPartitionAttachAttemptCount uint32 = 0x0014
	AttrParentChangeCount                 uint32 = 0x0015
	AttrTxTotalCount                      uint32 = 0x0016
	AttrTxUnicastCount                    uint32 = 0x0017
	AttrTxBroadcastCount                  uint32 = 0x0018
	AttrTxAckRequestedCount               uint32 = 0x0019
	AttrTxAckedCount                      uint32 = 0x001A
	AttrTxNoAckRequestedCount             uint32 = 0x001B
	AttrTxDataCount                       uint32 = 0x001C
	AttrTxDataPollCount                   uint32 = 0x001D
	AttrTxBeaconCount                     uint32 = 0x001E
	AttrTxBeaconRequestCount              uint32 = 0x001F
	AttrTxOtherCount                      uint32 = 0x0020
	AttrTxRetryCount                      uint32 = 0x0021
	AttrTxDirectMaxRetryExpiryCount       uint32 = 0x0022
	AttrTxIndirectMaxRetryExpiryCount     uint32 = 0x0023
	AttrTxErrCcaCount                     uint32 = 0x0024
	AttrTxErrAbortCount                   uint32 = 0x0025
	AttrTxErrBusyChannelCount             uint32 = 0x0026
	AttrRxTotalCount                      uint32 = 0x0027
	AttrRxUnicastCount                    uint32 = 0x0028
	AttrRxBroadcastCount                  uint32 = 0x0029
	AttrRxDataCount                       uint32 = 0x002A
	AttrRxDataPollCount                   uint32 = 0x002B
	AttrRxBeaconCount                     uint32 = 0x002C
	AttrRxBeaconRequestCount              uint32 = 0x002D
	AttrRxOtherCount                      uint32 = 0x002E
	AttrRxAddressFilteredCount            uint32 = 0x002F
	AttrRxDestAddrFilteredCount           uint32 = 0x0030
	AttrRxDuplicatedCount                 uint32 = 0x0031
	AttrRxErrNoFrameCount                 uint32 = 0x0032
	AttrRxErrUnknownNeighborCount         uint32 = 0x0033
	AttrRxErrInvalidSrcAddrCount          uint32 = 0x0034
	AttrRxErrSecCount                     uint32 = 0x0035
	AttrRxErrFcsCount                     uint32 = 0x0036
	AttrRxErrOtherCount                   uint32 = 0x0037
	AttrActiveTimestamp                   uint32 = 0x0038
	AttrPendingTimestamp                  uint32 = 0x0039
	AttrDelay                             uint32 = 0x003A
	AttrSecurityPolicy                    uint32 = 0x003B
	AttrChannelPage0Mask                  uint32 = 0x003C
	AttrOperationalDatasetComponents      uint32 = 0x003D
	AttrActiveNetworkFaultsList           uint32 = 0x003E
	AttrExtAddress                        uint32 = 0x003F
	AttrRloc16                            uint32 = 0x0040
)

// Command IDs.
const (
	CmdResetCounts uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PKTCNT", Name: "PacketCounts"},
			{Bit: 1, Code: "ERRCNT", Name: "ErrorCounts"},
			{Bit: 2, Code: "MLECNT", Name: "MLECounts"},
			{Bit: 3, Code: "MACCNT", Name: "MACCounts"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrChannel, Name: "Channel", DisplayName: "Channel", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrRoutingRole, Name: "RoutingRole", DisplayName: "RoutingRole", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrNetworkName, Name: "NetworkName", DisplayName: "NetworkName", Type: "string", Readable: true, Nullable: true},
			{ID: AttrPanId, Name: "PanId", DisplayName: "PanId", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrExtendedPanId, Name: "ExtendedPanId", DisplayName: "ExtendedPanId", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrMeshLocalPrefix, Name: "MeshLocalPrefix", DisplayName: "MeshLocalPrefix", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrOverrunCount, Name: "OverrunCount", DisplayName: "OverrunCount", Type: "uint64", Readable: true},
			{ID: AttrNeighborTable, Name: "NeighborTable", DisplayName: "NeighborTable", Type: "list", Readable: true},
			{ID: AttrRouteTable, Name: "RouteTable", DisplayName: "RouteTable", Type: "list", Readable: true},
			{ID: AttrPartitionId, Name: "PartitionId", DisplayName: "PartitionId", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrWeighting, Name: "Weighting", DisplayName: "Weighting", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrDataVersion, Name: "DataVersion", DisplayName: "DataVersion", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrStableDataVersion, Name: "StableDataVersion", DisplayName: "StableDataVersion", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrLeaderRouterId, Name: "LeaderRouterId", DisplayName: "LeaderRouterId", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrDetachedRoleCount, Name: "DetachedRoleCount", DisplayName: "DetachedRoleCount", Type: "uint16", Readable: true},
			{ID: AttrChildRoleCount, Name: "ChildRoleCount", DisplayName: "ChildRoleCount", Type: "uint16", Readable: true},
			{ID: AttrRouterRoleCount, Name: "RouterRoleCount", DisplayName: "RouterRoleCount", Type: "uint16", Readable: true},
			{ID: AttrLeaderRoleCount, Name: "LeaderRoleCount", DisplayName: "LeaderRoleCount", Type: "uint16", Readable: true},
			{ID: AttrAttachAttemptCount, Name: "AttachAttemptCount", DisplayName: "AttachAttemptCount", Type: "uint16", Readable: true},
			{ID: AttrPartitionIdChangeCount, Name: "PartitionIdChangeCount", DisplayName: "PartitionIdChangeCount", Type: "uint16", Readable: true},
			{ID: AttrBetterPartitionAttachAttemptCount, Name: "BetterPartitionAttachAttemptCount", DisplayName: "BetterPartitionAttachAttemptCount", Type: "uint16", Readable: true},
			{ID: AttrParentChangeCount, Name: "ParentChangeCount", DisplayName: "ParentChangeCount", Type: "uint16", Readable: true},
			{ID: AttrTxTotalCount, Name: "TxTotalCount", DisplayName: "TxTotalCount", Type: "uint32", Readable: true},
			{ID: AttrTxUnicastCount, Name: "TxUnicastCount", DisplayName: "TxUnicastCount", Type: "uint32", Readable: true},
			{ID: AttrTxBroadcastCount, Name: "TxBroadcastCount", DisplayName: "TxBroadcastCount", Type: "uint32", Readable: true},
			{ID: AttrTxAckRequestedCount, Name: "TxAckRequestedCount", DisplayName: "TxAckRequestedCount", Type: "uint32", Readable: true},
			{ID: AttrTxAckedCount, Name: "TxAckedCount", DisplayName: "TxAckedCount", Type: "uint32", Readable: true},
			{ID: AttrTxNoAckRequestedCount, Name: "TxNoAckRequestedCount", DisplayName: "TxNoAckRequestedCount", Type: "uint32", Readable: true},
			{ID: AttrTxDataCount, Name: "TxDataCount", DisplayName: "TxDataCount", Type: "uint32", Readable: true},
			{ID: AttrTxDataPollCount, Name: "TxDataPollCount", DisplayName: "TxDataPollCount", Type: "uint32", Readable: true},
			{ID: AttrTxBeaconCount, Name: "TxBeaconCount", DisplayName: "TxBeaconCount", Type: "uint32", Readable: true},
			{ID: AttrTxBeaconRequestCount, Name: "TxBeaconRequestCount", DisplayName: "TxBeaconRequestCount", Type: "uint32", Readable: true},
			{ID: AttrTxOtherCount, Name: "TxOtherCount", DisplayName: "TxOtherCount", Type: "uint32", Readable: true},
			{ID: AttrTxRetryCount, Name: "TxRetryCount", DisplayName: "TxRetryCount", Type: "uint32", Readable: true},
			{ID: AttrTxDirectMaxRetryExpiryCount, Name: "TxDirectMaxRetryExpiryCount", DisplayName: "TxDirectMaxRetryExpiryCount", Type: "uint32", Readable: true},
			{ID: AttrTxIndirectMaxRetryExpiryCount, Name: "TxIndirectMaxRetryExpiryCount", DisplayName: "TxIndirectMaxRetryExpiryCount", Type: "uint32", Readable: true},
			{ID: AttrTxErrCcaCount, Name: "TxErrCcaCount", DisplayName: "TxErrCcaCount", Type: "uint32", Readable: true},
			{ID: AttrTxErrAbortCount, Name: "TxErrAbortCount", DisplayName: "TxErrAbortCount", Type: "uint32", Readable: true},
			{ID: AttrTxErrBusyChannelCount, Name: "TxErrBusyChannelCount", DisplayName: "TxErrBusyChannelCount", Type: "uint32", Readable: true},
			{ID: AttrRxTotalCount, Name: "RxTotalCount", DisplayName: "RxTotalCount", Type: "uint32", Readable: true},
			{ID: AttrRxUnicastCount, Name: "RxUnicastCount", DisplayName: "RxUnicastCount", Type: "uint32", Readable: true},
			{ID: AttrRxBroadcastCount, Name: "RxBroadcastCount", DisplayName: "RxBroadcastCount", Type: "uint32", Readable: true},
			{ID: AttrRxDataCount, Name: "RxDataCount", DisplayName: "RxDataCount", Type: "uint32", Readable: true},
			{ID: AttrRxDataPollCount, Name: "RxDataPollCount", DisplayName: "RxDataPollCount", Type: "uint32", Readable: true},
			{ID: AttrRxBeaconCount, Name: "RxBeaconCount", DisplayName: "RxBeaconCount", Type: "uint32", Readable: true},
			{ID: AttrRxBeaconRequestCount, Name: "RxBeaconRequestCount", DisplayName: "RxBeaconRequestCount", Type: "uint32", Readable: true},
			{ID: AttrRxOtherCount, Name: "RxOtherCount", DisplayName: "RxOtherCount", Type: "uint32", Readable: true},
			{ID: AttrRxAddressFilteredCount, Name: "RxAddressFilteredCount", DisplayName: "RxAddressFilteredCount", Type: "uint32", Readable: true},
			{ID: AttrRxDestAddrFilteredCount, Name: "RxDestAddrFilteredCount", DisplayName: "RxDestAddrFilteredCount", Type: "uint32", Readable: true},
			{ID: AttrRxDuplicatedCount, Name: "RxDuplicatedCount", DisplayName: "RxDuplicatedCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrNoFrameCount, Name: "RxErrNoFrameCount", DisplayName: "RxErrNoFrameCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrUnknownNeighborCount, Name: "RxErrUnknownNeighborCount", DisplayName: "RxErrUnknownNeighborCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrInvalidSrcAddrCount, Name: "RxErrInvalidSrcAddrCount", DisplayName: "RxErrInvalidSrcAddrCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrSecCount, Name: "RxErrSecCount", DisplayName: "RxErrSecCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrFcsCount, Name: "RxErrFcsCount", DisplayName: "RxErrFcsCount", Type: "uint32", Readable: true},
			{ID: AttrRxErrOtherCount, Name: "RxErrOtherCount", DisplayName: "RxErrOtherCount", Type: "uint32", Readable: true},
			{ID: AttrActiveTimestamp, Name: "ActiveTimestamp", DisplayName: "ActiveTimestamp", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrPendingTimestamp, Name: "PendingTimestamp", DisplayName: "PendingTimestamp", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrDelay, Name: "Delay", DisplayName: "Delay", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrSecurityPolicy, Name: "SecurityPolicy", DisplayName: "SecurityPolicy", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrChannelPage0Mask, Name: "ChannelPage0Mask", DisplayName: "ChannelPage0Mask", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrOperationalDatasetComponents, Name: "OperationalDatasetComponents", DisplayName: "OperationalDatasetComponents", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrActiveNetworkFaultsList, Name: "ActiveNetworkFaultsList", DisplayName: "ActiveNetworkFaultsList", Type: "list", Readable: true},
			{ID: AttrExtAddress, Name: "ExtAddress", DisplayName: "ExtAddress", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrRloc16, Name: "Rloc16", DisplayName: "Rloc16", Type: "uint16", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdResetCounts, Name: "ResetCounts", DisplayName: "ResetCounts"},
		},
	})
}
