// Code generated by cmd/codegen; DO NOT EDIT.

// Package valveconfigurationandcontrol implements the Matter Valve Configuration and Control cluster (0x0081).
package valveconfigurationandcontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Valve Configuration and Control.
	ID uint32 = 0x0081
	// Name is the CLI-friendly cluster name.
	Name = "ValveConfigurationAndControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Valve Configuration and Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTimeSync uint32 = 1 << 0 // TS
	FeatureLevel    uint32 = 1 << 1 // LVL
)

// Attribute IDs.
const (
	AttrOpenDuration        uint32 = 0x0000
	AttrDefaultOpenDuration uint32 = 0x0001
	AttrAutoCloseTime       uint32 = 0x0002
	AttrRemainingDuration   uint32 = 0x0003
	AttrCurrentState        uint32 = 0x0004
	AttrTargetState         uint32 = 0x0005
	AttrCurrentLevel        uint32 = 0x0006
	AttrTargetLevel         uint32 = 0x0007
	AttrDefaultOpenLevel    uint32 = 0x0008
	AttrValveFault          uint32 = 0x0009
	AttrLevelStep           uint32 = 0x000A
)

// Command IDs.
const (
	CmdOpen  uint32 = 0x00
	CmdClose uint32 = 0x01
)

// OpenRequest is the request payload for the Open command.
type OpenRequest struct {
	OpenDuration uint32 `tlv:"0,uint"`
	TargetLevel  uint8  `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TS", Name: "TimeSync"},
			{Bit: 1, Code: "LVL", Name: "Level"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrOpenDuration, Name: "OpenDuration", DisplayName: "OpenDuration", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrDefaultOpenDuration, Name: "DefaultOpenDuration", DisplayName: "DefaultOpenDuration", Type: "uint32", Readable: true, Writable: true, Nullable: true},
			{ID: AttrAutoCloseTime, Name: "AutoCloseTime", DisplayName: "AutoCloseTime", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrRemainingDuration, Name: "RemainingDuration", DisplayName: "RemainingDuration", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrCurrentState, Name: "CurrentState", DisplayName: "CurrentState", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrTargetState, Name: "TargetState", DisplayName: "TargetState", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrCurrentLevel, Name: "CurrentLevel", DisplayName: "CurrentLevel", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrTargetLevel, Name: "TargetLevel", DisplayName: "TargetLevel", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrDefaultOpenLevel, Name: "DefaultOpenLevel", DisplayName: "DefaultOpenLevel", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrValveFault, Name: "ValveFault", DisplayName: "ValveFault", Type: "bitmap8", Readable: true},
			{ID: AttrLevelStep, Name: "LevelStep", DisplayName: "LevelStep", Type: "uint8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdOpen, Name: "Open", DisplayName: "Open", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OpenDuration", DisplayName: "OpenDuration", Type: "uint32", Optional: true, Nullable: true},
				{ID: 1, Name: "TargetLevel", DisplayName: "TargetLevel", Type: "uint8", Optional: true},
			}},
			{ID: CmdClose, Name: "Close", DisplayName: "Close"},
		},
	})
}
