// Code generated by cmd/codegen; DO NOT EDIT.

// Package wakeonlan implements the Matter Wake On LAN cluster (0x0503).
package wakeonlan

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Wake On LAN.
	ID uint32 = 0x0503
	// Name is the CLI-friendly cluster name.
	Name = "WakeOnLAN"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Wake On LAN"
)

// Attribute IDs.
const (
	AttrMACAddress       uint32 = 0x0000
	AttrLinkLocalAddress uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMACAddress, Name: "MACAddress", DisplayName: "MACAddress", Type: "string", Readable: true},
			{ID: AttrLinkLocalAddress, Name: "LinkLocalAddress", DisplayName: "LinkLocalAddress", Type: "octets", Readable: true},
		},
	})
}
