// Code generated by cmd/codegen; DO NOT EDIT.

// Package generalcommissioning implements the Matter General Commissioning cluster (0x0030).
package generalcommissioning

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for General Commissioning.
	ID uint32 = 0x0030
	// Name is the CLI-friendly cluster name.
	Name = "GeneralCommissioning"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "General Commissioning"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTermsAndConditions uint32 = 1 << 0 // TC
	FeatureNetworkRecovery    uint32 = 1 << 1 // NR
)

// Attribute IDs.
const (
	AttrBreadcrumb                   uint32 = 0x0000
	AttrBasicCommissioningInfo       uint32 = 0x0001
	AttrRegulatoryConfig             uint32 = 0x0002
	AttrLocationCapability           uint32 = 0x0003
	AttrSupportsConcurrentConnection uint32 = 0x0004
	AttrTCAcceptedVersion            uint32 = 0x0005
	AttrTCMinRequiredVersion         uint32 = 0x0006
	AttrTCAcknowledgements           uint32 = 0x0007
	AttrTCAcknowledgementsRequired   uint32 = 0x0008
	AttrTCUpdateDeadline             uint32 = 0x0009
	AttrRecoveryIdentifier           uint32 = 0x000A
	AttrNetworkRecoveryReason        uint32 = 0x000B
	AttrIsCommissioningWithoutPower  uint32 = 0x000C
)

// Command IDs.
const (
	CmdArmFailSafe           uint32 = 0x00
	CmdSetRegulatoryConfig   uint32 = 0x02
	CmdCommissioningComplete uint32 = 0x04
	CmdSetTCAcknowledgements uint32 = 0x06
)

// ArmFailSafeRequest is the request payload for the ArmFailSafe command.
type ArmFailSafeRequest struct {
	ExpiryLengthSeconds uint16 `tlv:"0,uint"`
	Breadcrumb          uint64 `tlv:"1,uint"`
}

// SetRegulatoryConfigRequest is the request payload for the SetRegulatoryConfig command.
type SetRegulatoryConfigRequest struct {
	NewRegulatoryConfig uint8  `tlv:"0,uint"`
	CountryCode         string `tlv:"1,utf8"`
	Breadcrumb          uint64 `tlv:"2,uint"`
}

// SetTCAcknowledgementsRequest is the request payload for the SetTCAcknowledgements command.
type SetTCAcknowledgementsRequest struct {
	TCVersion      uint16 `tlv:"0,uint"`
	TCUserResponse uint16 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TC", Name: "TermsAndConditions"},
			{Bit: 1, Code: "NR", Name: "NetworkRecovery"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrBreadcrumb, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Readable: true, Writable: true},
			{ID: AttrBasicCommissioningInfo, Name: "BasicCommissioningInfo", DisplayName: "BasicCommissioningInfo", Type: "uint8", Readable: true},
			{ID: AttrRegulatoryConfig, Name: "RegulatoryConfig", DisplayName: "RegulatoryConfig", Type: "enum8", Readable: true},
			{ID: AttrLocationCapability, Name: "LocationCapability", DisplayName: "LocationCapability", Type: "enum8", Readable: true},
			{ID: AttrSupportsConcurrentConnection, Name: "SupportsConcurrentConnection", DisplayName: "SupportsConcurrentConnection", Type: "bool", Readable: true},
			{ID: AttrTCAcceptedVersion, Name: "TCAcceptedVersion", DisplayName: "TCAcceptedVersion", Type: "uint16", Readable: true},
			{ID: AttrTCMinRequiredVersion, Name: "TCMinRequiredVersion", DisplayName: "TCMinRequiredVersion", Type: "uint16", Readable: true},
			{ID: AttrTCAcknowledgements, Name: "TCAcknowledgements", DisplayName: "TCAcknowledgements", Type: "bitmap16", Readable: true},
			{ID: AttrTCAcknowledgementsRequired, Name: "TCAcknowledgementsRequired", DisplayName: "TCAcknowledgementsRequired", Type: "bool", Readable: true},
			{ID: AttrTCUpdateDeadline, Name: "TCUpdateDeadline", DisplayName: "TCUpdateDeadline", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrRecoveryIdentifier, Name: "RecoveryIdentifier", DisplayName: "RecoveryIdentifier", Type: "octets", Readable: true},
			{ID: AttrNetworkRecoveryReason, Name: "NetworkRecoveryReason", DisplayName: "NetworkRecoveryReason", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrIsCommissioningWithoutPower, Name: "IsCommissioningWithoutPower", DisplayName: "IsCommissioningWithoutPower", Type: "bool", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdArmFailSafe, Name: "ArmFailSafe", DisplayName: "ArmFailSafe", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ExpiryLengthSeconds", DisplayName: "ExpiryLengthSeconds", Type: "uint16"},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64"},
			}},
			{ID: CmdSetRegulatoryConfig, Name: "SetRegulatoryConfig", DisplayName: "SetRegulatoryConfig", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NewRegulatoryConfig", DisplayName: "NewRegulatoryConfig", Type: "enum8"},
				{ID: 1, Name: "CountryCode", DisplayName: "CountryCode", Type: "string"},
				{ID: 2, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64"},
			}},
			{ID: CmdCommissioningComplete, Name: "CommissioningComplete", DisplayName: "CommissioningComplete", HasResponse: true},
			{ID: CmdSetTCAcknowledgements, Name: "SetTCAcknowledgements", DisplayName: "SetTCAcknowledgements", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TCVersion", DisplayName: "TCVersion", Type: "uint16"},
				{ID: 1, Name: "TCUserResponse", DisplayName: "TCUserResponse", Type: "bitmap16"},
			}},
		},
	})
}
