// Code generated by cmd/codegen; DO NOT EDIT.

// Package waterheatermanagement implements the Matter Water Heater Management cluster (0x0094).
package waterheatermanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Water Heater Management.
	ID uint32 = 0x0094
	// Name is the CLI-friendly cluster name.
	Name = "WaterHeaterManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Water Heater Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureEnergyManagement uint32 = 1 << 0 // EM
	FeatureTankPercent      uint32 = 1 << 1 // TP
)

// Attribute IDs.
const (
	AttrHeaterTypes           uint32 = 0x0000
	AttrHeatDemand            uint32 = 0x0001
	AttrTankVolume            uint32 = 0x0002
	AttrEstimatedHeatRequired uint32 = 0x0003
	AttrTankPercentage        uint32 = 0x0004
	AttrBoostState            uint32 = 0x0005
)

// Command IDs.
const (
	CmdBoost       uint32 = 0x00
	CmdCancelBoost uint32 = 0x01
)

// BoostRequest is the request payload for the Boost command.
type BoostRequest struct {
	BoostInfo uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "EM", Name: "EnergyManagement"},
			{Bit: 1, Code: "TP", Name: "TankPercent"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrHeaterTypes, Name: "HeaterTypes", DisplayName: "HeaterTypes", Type: "bitmap8", Readable: true},
			{ID: AttrHeatDemand, Name: "HeatDemand", DisplayName: "HeatDemand", Type: "bitmap8", Readable: true},
			{ID: AttrTankVolume, Name: "TankVolume", DisplayName: "TankVolume", Type: "uint16", Readable: true},
			{ID: AttrEstimatedHeatRequired, Name: "EstimatedHeatRequired", DisplayName: "EstimatedHeatRequired", Type: "int64", Readable: true},
			{ID: AttrTankPercentage, Name: "TankPercentage", DisplayName: "TankPercentage", Type: "uint8", Readable: true},
			{ID: AttrBoostState, Name: "BoostState", DisplayName: "BoostState", Type: "enum8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdBoost, Name: "Boost", DisplayName: "Boost", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "BoostInfo", DisplayName: "BoostInfo", Type: "struct"},
			}},
			{ID: CmdCancelBoost, Name: "CancelBoost", DisplayName: "CancelBoost"},
		},
	})
}
