// Code generated by cmd/codegen; DO NOT EDIT.

// Package messages implements the Matter Messages cluster (0x0097).
package messages

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Messages.
	ID uint32 = 0x0097
	// Name is the CLI-friendly cluster name.
	Name = "Messages"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Messages"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureReceivedConfirmation uint32 = 1 << 0 // CONF
	FeatureConfirmationResponse uint32 = 1 << 1 // RESP
	FeatureConfirmationReply    uint32 = 1 << 2 // RPLY
	FeatureProtectedMessages    uint32 = 1 << 3 // PROT
)

// Attribute IDs.
const (
	AttrMessages         uint32 = 0x0000
	AttrActiveMessageIDs uint32 = 0x0001
)

// Command IDs.
const (
	CmdPresentMessagesRequest uint32 = 0x00
	CmdCancelMessagesRequest  uint32 = 0x01
)

// PresentMessagesRequestRequest is the request payload for the PresentMessagesRequest command.
type PresentMessagesRequestRequest struct {
	MessageID      []byte `tlv:"0,bytes"`
	Priority       uint8  `tlv:"1,uint"`
	MessageControl uint8  `tlv:"2,uint"`
	StartTime      uint32 `tlv:"3,uint"`
	Duration       uint64 `tlv:"4,uint"`
	MessageText    string `tlv:"5,utf8"`
	Responses      uint8  `tlv:"6,uint"`
}

// CancelMessagesRequestRequest is the request payload for the CancelMessagesRequest command.
type CancelMessagesRequestRequest struct {
	MessageIDs uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CONF", Name: "ReceivedConfirmation"},
			{Bit: 1, Code: "RESP", Name: "ConfirmationResponse"},
			{Bit: 2, Code: "RPLY", Name: "ConfirmationReply"},
			{Bit: 3, Code: "PROT", Name: "ProtectedMessages"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMessages, Name: "Messages", DisplayName: "Messages", Type: "list", Readable: true},
			{ID: AttrActiveMessageIDs, Name: "ActiveMessageIDs", DisplayName: "ActiveMessageIDs", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdPresentMessagesRequest, Name: "PresentMessagesRequest", DisplayName: "PresentMessagesRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MessageID", DisplayName: "MessageID", Type: "octets"},
				{ID: 1, Name: "Priority", DisplayName: "Priority", Type: "enum8"},
				{ID: 2, Name: "MessageControl", DisplayName: "MessageControl", Type: "bitmap8"},
				{ID: 3, Name: "StartTime", DisplayName: "StartTime", Type: "uint32", Nullable: true},
				{ID: 4, Name: "Duration", DisplayName: "Duration", Type: "uint64", Nullable: true},
				{ID: 5, Name: "MessageText", DisplayName: "MessageText", Type: "string"},
				{ID: 6, Name: "Responses", DisplayName: "Responses", Type: "list"},
			}},
			{ID: CmdCancelMessagesRequest, Name: "CancelMessagesRequest", DisplayName: "CancelMessagesRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MessageIDs", DisplayName: "MessageIDs", Type: "list"},
			}},
		},
	})
}
