// Code generated by cmd/codegen; DO NOT EDIT.

// Package deviceenergymanagement implements the Matter Device Energy Management cluster (0x0098).
package deviceenergymanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Device Energy Management.
	ID uint32 = 0x0098
	// Name is the CLI-friendly cluster name.
	Name = "DeviceEnergyManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Device Energy Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePowerAdjustment           uint32 = 1 << 0 // PA
	FeaturePowerForecastReporting    uint32 = 1 << 1 // PFR
	FeatureStateForecastReporting    uint32 = 1 << 2 // SFR
	FeatureStartTimeAdjustment       uint32 = 1 << 3 // STA
	FeaturePausable                  uint32 = 1 << 4 // PAU
	FeatureForecastAdjustment        uint32 = 1 << 5 // FA
	FeatureConstraintBasedAdjustment uint32 = 1 << 6 // CON
)

// Attribute IDs.
const (
	AttrESAType                   uint32 = 0x0000
	AttrESACanGenerate            uint32 = 0x0001
	AttrESAState                  uint32 = 0x0002
	AttrAbsMinPower               uint32 = 0x0003
	AttrAbsMaxPower               uint32 = 0x0004
	AttrPowerAdjustmentCapability uint32 = 0x0005
	AttrForecast                  uint32 = 0x0006
	AttrOptOutState               uint32 = 0x0007
)

// Command IDs.
const (
	CmdPowerAdjustRequest             uint32 = 0x00
	CmdCancelPowerAdjustRequest       uint32 = 0x01
	CmdStartTimeAdjustRequest         uint32 = 0x02
	CmdPauseRequest                   uint32 = 0x03
	CmdResumeRequest                  uint32 = 0x04
	CmdModifyForecastRequest          uint32 = 0x05
	CmdRequestConstraintBasedForecast uint32 = 0x06
	CmdCancelRequest                  uint32 = 0x07
)

// PowerAdjustRequestRequest is the request payload for the PowerAdjustRequest command.
type PowerAdjustRequestRequest struct {
	Power    int64  `tlv:"0,int"`
	Duration uint32 `tlv:"1,uint"`
	Cause    uint8  `tlv:"2,uint"`
}

// StartTimeAdjustRequestRequest is the request payload for the StartTimeAdjustRequest command.
type StartTimeAdjustRequestRequest struct {
	RequestedStartTime uint32 `tlv:"0,uint"`
	Cause              uint8  `tlv:"1,uint"`
}

// PauseRequestRequest is the request payload for the PauseRequest command.
type PauseRequestRequest struct {
	Duration uint32 `tlv:"0,uint"`
	Cause    uint8  `tlv:"1,uint"`
}

// ModifyForecastRequestRequest is the request payload for the ModifyForecastRequest command.
type ModifyForecastRequestRequest struct {
	ForecastID      uint32 `tlv:"0,uint"`
	SlotAdjustments uint8  `tlv:"1,uint"`
	Cause           uint8  `tlv:"2,uint"`
}

// RequestConstraintBasedForecastRequest is the request payload for the RequestConstraintBasedForecast command.
type RequestConstraintBasedForecastRequest struct {
	Constraints uint8 `tlv:"0,uint"`
	Cause       uint8 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PA", Name: "PowerAdjustment"},
			{Bit: 1, Code: "PFR", Name: "PowerForecastReporting"},
			{Bit: 2, Code: "SFR", Name: "StateForecastReporting"},
			{Bit: 3, Code: "STA", Name: "StartTimeAdjustment"},
			{Bit: 4, Code: "PAU", Name: "Pausable"},
			{Bit: 5, Code: "FA", Name: "ForecastAdjustment"},
			{Bit: 6, Code: "CON", Name: "ConstraintBasedAdjustment"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrESAType, Name: "ESAType", DisplayName: "ESAType", Type: "enum8", Readable: true},
			{ID: AttrESACanGenerate, Name: "ESACanGenerate", DisplayName: "ESACanGenerate", Type: "bool", Readable: true},
			{ID: AttrESAState, Name: "ESAState", DisplayName: "ESAState", Type: "enum8", Readable: true},
			{ID: AttrAbsMinPower, Name: "AbsMinPower", DisplayName: "AbsMinPower", Type: "int64", Readable: true},
			{ID: AttrAbsMaxPower, Name: "AbsMaxPower", DisplayName: "AbsMaxPower", Type: "int64", Readable: true},
			{ID: AttrPowerAdjustmentCapability, Name: "PowerAdjustmentCapability", DisplayName: "PowerAdjustmentCapability", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrForecast, Name: "Forecast", DisplayName: "Forecast", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrOptOutState, Name: "OptOutState", DisplayName: "OptOutState", Type: "enum8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdPowerAdjustRequest, Name: "PowerAdjustRequest", DisplayName: "PowerAdjustRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Power", DisplayName: "Power", Type: "int64"},
				{ID: 1, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
				{ID: 2, Name: "Cause", DisplayName: "Cause", Type: "enum8"},
			}},
			{ID: CmdCancelPowerAdjustRequest, Name: "CancelPowerAdjustRequest", DisplayName: "CancelPowerAdjustRequest"},
			{ID: CmdStartTimeAdjustRequest, Name: "StartTimeAdjustRequest", DisplayName: "StartTimeAdjustRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "RequestedStartTime", DisplayName: "RequestedStartTime", Type: "uint32"},
				{ID: 1, Name: "Cause", DisplayName: "Cause", Type: "enum8"},
			}},
			{ID: CmdPauseRequest, Name: "PauseRequest", DisplayName: "PauseRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
				{ID: 1, Name: "Cause", DisplayName: "Cause", Type: "enum8"},
			}},
			{ID: CmdResumeRequest, Name: "ResumeRequest", DisplayName: "ResumeRequest"},
			{ID: CmdModifyForecastRequest, Name: "ModifyForecastRequest", DisplayName: "ModifyForecastRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ForecastID", DisplayName: "ForecastID", Type: "uint32"},
				{ID: 1, Name: "SlotAdjustments", DisplayName: "SlotAdjustments", Type: "list"},
				{ID: 2, Name: "Cause", DisplayName: "Cause", Type: "enum8"},
			}},
			{ID: CmdRequestConstraintBasedForecast, Name: "RequestConstraintBasedForecast", DisplayName: "RequestConstraintBasedForecast", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Constraints", DisplayName: "Constraints", Type: "list"},
				{ID: 1, Name: "Cause", DisplayName: "Cause", Type: "enum8"},
			}},
			{ID: CmdCancelRequest, Name: "CancelRequest", DisplayName: "CancelRequest"},
		},
	})
}
