// Code generated by cmd/codegen; DO NOT EDIT.

// Package groups implements the Matter Groups cluster (0x0004).
package groups

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Groups.
	ID uint32 = 0x0004
	// Name is the CLI-friendly cluster name.
	Name = "Groups"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Groups"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureGroupNames uint32 = 1 << 0 // GN
)

// Attribute IDs.
const (
	AttrNameSupport uint32 = 0x0000
)

// Command IDs.
const (
	CmdAddGroup              uint32 = 0x00
	CmdViewGroup             uint32 = 0x01
	CmdGetGroupMembership    uint32 = 0x02
	CmdRemoveGroup           uint32 = 0x03
	CmdRemoveAllGroups       uint32 = 0x04
	CmdAddGroupIfIdentifying uint32 = 0x05
)

// AddGroupRequest is the request payload for the AddGroup command.
type AddGroupRequest struct {
	GroupID   uint16 `tlv:"0,uint"`
	GroupName string `tlv:"1,utf8"`
}

// ViewGroupRequest is the request payload for the ViewGroup command.
type ViewGroupRequest struct {
	GroupID uint16 `tlv:"0,uint"`
}

// GetGroupMembershipRequest is the request payload for the GetGroupMembership command.
type GetGroupMembershipRequest struct {
	GroupList uint8 `tlv:"0,uint"`
}

// RemoveGroupRequest is the request payload for the RemoveGroup command.
type RemoveGroupRequest struct {
	GroupID uint16 `tlv:"0,uint"`
}

// AddGroupIfIdentifyingRequest is the request payload for the AddGroupIfIdentifying command.
type AddGroupIfIdentifyingRequest struct {
	GroupID   uint16 `tlv:"0,uint"`
	GroupName string `tlv:"1,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "GN", Name: "GroupNames"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrNameSupport, Name: "NameSupport", DisplayName: "NameSupport", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAddGroup, Name: "AddGroup", DisplayName: "AddGroup", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "GroupName", DisplayName: "GroupName", Type: "string"},
			}},
			{ID: CmdViewGroup, Name: "ViewGroup", DisplayName: "ViewGroup", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdGetGroupMembership, Name: "GetGroupMembership", DisplayName: "GetGroupMembership", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupList", DisplayName: "GroupList", Type: "list"},
			}},
			{ID: CmdRemoveGroup, Name: "RemoveGroup", DisplayName: "RemoveGroup", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdRemoveAllGroups, Name: "RemoveAllGroups", DisplayName: "RemoveAllGroups"},
			{ID: CmdAddGroupIfIdentifying, Name: "AddGroupIfIdentifying", DisplayName: "AddGroupIfIdentifying", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "GroupName", DisplayName: "GroupName", Type: "string"},
			}},
		},
	})
}
