// Code generated by cmd/codegen; DO NOT EDIT.

// Package pressuremeasurement implements the Matter Pressure Measurement cluster (0x0403).
package pressuremeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Pressure Measurement.
	ID uint32 = 0x0403
	// Name is the CLI-friendly cluster name.
	Name = "PressureMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Pressure Measurement"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureExtended uint32 = 1 << 0 // EXT
)

// Attribute IDs.
const (
	AttrMeasuredValue    uint32 = 0x0000
	AttrMinMeasuredValue uint32 = 0x0001
	AttrMaxMeasuredValue uint32 = 0x0002
	AttrTolerance        uint32 = 0x0003
	AttrScaledValue      uint32 = 0x0010
	AttrMinScaledValue   uint32 = 0x0011
	AttrMaxScaledValue   uint32 = 0x0012
	AttrScaledTolerance  uint32 = 0x0013
	AttrScale            uint32 = 0x0014
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "EXT", Name: "Extended"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMeasuredValue, Name: "MeasuredValue", DisplayName: "MeasuredValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMinMeasuredValue, Name: "MinMeasuredValue", DisplayName: "MinMeasuredValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxMeasuredValue, Name: "MaxMeasuredValue", DisplayName: "MaxMeasuredValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrTolerance, Name: "Tolerance", DisplayName: "Tolerance", Type: "uint16", Readable: true},
			{ID: AttrScaledValue, Name: "ScaledValue", DisplayName: "ScaledValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMinScaledValue, Name: "MinScaledValue", DisplayName: "MinScaledValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrMaxScaledValue, Name: "MaxScaledValue", DisplayName: "MaxScaledValue", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrScaledTolerance, Name: "ScaledTolerance", DisplayName: "ScaledTolerance", Type: "uint16", Readable: true},
			{ID: AttrScale, Name: "Scale", DisplayName: "Scale", Type: "int8", Readable: true},
		},
	})
}
