// Code generated by cmd/codegen; DO NOT EDIT.

// Package servicearea implements the Matter Service Area cluster (0x0150).
package servicearea

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Service Area.
	ID uint32 = 0x0150
	// Name is the CLI-friendly cluster name.
	Name = "ServiceArea"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Service Area"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureSelectWhileRunning uint32 = 1 << 0 // SELRUN
	FeatureProgressReporting  uint32 = 1 << 1 // PROG
	FeatureMaps               uint32 = 1 << 2 // MAPS
)

// Attribute IDs.
const (
	AttrSupportedAreas   uint32 = 0x0000
	AttrSupportedMaps    uint32 = 0x0001
	AttrSelectedAreas    uint32 = 0x0002
	AttrCurrentArea      uint32 = 0x0003
	AttrEstimatedEndTime uint32 = 0x0004
	AttrProgress         uint32 = 0x0005
)

// Command IDs.
const (
	CmdSelectAreas uint32 = 0x00
	CmdSkipArea    uint32 = 0x02
)

// SelectAreasRequest is the request payload for the SelectAreas command.
type SelectAreasRequest struct {
	NewAreas uint8 `tlv:"0,uint"`
}

// SkipAreaRequest is the request payload for the SkipArea command.
type SkipAreaRequest struct {
	SkippedArea uint32 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "SELRUN", Name: "SelectWhileRunning"},
			{Bit: 1, Code: "PROG", Name: "ProgressReporting"},
			{Bit: 2, Code: "MAPS", Name: "Maps"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedAreas, Name: "SupportedAreas", DisplayName: "SupportedAreas", Type: "list", Readable: true},
			{ID: AttrSupportedMaps, Name: "SupportedMaps", DisplayName: "SupportedMaps", Type: "list", Readable: true},
			{ID: AttrSelectedAreas, Name: "SelectedAreas", DisplayName: "SelectedAreas", Type: "list", Readable: true},
			{ID: AttrCurrentArea, Name: "CurrentArea", DisplayName: "CurrentArea", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrEstimatedEndTime, Name: "EstimatedEndTime", DisplayName: "EstimatedEndTime", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrProgress, Name: "Progress", DisplayName: "Progress", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSelectAreas, Name: "SelectAreas", DisplayName: "SelectAreas", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NewAreas", DisplayName: "NewAreas", Type: "list"},
			}},
			{ID: CmdSkipArea, Name: "SkipArea", DisplayName: "SkipArea", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SkippedArea", DisplayName: "SkippedArea", Type: "uint32"},
			}},
		},
	})
}
