// Code generated by cmd/codegen; DO NOT EDIT.

// Package watertanklevelmonitoring implements the Matter Water Tank Level Monitoring cluster (0x0079).
package watertanklevelmonitoring

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Water Tank Level Monitoring.
	ID uint32 = 0x0079
	// Name is the CLI-friendly cluster name.
	Name = "WaterTankLevelMonitoring"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Water Tank Level Monitoring"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureCondition              uint32 = 1 << 0 // CON
	FeatureWarning                uint32 = 1 << 1 // WRN
	FeatureReplacementProductList uint32 = 1 << 2 // REP
)

// Attribute IDs.
const (
	AttrCondition              uint32 = 0x0000
	AttrDegradationDirection   uint32 = 0x0001
	AttrChangeIndication       uint32 = 0x0002
	AttrInPlaceIndicator       uint32 = 0x0003
	AttrLastChangedTime        uint32 = 0x0004
	AttrReplacementProductList uint32 = 0x0005
)

// Command IDs.
const (
	CmdResetCondition uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CON", Name: "Condition"},
			{Bit: 1, Code: "WRN", Name: "Warning"},
			{Bit: 2, Code: "REP", Name: "ReplacementProductList"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCondition, Name: "Condition", DisplayName: "Condition", Type: "uint8", Readable: true},
			{ID: AttrDegradationDirection, Name: "DegradationDirection", DisplayName: "DegradationDirection", Type: "enum8", Readable: true},
			{ID: AttrChangeIndication, Name: "ChangeIndication", DisplayName: "ChangeIndication", Type: "enum8", Readable: true},
			{ID: AttrInPlaceIndicator, Name: "InPlaceIndicator", DisplayName: "InPlaceIndicator", Type: "bool", Readable: true},
			{ID: AttrLastChangedTime, Name: "LastChangedTime", DisplayName: "LastChangedTime", Type: "uint32", Readable: true, Writable: true, Nullable: true},
			{ID: AttrReplacementProductList, Name: "ReplacementProductList", DisplayName: "ReplacementProductList", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdResetCondition, Name: "ResetCondition", DisplayName: "ResetCondition"},
		},
	})
}
