// Code generated by cmd/codegen; DO NOT EDIT.

// Package contentcontrol implements the Matter Content Control cluster (0x050F).
package contentcontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Content Control.
	ID uint32 = 0x050F
	// Name is the CLI-friendly cluster name.
	Name = "ContentControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Content Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureScreenTime             uint32 = 1 << 0 // ST
	FeaturePINManagement          uint32 = 1 << 1 // PM
	FeatureBlockUnrated           uint32 = 1 << 2 // BU
	FeatureOnDemandContentRating  uint32 = 1 << 3 // OCR
	FeatureScheduledContentRating uint32 = 1 << 4 // SCR
	FeatureBlockChannels          uint32 = 1 << 5 // BC
	FeatureBlockApplications      uint32 = 1 << 6 // BA
	FeatureBlockContentTimeWindow uint32 = 1 << 7 // BTW
)

// Attribute IDs.
const (
	AttrEnabled                         uint32 = 0x0000
	AttrOnDemandRatings                 uint32 = 0x0001
	AttrOnDemandRatingThreshold         uint32 = 0x0002
	AttrScheduledContentRatings         uint32 = 0x0003
	AttrScheduledContentRatingThreshold uint32 = 0x0004
	AttrScreenDailyTime                 uint32 = 0x0005
	AttrRemainingScreenTime             uint32 = 0x0006
	AttrBlockUnrated                    uint32 = 0x0007
	AttrBlockChannelList                uint32 = 0x0008
	AttrBlockApplicationList            uint32 = 0x0009
	AttrBlockContentTimeWindow          uint32 = 0x000A
)

// Command IDs.
const (
	CmdUpdatePIN                          uint32 = 0x00
	CmdResetPIN                           uint32 = 0x01
	CmdEnable                             uint32 = 0x03
	CmdDisable                            uint32 = 0x04
	CmdAddBonusTime                       uint32 = 0x05
	CmdSetScreenDailyTime                 uint32 = 0x06
	CmdBlockUnratedContent                uint32 = 0x07
	CmdUnblockUnratedContent              uint32 = 0x08
	CmdSetOnDemandRatingThreshold         uint32 = 0x09
	CmdSetScheduledContentRatingThreshold uint32 = 0x0A
	CmdAddBlockChannels                   uint32 = 0x0B
	CmdRemoveBlockChannels                uint32 = 0x0C
	CmdAddBlockApplications               uint32 = 0x0D
	CmdRemoveBlockApplications            uint32 = 0x0E
	CmdSetBlockContentTimeWindow          uint32 = 0x0F
	CmdRemoveBlockContentTimeWindow       uint32 = 0x10
)

// UpdatePINRequest is the request payload for the UpdatePIN command.
type UpdatePINRequest struct {
	OldPIN string `tlv:"0,utf8"`
	NewPIN string `tlv:"1,utf8"`
}

// AddBonusTimeRequest is the request payload for the AddBonusTime command.
type AddBonusTimeRequest struct {
	PINCode   string `tlv:"0,utf8"`
	BonusTime uint32 `tlv:"1,uint"`
}

// SetScreenDailyTimeRequest is the request payload for the SetScreenDailyTime command.
type SetScreenDailyTimeRequest struct {
	ScreenTime uint32 `tlv:"0,uint"`
}

// SetOnDemandRatingThresholdRequest is the request payload for the SetOnDemandRatingThreshold command.
type SetOnDemandRatingThresholdRequest struct {
	Rating string `tlv:"0,utf8"`
}

// SetScheduledContentRatingThresholdRequest is the request payload for the SetScheduledContentRatingThreshold command.
type SetScheduledContentRatingThresholdRequest struct {
	Rating string `tlv:"0,utf8"`
}

// AddBlockChannelsRequest is the request payload for the AddBlockChannels command.
type AddBlockChannelsRequest struct {
	Channels uint8 `tlv:"0,uint"`
}

// RemoveBlockChannelsRequest is the request payload for the RemoveBlockChannels command.
type RemoveBlockChannelsRequest struct {
	ChannelIndexes uint8 `tlv:"0,uint"`
}

// AddBlockApplicationsRequest is the request payload for the AddBlockApplications command.
type AddBlockApplicationsRequest struct {
	Applications uint8 `tlv:"0,uint"`
}

// RemoveBlockApplicationsRequest is the request payload for the RemoveBlockApplications command.
type RemoveBlockApplicationsRequest struct {
	Applications uint8 `tlv:"0,uint"`
}

// SetBlockContentTimeWindowRequest is the request payload for the SetBlockContentTimeWindow command.
type SetBlockContentTimeWindowRequest struct {
	TimeWindow uint8 `tlv:"0,uint"`
}

// RemoveBlockContentTimeWindowRequest is the request payload for the RemoveBlockContentTimeWindow command.
type RemoveBlockContentTimeWindowRequest struct {
	TimeWindowIndexes uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "ST", Name: "ScreenTime"},
			{Bit: 1, Code: "PM", Name: "PINManagement"},
			{Bit: 2, Code: "BU", Name: "BlockUnrated"},
			{Bit: 3, Code: "OCR", Name: "OnDemandContentRating"},
			{Bit: 4, Code: "SCR", Name: "ScheduledContentRating"},
			{Bit: 5, Code: "BC", Name: "BlockChannels"},
			{Bit: 6, Code: "BA", Name: "BlockApplications"},
			{Bit: 7, Code: "BTW", Name: "BlockContentTimeWindow"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrEnabled, Name: "Enabled", DisplayName: "Enabled", Type: "bool", Readable: true},
			{ID: AttrOnDemandRatings, Name: "OnDemandRatings", DisplayName: "OnDemandRatings", Type: "list", Readable: true},
			{ID: AttrOnDemandRatingThreshold, Name: "OnDemandRatingThreshold", DisplayName: "OnDemandRatingThreshold", Type: "string", Readable: true},
			{ID: AttrScheduledContentRatings, Name: "ScheduledContentRatings", DisplayName: "ScheduledContentRatings", Type: "list", Readable: true},
			{ID: AttrScheduledContentRatingThreshold, Name: "ScheduledContentRatingThreshold", DisplayName: "ScheduledContentRatingThreshold", Type: "string", Readable: true},
			{ID: AttrScreenDailyTime, Name: "ScreenDailyTime", DisplayName: "ScreenDailyTime", Type: "uint32", Readable: true},
			{ID: AttrRemainingScreenTime, Name: "RemainingScreenTime", DisplayName: "RemainingScreenTime", Type: "uint32", Readable: true},
			{ID: AttrBlockUnrated, Name: "BlockUnrated", DisplayName: "BlockUnrated", Type: "bool", Readable: true},
			{ID: AttrBlockChannelList, Name: "BlockChannelList", DisplayName: "BlockChannelList", Type: "list", Readable: true},
			{ID: AttrBlockApplicationList, Name: "BlockApplicationList", DisplayName: "BlockApplicationList", Type: "list", Readable: true},
			{ID: AttrBlockContentTimeWindow, Name: "BlockContentTimeWindow", DisplayName: "BlockContentTimeWindow", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdUpdatePIN, Name: "UpdatePIN", DisplayName: "UpdatePIN", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OldPIN", DisplayName: "OldPIN", Type: "string"},
				{ID: 1, Name: "NewPIN", DisplayName: "NewPIN", Type: "string"},
			}},
			{ID: CmdResetPIN, Name: "ResetPIN", DisplayName: "ResetPIN", HasResponse: true},
			{ID: CmdEnable, Name: "Enable", DisplayName: "Enable"},
			{ID: CmdDisable, Name: "Disable", DisplayName: "Disable"},
			{ID: CmdAddBonusTime, Name: "AddBonusTime", DisplayName: "AddBonusTime", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PINCode", DisplayName: "PINCode", Type: "string", Optional: true},
				{ID: 1, Name: "BonusTime", DisplayName: "BonusTime", Type: "uint32"},
			}},
			{ID: CmdSetScreenDailyTime, Name: "SetScreenDailyTime", DisplayName: "SetScreenDailyTime", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ScreenTime", DisplayName: "ScreenTime", Type: "uint32"},
			}},
			{ID: CmdBlockUnratedContent, Name: "BlockUnratedContent", DisplayName: "BlockUnratedContent"},
			{ID: CmdUnblockUnratedContent, Name: "UnblockUnratedContent", DisplayName: "UnblockUnratedContent"},
			{ID: CmdSetOnDemandRatingThreshold, Name: "SetOnDemandRatingThreshold", DisplayName: "SetOnDemandRatingThreshold", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Rating", DisplayName: "Rating", Type: "string"},
			}},
			{ID: CmdSetScheduledContentRatingThreshold, Name: "SetScheduledContentRatingThreshold", DisplayName: "SetScheduledContentRatingThreshold", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Rating", DisplayName: "Rating", Type: "string"},
			}},
			{ID: CmdAddBlockChannels, Name: "AddBlockChannels", DisplayName: "AddBlockChannels", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Channels", DisplayName: "Channels", Type: "list"},
			}},
			{ID: CmdRemoveBlockChannels, Name: "RemoveBlockChannels", DisplayName: "RemoveBlockChannels", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ChannelIndexes", DisplayName: "ChannelIndexes", Type: "list"},
			}},
			{ID: CmdAddBlockApplications, Name: "AddBlockApplications", DisplayName: "AddBlockApplications", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Applications", DisplayName: "Applications", Type: "list"},
			}},
			{ID: CmdRemoveBlockApplications, Name: "RemoveBlockApplications", DisplayName: "RemoveBlockApplications", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Applications", DisplayName: "Applications", Type: "list"},
			}},
			{ID: CmdSetBlockContentTimeWindow, Name: "SetBlockContentTimeWindow", DisplayName: "SetBlockContentTimeWindow", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TimeWindow", DisplayName: "TimeWindow", Type: "struct"},
			}},
			{ID: CmdRemoveBlockContentTimeWindow, Name: "RemoveBlockContentTimeWindow", DisplayName: "RemoveBlockContentTimeWindow", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TimeWindowIndexes", DisplayName: "TimeWindowIndexes", Type: "list"},
			}},
		},
	})
}
