// Code generated by cmd/codegen; DO NOT EDIT.

// Package diagnosticlogs implements the Matter Diagnostic Logs cluster (0x0032).
package diagnosticlogs

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Diagnostic Logs.
	ID uint32 = 0x0032
	// Name is the CLI-friendly cluster name.
	Name = "DiagnosticLogs"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Diagnostic Logs"
)

// Command IDs.
const (
	CmdRetrieveLogsRequest uint32 = 0x00
)

// RetrieveLogsRequestRequest is the request payload for the RetrieveLogsRequest command.
type RetrieveLogsRequestRequest struct {
	Intent                 uint8  `tlv:"0,uint"`
	RequestedProtocol      uint8  `tlv:"1,uint"`
	TransferFileDesignator string `tlv:"2,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdRetrieveLogsRequest, Name: "RetrieveLogsRequest", DisplayName: "RetrieveLogsRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Intent", DisplayName: "Intent", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "EndUserSupport"}, {Value: 1, Name: "NetworkDiag"}, {Value: 2, Name: "CrashLogs"}}},
				{ID: 1, Name: "RequestedProtocol", DisplayName: "RequestedProtocol", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "ResponsePayload"}, {Value: 1, Name: "BDX"}}},
				{ID: 2, Name: "TransferFileDesignator", DisplayName: "TransferFileDesignator", Type: "string", Optional: true},
			}},
		},
	})
}
