// Code generated by cmd/codegen; DO NOT EDIT.

// Package fancontrol implements the Matter Fan Control cluster (0x0202).
package fancontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Fan Control.
	ID uint32 = 0x0202
	// Name is the CLI-friendly cluster name.
	Name = "FanControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Fan Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureMultiSpeed       uint32 = 1 << 0 // SPD
	FeatureAuto             uint32 = 1 << 1 // AUT
	FeatureRocking          uint32 = 1 << 2 // RCK
	FeatureWind             uint32 = 1 << 3 // WND
	FeatureStep             uint32 = 1 << 4 // STEP
	FeatureAirflowDirection uint32 = 1 << 5 // DIR
)

// Attribute IDs.
const (
	AttrFanMode          uint32 = 0x0000
	AttrFanModeSequence  uint32 = 0x0001
	AttrPercentSetting   uint32 = 0x0002
	AttrPercentCurrent   uint32 = 0x0003
	AttrSpeedMax         uint32 = 0x0004
	AttrSpeedSetting     uint32 = 0x0005
	AttrSpeedCurrent     uint32 = 0x0006
	AttrRockSupport      uint32 = 0x0007
	AttrRockSetting      uint32 = 0x0008
	AttrWindSupport      uint32 = 0x0009
	AttrWindSetting      uint32 = 0x000A
	AttrAirflowDirection uint32 = 0x000B
)

// Command IDs.
const (
	CmdStep uint32 = 0x00
)

// StepRequest is the request payload for the Step command.
type StepRequest struct {
	Direction uint8 `tlv:"0,uint"`
	Wrap      bool  `tlv:"1,bool"`
	LowestOff bool  `tlv:"2,bool"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "SPD", Name: "MultiSpeed"},
			{Bit: 1, Code: "AUT", Name: "Auto"},
			{Bit: 2, Code: "RCK", Name: "Rocking"},
			{Bit: 3, Code: "WND", Name: "Wind"},
			{Bit: 4, Code: "STEP", Name: "Step"},
			{Bit: 5, Code: "DIR", Name: "AirflowDirection"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrFanMode, Name: "FanMode", DisplayName: "FanMode", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrFanModeSequence, Name: "FanModeSequence", DisplayName: "FanModeSequence", Type: "enum8", Readable: true},
			{ID: AttrPercentSetting, Name: "PercentSetting", DisplayName: "PercentSetting", Type: "uint8", Readable: true, Writable: true, Nullable: true},
			{ID: AttrPercentCurrent, Name: "PercentCurrent", DisplayName: "PercentCurrent", Type: "uint8", Readable: true},
			{ID: AttrSpeedMax, Name: "SpeedMax", DisplayName: "SpeedMax", Type: "uint8", Readable: true},
			{ID: AttrSpeedSetting, Name: "SpeedSetting", DisplayName: "SpeedSetting", Type: "uint8", Readable: true, Writable: true, Nullable: true},
			{ID: AttrSpeedCurrent, Name: "SpeedCurrent", DisplayName: "SpeedCurrent", Type: "uint8", Readable: true},
			{ID: AttrRockSupport, Name: "RockSupport", DisplayName: "RockSupport", Type: "bitmap8", Readable: true},
			{ID: AttrRockSetting, Name: "RockSetting", DisplayName: "RockSetting", Type: "bitmap8", Readable: true, Writable: true},
			{ID: AttrWindSupport, Name: "WindSupport", DisplayName: "WindSupport", Type: "bitmap8", Readable: true},
			{ID: AttrWindSetting, Name: "WindSetting", DisplayName: "WindSetting", Type: "bitmap8", Readable: true, Writable: true},
			{ID: AttrAirflowDirection, Name: "AirflowDirection", DisplayName: "AirflowDirection", Type: "enum8", Readable: true, Writable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdStep, Name: "Step", DisplayName: "Step", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Direction", DisplayName: "Direction", Type: "enum8"},
				{ID: 1, Name: "Wrap", DisplayName: "Wrap", Type: "bool", Optional: true},
				{ID: 2, Name: "LowestOff", DisplayName: "LowestOff", Type: "bool", Optional: true},
			}},
		},
	})
}
