// Code generated by cmd/codegen; DO NOT EDIT.

// Package temperaturecontrol implements the Matter Temperature Control cluster (0x0056).
package temperaturecontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Temperature Control.
	ID uint32 = 0x0056
	// Name is the CLI-friendly cluster name.
	Name = "TemperatureControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Temperature Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTemperatureNumber uint32 = 1 << 0 // TN
	FeatureTemperatureLevel  uint32 = 1 << 1 // TL
	FeatureTemperatureStep   uint32 = 1 << 2 // STEP
)

// Attribute IDs.
const (
	AttrTemperatureSetpoint        uint32 = 0x0000
	AttrMinTemperature             uint32 = 0x0001
	AttrMaxTemperature             uint32 = 0x0002
	AttrStep                       uint32 = 0x0003
	AttrSelectedTemperatureLevel   uint32 = 0x0004
	AttrSupportedTemperatureLevels uint32 = 0x0005
)

// Command IDs.
const (
	CmdSetTemperature uint32 = 0x00
)

// SetTemperatureRequest is the request payload for the SetTemperature command.
type SetTemperatureRequest struct {
	TargetTemperature      int16 `tlv:"0,int"`
	TargetTemperatureLevel uint8 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TN", Name: "TemperatureNumber"},
			{Bit: 1, Code: "TL", Name: "TemperatureLevel"},
			{Bit: 2, Code: "STEP", Name: "TemperatureStep"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTemperatureSetpoint, Name: "TemperatureSetpoint", DisplayName: "TemperatureSetpoint", Type: "int16", Readable: true},
			{ID: AttrMinTemperature, Name: "MinTemperature", DisplayName: "MinTemperature", Type: "int16", Readable: true},
			{ID: AttrMaxTemperature, Name: "MaxTemperature", DisplayName: "MaxTemperature", Type: "int16", Readable: true},
			{ID: AttrStep, Name: "Step", DisplayName: "Step", Type: "int16", Readable: true},
			{ID: AttrSelectedTemperatureLevel, Name: "SelectedTemperatureLevel", DisplayName: "SelectedTemperatureLevel", Type: "uint8", Readable: true},
			{ID: AttrSupportedTemperatureLevels, Name: "SupportedTemperatureLevels", DisplayName: "SupportedTemperatureLevels", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSetTemperature, Name: "SetTemperature", DisplayName: "SetTemperature", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TargetTemperature", DisplayName: "TargetTemperature", Type: "int16"},
				{ID: 1, Name: "TargetTemperatureLevel", DisplayName: "TargetTemperatureLevel", Type: "uint8"},
			}},
		},
	})
}
