// Code generated by cmd/codegen; DO NOT EDIT.

// Package laundrydryercontrols implements the Matter Laundry Dryer Controls cluster (0x004A).
package laundrydryercontrols

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Laundry Dryer Controls.
	ID uint32 = 0x004A
	// Name is the CLI-friendly cluster name.
	Name = "LaundryDryerControls"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Laundry Dryer Controls"
)

// Attribute IDs.
const (
	AttrSupportedDrynessLevels uint32 = 0x0000
	AttrSelectedDrynessLevel   uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedDrynessLevels, Name: "SupportedDrynessLevels", DisplayName: "SupportedDrynessLevels", Type: "list", Readable: true},
			{ID: AttrSelectedDrynessLevel, Name: "SelectedDrynessLevel", DisplayName: "SelectedDrynessLevel", Type: "enum8", Readable: true, Writable: true, Nullable: true},
		},
	})
}
