// Code generated by cmd/codegen; DO NOT EDIT.

// Package timesynchronization implements the Matter Time Synchronization cluster (0x0038).
package timesynchronization

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Time Synchronization.
	ID uint32 = 0x0038
	// Name is the CLI-friendly cluster name.
	Name = "TimeSynchronization"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Time Synchronization"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTimeZone       uint32 = 1 << 0 // TZ
	FeatureNTPClient      uint32 = 1 << 1 // NTPC
	FeatureNTPServer      uint32 = 1 << 2 // NTPS
	FeatureTimeSyncClient uint32 = 1 << 3 // TSC
)

// Attribute IDs.
const (
	AttrUTCTime              uint32 = 0x0000
	AttrGranularity          uint32 = 0x0001
	AttrTimeSource           uint32 = 0x0002
	AttrTrustedTimeSource    uint32 = 0x0003
	AttrDefaultNTP           uint32 = 0x0004
	AttrTimeZone             uint32 = 0x0005
	AttrDSTOffset            uint32 = 0x0006
	AttrLocalTime            uint32 = 0x0007
	AttrTimeZoneDatabase     uint32 = 0x0008
	AttrNTPServerAvailable   uint32 = 0x0009
	AttrTimeZoneListMaxSize  uint32 = 0x000A
	AttrDSTOffsetListMaxSize uint32 = 0x000B
	AttrSupportsDNSResolve   uint32 = 0x000C
)

// Command IDs.
const (
	CmdSetUTCTime           uint32 = 0x00
	CmdSetTrustedTimeSource uint32 = 0x01
	CmdSetTimeZone          uint32 = 0x02
	CmdSetDSTOffset         uint32 = 0x04
	CmdSetDefaultNTP        uint32 = 0x05
)

// SetUTCTimeRequest is the request payload for the SetUTCTime command.
type SetUTCTimeRequest struct {
	UTCTime     uint64 `tlv:"0,uint"`
	Granularity uint8  `tlv:"1,uint"`
	TimeSource  uint8  `tlv:"2,uint"`
}

// SetTrustedTimeSourceRequest is the request payload for the SetTrustedTimeSource command.
type SetTrustedTimeSourceRequest struct {
	TrustedTimeSource uint8 `tlv:"0,uint"`
}

// SetTimeZoneRequest is the request payload for the SetTimeZone command.
type SetTimeZoneRequest struct {
	TimeZone uint8 `tlv:"0,uint"`
}

// SetDSTOffsetRequest is the request payload for the SetDSTOffset command.
type SetDSTOffsetRequest struct {
	DSTOffset uint8 `tlv:"0,uint"`
}

// SetDefaultNTPRequest is the request payload for the SetDefaultNTP command.
type SetDefaultNTPRequest struct {
	DefaultNTP string `tlv:"0,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TZ", Name: "TimeZone"},
			{Bit: 1, Code: "NTPC", Name: "NTPClient"},
			{Bit: 2, Code: "NTPS", Name: "NTPServer"},
			{Bit: 3, Code: "TSC", Name: "TimeSyncClient"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrUTCTime, Name: "UTCTime", DisplayName: "UTCTime", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrGranularity, Name: "Granularity", DisplayName: "Granularity", Type: "enum8", Readable: true},
			{ID: AttrTimeSource, Name: "TimeSource", DisplayName: "TimeSource", Type: "enum8", Readable: true},
			{ID: AttrTrustedTimeSource, Name: "TrustedTimeSource", DisplayName: "TrustedTimeSource", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrDefaultNTP, Name: "DefaultNTP", DisplayName: "DefaultNTP", Type: "string", Readable: true, Nullable: true},
			{ID: AttrTimeZone, Name: "TimeZone", DisplayName: "TimeZone", Type: "list", Readable: true},
			{ID: AttrDSTOffset, Name: "DSTOffset", DisplayName: "DSTOffset", Type: "list", Readable: true},
			{ID: AttrLocalTime, Name: "LocalTime", DisplayName: "LocalTime", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrTimeZoneDatabase, Name: "TimeZoneDatabase", DisplayName: "TimeZoneDatabase", Type: "enum8", Readable: true},
			{ID: AttrNTPServerAvailable, Name: "NTPServerAvailable", DisplayName: "NTPServerAvailable", Type: "bool", Readable: true},
			{ID: AttrTimeZoneListMaxSize, Name: "TimeZoneListMaxSize", DisplayName: "TimeZoneListMaxSize", Type: "uint8", Readable: true},
			{ID: AttrDSTOffsetListMaxSize, Name: "DSTOffsetListMaxSize", DisplayName: "DSTOffsetListMaxSize", Type: "uint8", Readable: true},
			{ID: AttrSupportsDNSResolve, Name: "SupportsDNSResolve", DisplayName: "SupportsDNSResolve", Type: "bool", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSetUTCTime, Name: "SetUTCTime", DisplayName: "SetUTCTime", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UTCTime", DisplayName: "UTCTime", Type: "uint64"},
				{ID: 1, Name: "Granularity", DisplayName: "Granularity", Type: "enum8"},
				{ID: 2, Name: "TimeSource", DisplayName: "TimeSource", Type: "enum8", Optional: true},
			}},
			{ID: CmdSetTrustedTimeSource, Name: "SetTrustedTimeSource", DisplayName: "SetTrustedTimeSource", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TrustedTimeSource", DisplayName: "TrustedTimeSource", Type: "struct", Nullable: true},
			}},
			{ID: CmdSetTimeZone, Name: "SetTimeZone", DisplayName: "SetTimeZone", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TimeZone", DisplayName: "TimeZone", Type: "list"},
			}},
			{ID: CmdSetDSTOffset, Name: "SetDSTOffset", DisplayName: "SetDSTOffset", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DSTOffset", DisplayName: "DSTOffset", Type: "list"},
			}},
			{ID: CmdSetDefaultNTP, Name: "SetDefaultNTP", DisplayName: "SetDefaultNTP", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DefaultNTP", DisplayName: "DefaultNTP", Type: "string", Nullable: true},
			}},
		},
	})
}
