// Code generated by cmd/codegen; DO NOT EDIT.

// Package networkcommissioning implements the Matter Network Commissioning cluster (0x0031).
package networkcommissioning

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Network Commissioning.
	ID uint32 = 0x0031
	// Name is the CLI-friendly cluster name.
	Name = "NetworkCommissioning"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Network Commissioning"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureWiFiNetworkInterface     uint32 = 1 << 0 // WI
	FeatureThreadNetworkInterface   uint32 = 1 << 1 // TH
	FeatureEthernetNetworkInterface uint32 = 1 << 2 // ET
)

// Attribute IDs.
const (
	AttrMaxNetworks             uint32 = 0x0000
	AttrNetworks                uint32 = 0x0001
	AttrScanMaxTimeSeconds      uint32 = 0x0002
	AttrConnectMaxTimeSeconds   uint32 = 0x0003
	AttrInterfaceEnabled        uint32 = 0x0004
	AttrLastNetworkingStatus    uint32 = 0x0005
	AttrLastNetworkID           uint32 = 0x0006
	AttrLastConnectErrorValue   uint32 = 0x0007
	AttrSupportedWiFiBands      uint32 = 0x0008
	AttrSupportedThreadFeatures uint32 = 0x0009
	AttrThreadVersion           uint32 = 0x000A
)

// Command IDs.
const (
	CmdScanNetworks             uint32 = 0x00
	CmdAddOrUpdateWiFiNetwork   uint32 = 0x02
	CmdAddOrUpdateThreadNetwork uint32 = 0x03
	CmdRemoveNetwork            uint32 = 0x04
	CmdConnectNetwork           uint32 = 0x06
	CmdReorderNetwork           uint32 = 0x08
)

// ScanNetworksRequest is the request payload for the ScanNetworks command.
type ScanNetworksRequest struct {
	SSID       []byte `tlv:"0,bytes"`
	Breadcrumb uint64 `tlv:"1,uint"`
}

// AddOrUpdateWiFiNetworkRequest is the request payload for the AddOrUpdateWiFiNetwork command.
type AddOrUpdateWiFiNetworkRequest struct {
	SSID        []byte `tlv:"0,bytes"`
	Credentials []byte `tlv:"1,bytes"`
	Breadcrumb  uint64 `tlv:"2,uint"`
}

// AddOrUpdateThreadNetworkRequest is the request payload for the AddOrUpdateThreadNetwork command.
type AddOrUpdateThreadNetworkRequest struct {
	OperationalDataset []byte `tlv:"0,bytes"`
	Breadcrumb         uint64 `tlv:"1,uint"`
}

// RemoveNetworkRequest is the request payload for the RemoveNetwork command.
type RemoveNetworkRequest struct {
	NetworkID  []byte `tlv:"0,bytes"`
	Breadcrumb uint64 `tlv:"1,uint"`
}

// ConnectNetworkRequest is the request payload for the ConnectNetwork command.
type ConnectNetworkRequest struct {
	NetworkID  []byte `tlv:"0,bytes"`
	Breadcrumb uint64 `tlv:"1,uint"`
}

// ReorderNetworkRequest is the request payload for the ReorderNetwork command.
type ReorderNetworkRequest struct {
	NetworkID    []byte `tlv:"0,bytes"`
	NetworkIndex uint8  `tlv:"1,uint"`
	Breadcrumb   uint64 `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "WI", Name: "WiFiNetworkInterface"},
			{Bit: 1, Code: "TH", Name: "ThreadNetworkInterface"},
			{Bit: 2, Code: "ET", Name: "EthernetNetworkInterface"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxNetworks, Name: "MaxNetworks", DisplayName: "MaxNetworks", Type: "uint8", Readable: true},
			{ID: AttrNetworks, Name: "Networks", DisplayName: "Networks", Type: "list", Readable: true},
			{ID: AttrScanMaxTimeSeconds, Name: "ScanMaxTimeSeconds", DisplayName: "ScanMaxTimeSeconds", Type: "uint8", Readable: true},
			{ID: AttrConnectMaxTimeSeconds, Name: "ConnectMaxTimeSeconds", DisplayName: "ConnectMaxTimeSeconds", Type: "uint8", Readable: true},
			{ID: AttrInterfaceEnabled, Name: "InterfaceEnabled", DisplayName: "InterfaceEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrLastNetworkingStatus, Name: "LastNetworkingStatus", DisplayName: "LastNetworkingStatus", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrLastNetworkID, Name: "LastNetworkID", DisplayName: "LastNetworkID", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrLastConnectErrorValue, Name: "LastConnectErrorValue", DisplayName: "LastConnectErrorValue", Type: "int32", Readable: true, Nullable: true},
			{ID: AttrSupportedWiFiBands, Name: "SupportedWiFiBands", DisplayName: "SupportedWiFiBands", Type: "list", Readable: true},
			{ID: AttrSupportedThreadFeatures, Name: "SupportedThreadFeatures", DisplayName: "SupportedThreadFeatures", Type: "bitmap8", Readable: true},
			{ID: AttrThreadVersion, Name: "ThreadVersion", DisplayName: "ThreadVersion", Type: "uint16", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdScanNetworks, Name: "ScanNetworks", DisplayName: "ScanNetworks", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SSID", DisplayName: "SSID", Type: "octets", Optional: true, Nullable: true},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdAddOrUpdateWiFiNetwork, Name: "AddOrUpdateWiFiNetwork", DisplayName: "AddOrUpdateWiFiNetwork", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SSID", DisplayName: "SSID", Type: "octets"},
				{ID: 1, Name: "Credentials", DisplayName: "Credentials", Type: "octets"},
				{ID: 2, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdAddOrUpdateThreadNetwork, Name: "AddOrUpdateThreadNetwork", DisplayName: "AddOrUpdateThreadNetwork", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OperationalDataset", DisplayName: "OperationalDataset", Type: "octets"},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdRemoveNetwork, Name: "RemoveNetwork", DisplayName: "RemoveNetwork", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NetworkID", DisplayName: "NetworkID", Type: "octets"},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdConnectNetwork, Name: "ConnectNetwork", DisplayName: "ConnectNetwork", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NetworkID", DisplayName: "NetworkID", Type: "octets"},
				{ID: 1, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
			{ID: CmdReorderNetwork, Name: "ReorderNetwork", DisplayName: "ReorderNetwork", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NetworkID", DisplayName: "NetworkID", Type: "octets"},
				{ID: 1, Name: "NetworkIndex", DisplayName: "NetworkIndex", Type: "uint8"},
				{ID: 2, Name: "Breadcrumb", DisplayName: "Breadcrumb", Type: "uint64", Optional: true},
			}},
		},
	})
}
