// Code generated by cmd/codegen; DO NOT EDIT.

// Package operationalcredentials implements the Matter Operational Credentials cluster (0x003E).
package operationalcredentials

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Operational Credentials.
	ID uint32 = 0x003E
	// Name is the CLI-friendly cluster name.
	Name = "OperationalCredentials"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Operational Credentials"
)

// Attribute IDs.
const (
	AttrNOCs                    uint32 = 0x0000
	AttrFabrics                 uint32 = 0x0001
	AttrSupportedFabrics        uint32 = 0x0002
	AttrCommissionedFabrics     uint32 = 0x0003
	AttrTrustedRootCertificates uint32 = 0x0004
	AttrCurrentFabricIndex      uint32 = 0x0005
)

// Command IDs.
const (
	CmdAttestationRequest          uint32 = 0x00
	CmdCertificateChainRequest     uint32 = 0x02
	CmdCSRRequest                  uint32 = 0x04
	CmdAddNOC                      uint32 = 0x06
	CmdUpdateNOC                   uint32 = 0x07
	CmdUpdateFabricLabel           uint32 = 0x09
	CmdRemoveFabric                uint32 = 0x0A
	CmdAddTrustedRootCertificate   uint32 = 0x0B
	CmdSetVIDVerificationStatement uint32 = 0x0C
	CmdSignVIDVerificationRequest  uint32 = 0x0D
)

// AttestationRequestRequest is the request payload for the AttestationRequest command.
type AttestationRequestRequest struct {
	AttestationNonce []byte `tlv:"0,bytes"`
}

// CertificateChainRequestRequest is the request payload for the CertificateChainRequest command.
type CertificateChainRequestRequest struct {
	CertificateType uint8 `tlv:"0,uint"`
}

// CSRRequestRequest is the request payload for the CSRRequest command.
type CSRRequestRequest struct {
	CSRNonce       []byte `tlv:"0,bytes"`
	IsForUpdateNOC bool   `tlv:"1,bool"`
}

// AddNOCRequest is the request payload for the AddNOC command.
type AddNOCRequest struct {
	NOCValue         []byte `tlv:"0,bytes"`
	ICACValue        []byte `tlv:"1,bytes"`
	IPKValue         []byte `tlv:"2,bytes"`
	CaseAdminSubject uint64 `tlv:"3,uint"`
	AdminVendorId    uint16 `tlv:"4,uint"`
}

// UpdateNOCRequest is the request payload for the UpdateNOC command.
type UpdateNOCRequest struct {
	NOCValue  []byte `tlv:"0,bytes"`
	ICACValue []byte `tlv:"1,bytes"`
}

// UpdateFabricLabelRequest is the request payload for the UpdateFabricLabel command.
type UpdateFabricLabelRequest struct {
	Label string `tlv:"0,utf8"`
}

// RemoveFabricRequest is the request payload for the RemoveFabric command.
type RemoveFabricRequest struct {
	FabricIndex uint8 `tlv:"0,uint"`
}

// AddTrustedRootCertificateRequest is the request payload for the AddTrustedRootCertificate command.
type AddTrustedRootCertificateRequest struct {
	RootCACertificate []byte `tlv:"0,bytes"`
}

// SetVIDVerificationStatementRequest is the request payload for the SetVIDVerificationStatement command.
type SetVIDVerificationStatementRequest struct {
	VendorID                 uint16 `tlv:"0,uint"`
	VIDVerificationStatement []byte `tlv:"1,bytes"`
	VVSC                     []byte `tlv:"2,bytes"`
}

// SignVIDVerificationRequestRequest is the request payload for the SignVIDVerificationRequest command.
type SignVIDVerificationRequestRequest struct {
	FabricIndex     uint8  `tlv:"0,uint"`
	ClientChallenge []byte `tlv:"1,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrNOCs, Name: "NOCs", DisplayName: "NOCs", Type: "list", Readable: true},
			{ID: AttrFabrics, Name: "Fabrics", DisplayName: "Fabrics", Type: "list", Readable: true},
			{ID: AttrSupportedFabrics, Name: "SupportedFabrics", DisplayName: "SupportedFabrics", Type: "uint8", Readable: true},
			{ID: AttrCommissionedFabrics, Name: "CommissionedFabrics", DisplayName: "CommissionedFabrics", Type: "uint8", Readable: true},
			{ID: AttrTrustedRootCertificates, Name: "TrustedRootCertificates", DisplayName: "TrustedRootCertificates", Type: "list", Readable: true},
			{ID: AttrCurrentFabricIndex, Name: "CurrentFabricIndex", DisplayName: "CurrentFabricIndex", Type: "uint8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAttestationRequest, Name: "AttestationRequest", DisplayName: "AttestationRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AttestationNonce", DisplayName: "AttestationNonce", Type: "octets"},
			}},
			{ID: CmdCertificateChainRequest, Name: "CertificateChainRequest", DisplayName: "CertificateChainRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CertificateType", DisplayName: "CertificateType", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 1, Name: "DACCertificate"}, {Value: 2, Name: "PAICertificate"}}},
			}},
			{ID: CmdCSRRequest, Name: "CSRRequest", DisplayName: "CSRRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CSRNonce", DisplayName: "CSRNonce", Type: "octets"},
				{ID: 1, Name: "IsForUpdateNOC", DisplayName: "IsForUpdateNOC", Type: "bool", Optional: true},
			}},
			{ID: CmdAddNOC, Name: "AddNOC", DisplayName: "AddNOC", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NOCValue", DisplayName: "NOCValue", Type: "octets"},
				{ID: 1, Name: "ICACValue", DisplayName: "ICACValue", Type: "octets", Optional: true},
				{ID: 2, Name: "IPKValue", DisplayName: "IPKValue", Type: "octets"},
				{ID: 3, Name: "CaseAdminSubject", DisplayName: "CaseAdminSubject", Type: "uint64"},
				{ID: 4, Name: "AdminVendorId", DisplayName: "AdminVendorId", Type: "uint16"},
			}},
			{ID: CmdUpdateNOC, Name: "UpdateNOC", DisplayName: "UpdateNOC", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NOCValue", DisplayName: "NOCValue", Type: "octets"},
				{ID: 1, Name: "ICACValue", DisplayName: "ICACValue", Type: "octets", Optional: true},
			}},
			{ID: CmdUpdateFabricLabel, Name: "UpdateFabricLabel", DisplayName: "UpdateFabricLabel", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Label", DisplayName: "Label", Type: "string"},
			}},
			{ID: CmdRemoveFabric, Name: "RemoveFabric", DisplayName: "RemoveFabric", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "FabricIndex", DisplayName: "FabricIndex", Type: "uint8"},
			}},
			{ID: CmdAddTrustedRootCertificate, Name: "AddTrustedRootCertificate", DisplayName: "AddTrustedRootCertificate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "RootCACertificate", DisplayName: "RootCACertificate", Type: "octets"},
			}},
			{ID: CmdSetVIDVerificationStatement, Name: "SetVIDVerificationStatement", DisplayName: "SetVIDVerificationStatement", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VendorID", DisplayName: "VendorID", Type: "uint16", Optional: true},
				{ID: 1, Name: "VIDVerificationStatement", DisplayName: "VIDVerificationStatement", Type: "octets", Optional: true},
				{ID: 2, Name: "VVSC", DisplayName: "VVSC", Type: "octets", Optional: true},
			}},
			{ID: CmdSignVIDVerificationRequest, Name: "SignVIDVerificationRequest", DisplayName: "SignVIDVerificationRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "FabricIndex", DisplayName: "FabricIndex", Type: "uint8"},
				{ID: 1, Name: "ClientChallenge", DisplayName: "ClientChallenge", Type: "octets"},
			}},
		},
	})
}
