// Code generated by cmd/codegen; DO NOT EDIT.

// Package pushavstreamtransport implements the Matter Push AV Stream Transport cluster (0x0555).
package pushavstreamtransport

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Push AV Stream Transport.
	ID uint32 = 0x0555
	// Name is the CLI-friendly cluster name.
	Name = "PushAVStreamTransport"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Push AV Stream Transport"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePerZoneSensitivity uint32 = 1 << 0 // PERZONESENS
	FeatureMetadata           uint32 = 1 << 1 // METADATA
)

// Attribute IDs.
const (
	AttrSupportedFormats   uint32 = 0x0000
	AttrCurrentConnections uint32 = 0x0001
)

// Command IDs.
const (
	CmdAllocatePushTransport    uint32 = 0x00
	CmdDeallocatePushTransport  uint32 = 0x02
	CmdModifyPushTransport      uint32 = 0x03
	CmdSetTransportStatus       uint32 = 0x04
	CmdManuallyTriggerTransport uint32 = 0x05
	CmdFindTransport            uint32 = 0x06
)

// AllocatePushTransportRequest is the request payload for the AllocatePushTransport command.
type AllocatePushTransportRequest struct {
	TransportOptions uint8 `tlv:"0,uint"`
}

// DeallocatePushTransportRequest is the request payload for the DeallocatePushTransport command.
type DeallocatePushTransportRequest struct {
	ConnectionID uint8 `tlv:"0,uint"`
}

// ModifyPushTransportRequest is the request payload for the ModifyPushTransport command.
type ModifyPushTransportRequest struct {
	ConnectionID     uint8 `tlv:"0,uint"`
	TransportOptions uint8 `tlv:"1,uint"`
}

// SetTransportStatusRequest is the request payload for the SetTransportStatus command.
type SetTransportStatusRequest struct {
	ConnectionID    uint8 `tlv:"0,uint"`
	TransportStatus uint8 `tlv:"1,uint"`
}

// ManuallyTriggerTransportRequest is the request payload for the ManuallyTriggerTransport command.
type ManuallyTriggerTransportRequest struct {
	ConnectionID     uint8  `tlv:"0,uint"`
	ActivationReason uint8  `tlv:"1,uint"`
	TimeControl      uint8  `tlv:"2,uint"`
	UserDefined      []byte `tlv:"3,bytes"`
}

// FindTransportRequest is the request payload for the FindTransport command.
type FindTransportRequest struct {
	ConnectionID uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PERZONESENS", Name: "PerZoneSensitivity"},
			{Bit: 1, Code: "METADATA", Name: "Metadata"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedFormats, Name: "SupportedFormats", DisplayName: "SupportedFormats", Type: "list", Readable: true},
			{ID: AttrCurrentConnections, Name: "CurrentConnections", DisplayName: "CurrentConnections", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAllocatePushTransport, Name: "AllocatePushTransport", DisplayName: "AllocatePushTransport", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TransportOptions", DisplayName: "TransportOptions", Type: "struct"},
			}},
			{ID: CmdDeallocatePushTransport, Name: "DeallocatePushTransport", DisplayName: "DeallocatePushTransport", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ConnectionID", DisplayName: "ConnectionID", Type: "uint8"},
			}},
			{ID: CmdModifyPushTransport, Name: "ModifyPushTransport", DisplayName: "ModifyPushTransport", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ConnectionID", DisplayName: "ConnectionID", Type: "uint8"},
				{ID: 1, Name: "TransportOptions", DisplayName: "TransportOptions", Type: "struct"},
			}},
			{ID: CmdSetTransportStatus, Name: "SetTransportStatus", DisplayName: "SetTransportStatus", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ConnectionID", DisplayName: "ConnectionID", Type: "uint8", Nullable: true},
				{ID: 1, Name: "TransportStatus", DisplayName: "TransportStatus", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "Active"}, {Value: 1, Name: "Inactive"}}},
			}},
			{ID: CmdManuallyTriggerTransport, Name: "ManuallyTriggerTransport", DisplayName: "ManuallyTriggerTransport", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ConnectionID", DisplayName: "ConnectionID", Type: "uint8"},
				{ID: 1, Name: "ActivationReason", DisplayName: "ActivationReason", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "UserInitiated"}, {Value: 1, Name: "Automation"}, {Value: 2, Name: "Emergency"}}},
				{ID: 2, Name: "TimeControl", DisplayName: "TimeControl", Type: "struct", Optional: true},
				{ID: 3, Name: "UserDefined", DisplayName: "UserDefined", Type: "octets", Optional: true},
			}},
			{ID: CmdFindTransport, Name: "FindTransport", DisplayName: "FindTransport", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ConnectionID", DisplayName: "ConnectionID", Type: "uint8", Nullable: true},
			}},
		},
	})
}
