// Code generated by cmd/codegen; DO NOT EDIT.

// Package ethernetnetworkdiagnostics implements the Matter Ethernet Network Diagnostics cluster (0x0037).
package ethernetnetworkdiagnostics

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Ethernet Network Diagnostics.
	ID uint32 = 0x0037
	// Name is the CLI-friendly cluster name.
	Name = "EthernetNetworkDiagnostics"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Ethernet Network Diagnostics"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePacketCounts uint32 = 1 << 0 // PKTCNT
	FeatureErrorCounts  uint32 = 1 << 1 // ERRCNT
)

// Attribute IDs.
const (
	AttrPHYRate        uint32 = 0x0000
	AttrFullDuplex     uint32 = 0x0001
	AttrPacketRxCount  uint32 = 0x0002
	AttrPacketTxCount  uint32 = 0x0003
	AttrTxErrCount     uint32 = 0x0004
	AttrCollisionCount uint32 = 0x0005
	AttrOverrunCount   uint32 = 0x0006
	AttrCarrierDetect  uint32 = 0x0007
	AttrTimeSinceReset uint32 = 0x0008
)

// Command IDs.
const (
	CmdResetCounts uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PKTCNT", Name: "PacketCounts"},
			{Bit: 1, Code: "ERRCNT", Name: "ErrorCounts"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrPHYRate, Name: "PHYRate", DisplayName: "PHYRate", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrFullDuplex, Name: "FullDuplex", DisplayName: "FullDuplex", Type: "bool", Readable: true, Nullable: true},
			{ID: AttrPacketRxCount, Name: "PacketRxCount", DisplayName: "PacketRxCount", Type: "uint64", Readable: true},
			{ID: AttrPacketTxCount, Name: "PacketTxCount", DisplayName: "PacketTxCount", Type: "uint64", Readable: true},
			{ID: AttrTxErrCount, Name: "TxErrCount", DisplayName: "TxErrCount", Type: "uint64", Readable: true},
			{ID: AttrCollisionCount, Name: "CollisionCount", DisplayName: "CollisionCount", Type: "uint64", Readable: true},
			{ID: AttrOverrunCount, Name: "OverrunCount", DisplayName: "OverrunCount", Type: "uint64", Readable: true},
			{ID: AttrCarrierDetect, Name: "CarrierDetect", DisplayName: "CarrierDetect", Type: "bool", Readable: true, Nullable: true},
			{ID: AttrTimeSinceReset, Name: "TimeSinceReset", DisplayName: "TimeSinceReset", Type: "uint64", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdResetCounts, Name: "ResetCounts", DisplayName: "ResetCounts"},
		},
	})
}
