// Code generated by cmd/codegen; DO NOT EDIT.

// Package closurecontrol implements the Matter Closure Control cluster (0x0104).
package closurecontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Closure Control.
	ID uint32 = 0x0104
	// Name is the CLI-friendly cluster name.
	Name = "ClosureControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Closure Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePositioning      uint32 = 1 << 0 // PS
	FeatureMotionLatching   uint32 = 1 << 1 // LT
	FeatureInstantaneous    uint32 = 1 << 2 // IS
	FeatureSpeed            uint32 = 1 << 3 // SP
	FeatureVentilation      uint32 = 1 << 4 // VT
	FeaturePedestrian       uint32 = 1 << 5 // PD
	FeatureCalibration      uint32 = 1 << 6 // CL
	FeatureProtection       uint32 = 1 << 7 // PT
	FeatureManuallyOperable uint32 = 1 << 8 // MO
)

// Attribute IDs.
const (
	AttrCountdownTime       uint32 = 0x0000
	AttrMainState           uint32 = 0x0001
	AttrCurrentErrorList    uint32 = 0x0002
	AttrOverallCurrentState uint32 = 0x0003
	AttrOverallTargetState  uint32 = 0x0004
	AttrLatchControlModes   uint32 = 0x0005
)

// Command IDs.
const (
	CmdStop      uint32 = 0x00
	CmdMoveTo    uint32 = 0x01
	CmdCalibrate uint32 = 0x02
)

// MoveToRequest is the request payload for the MoveTo command.
type MoveToRequest struct {
	Position uint8 `tlv:"0,uint"`
	Latch    bool  `tlv:"1,bool"`
	Speed    uint8 `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PS", Name: "Positioning"},
			{Bit: 1, Code: "LT", Name: "MotionLatching"},
			{Bit: 2, Code: "IS", Name: "Instantaneous"},
			{Bit: 3, Code: "SP", Name: "Speed"},
			{Bit: 4, Code: "VT", Name: "Ventilation"},
			{Bit: 5, Code: "PD", Name: "Pedestrian"},
			{Bit: 6, Code: "CL", Name: "Calibration"},
			{Bit: 7, Code: "PT", Name: "Protection"},
			{Bit: 8, Code: "MO", Name: "ManuallyOperable"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCountdownTime, Name: "CountdownTime", DisplayName: "CountdownTime", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrMainState, Name: "MainState", DisplayName: "MainState", Type: "enum8", Readable: true},
			{ID: AttrCurrentErrorList, Name: "CurrentErrorList", DisplayName: "CurrentErrorList", Type: "list", Readable: true},
			{ID: AttrOverallCurrentState, Name: "OverallCurrentState", DisplayName: "OverallCurrentState", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrOverallTargetState, Name: "OverallTargetState", DisplayName: "OverallTargetState", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrLatchControlModes, Name: "LatchControlModes", DisplayName: "LatchControlModes", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdStop, Name: "Stop", DisplayName: "Stop"},
			{ID: CmdMoveTo, Name: "MoveTo", DisplayName: "MoveTo", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Position", DisplayName: "Position", Type: "enum8", Optional: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "MoveToFullyClosed"}, {Value: 1, Name: "MoveToFullyOpen"}, {Value: 2, Name: "MoveToPedestrianPosition"}, {Value: 3, Name: "MoveToVentilationPosition"}, {Value: 4, Name: "MoveToSignaturePosition"}}},
				{ID: 1, Name: "Latch", DisplayName: "Latch", Type: "bool", Optional: true},
				{ID: 2, Name: "Speed", DisplayName: "Speed", Type: "enum8", Optional: true},
			}},
			{ID: CmdCalibrate, Name: "Calibrate", DisplayName: "Calibrate"},
		},
	})
}
