// Code generated by cmd/codegen; DO NOT EDIT.

// Package meteridentification implements the Matter Meter Identification cluster (0x0B06).
package meteridentification

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Meter Identification.
	ID uint32 = 0x0B06
	// Name is the CLI-friendly cluster name.
	Name = "MeterIdentification"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Meter Identification"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePowerThreshold uint32 = 1 << 0 // PWRTHLD
)

// Attribute IDs.
const (
	AttrMeterType         uint32 = 0x0000
	AttrPointOfDelivery   uint32 = 0x0001
	AttrMeterSerialNumber uint32 = 0x0002
	AttrProtocolVersion   uint32 = 0x0003
	AttrPowerThreshold    uint32 = 0x0004
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PWRTHLD", Name: "PowerThreshold"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMeterType, Name: "MeterType", DisplayName: "MeterType", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrPointOfDelivery, Name: "PointOfDelivery", DisplayName: "PointOfDelivery", Type: "string", Readable: true, Nullable: true},
			{ID: AttrMeterSerialNumber, Name: "MeterSerialNumber", DisplayName: "MeterSerialNumber", Type: "string", Readable: true, Nullable: true},
			{ID: AttrProtocolVersion, Name: "ProtocolVersion", DisplayName: "ProtocolVersion", Type: "string", Readable: true, Nullable: true},
			{ID: AttrPowerThreshold, Name: "PowerThreshold", DisplayName: "PowerThreshold", Type: "struct", Readable: true, Nullable: true},
		},
	})
}
