// Code generated by cmd/codegen; DO NOT EDIT.

// Package ozoneconcentrationmeasurement implements the Matter Ozone Concentration Measurement cluster (0x0415).
package ozoneconcentrationmeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Ozone Concentration Measurement.
	ID uint32 = 0x0415
	// Name is the CLI-friendly cluster name.
	Name = "OzoneConcentrationMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Ozone Concentration Measurement"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureNumericMeasurement uint32 = 1 << 0 // MEA
	FeatureLevelIndication    uint32 = 1 << 1 // LEV
	FeatureMediumLevel        uint32 = 1 << 2 // MED
	FeatureCriticalLevel      uint32 = 1 << 3 // CRI
	FeaturePeakMeasurement    uint32 = 1 << 4 // PEA
	FeatureAverageMeasurement uint32 = 1 << 5 // AVG
)

// Attribute IDs.
const (
	AttrMeasuredValue              uint32 = 0x0000
	AttrMinMeasuredValue           uint32 = 0x0001
	AttrMaxMeasuredValue           uint32 = 0x0002
	AttrPeakMeasuredValue          uint32 = 0x0003
	AttrPeakMeasuredValueWindow    uint32 = 0x0004
	AttrAverageMeasuredValue       uint32 = 0x0005
	AttrAverageMeasuredValueWindow uint32 = 0x0006
	AttrUncertainty                uint32 = 0x0007
	AttrMeasurementUnit            uint32 = 0x0008
	AttrMeasurementMedium          uint32 = 0x0009
	AttrLevelValue                 uint32 = 0x000A
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "MEA", Name: "NumericMeasurement"},
			{Bit: 1, Code: "LEV", Name: "LevelIndication"},
			{Bit: 2, Code: "MED", Name: "MediumLevel"},
			{Bit: 3, Code: "CRI", Name: "CriticalLevel"},
			{Bit: 4, Code: "PEA", Name: "PeakMeasurement"},
			{Bit: 5, Code: "AVG", Name: "AverageMeasurement"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMeasuredValue, Name: "MeasuredValue", DisplayName: "MeasuredValue", Type: "float32", Readable: true, Nullable: true},
			{ID: AttrMinMeasuredValue, Name: "MinMeasuredValue", DisplayName: "MinMeasuredValue", Type: "float32", Readable: true, Nullable: true},
			{ID: AttrMaxMeasuredValue, Name: "MaxMeasuredValue", DisplayName: "MaxMeasuredValue", Type: "float32", Readable: true, Nullable: true},
			{ID: AttrPeakMeasuredValue, Name: "PeakMeasuredValue", DisplayName: "PeakMeasuredValue", Type: "float32", Readable: true, Nullable: true},
			{ID: AttrPeakMeasuredValueWindow, Name: "PeakMeasuredValueWindow", DisplayName: "PeakMeasuredValueWindow", Type: "uint32", Readable: true},
			{ID: AttrAverageMeasuredValue, Name: "AverageMeasuredValue", DisplayName: "AverageMeasuredValue", Type: "float32", Readable: true, Nullable: true},
			{ID: AttrAverageMeasuredValueWindow, Name: "AverageMeasuredValueWindow", DisplayName: "AverageMeasuredValueWindow", Type: "uint32", Readable: true},
			{ID: AttrUncertainty, Name: "Uncertainty", DisplayName: "Uncertainty", Type: "float32", Readable: true},
			{ID: AttrMeasurementUnit, Name: "MeasurementUnit", DisplayName: "MeasurementUnit", Type: "enum8", Readable: true},
			{ID: AttrMeasurementMedium, Name: "MeasurementMedium", DisplayName: "MeasurementMedium", Type: "enum8", Readable: true},
			{ID: AttrLevelValue, Name: "LevelValue", DisplayName: "LevelValue", Type: "enum8", Readable: true},
		},
	})
}
