// Code generated by cmd/codegen; DO NOT EDIT.

// Package channel implements the Matter Channel cluster (0x0504).
package channel

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Channel.
	ID uint32 = 0x0504
	// Name is the CLI-friendly cluster name.
	Name = "Channel"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Channel"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureChannelList     uint32 = 1 << 0 // CL
	FeatureLineupInfo      uint32 = 1 << 1 // LI
	FeatureElectronicGuide uint32 = 1 << 2 // EG
	FeatureRecordProgram   uint32 = 1 << 3 // RP
)

// Attribute IDs.
const (
	AttrChannelList    uint32 = 0x0000
	AttrLineup         uint32 = 0x0001
	AttrCurrentChannel uint32 = 0x0002
)

// Command IDs.
const (
	CmdChangeChannel         uint32 = 0x00
	CmdChangeChannelByNumber uint32 = 0x02
	CmdSkipChannel           uint32 = 0x03
	CmdGetProgramGuide       uint32 = 0x04
	CmdRecordProgram         uint32 = 0x06
	CmdCancelRecordProgram   uint32 = 0x07
)

// ChangeChannelRequest is the request payload for the ChangeChannel command.
type ChangeChannelRequest struct {
	Match string `tlv:"0,utf8"`
}

// ChangeChannelByNumberRequest is the request payload for the ChangeChannelByNumber command.
type ChangeChannelByNumberRequest struct {
	MajorNumber uint16 `tlv:"0,uint"`
	MinorNumber uint16 `tlv:"1,uint"`
}

// SkipChannelRequest is the request payload for the SkipChannel command.
type SkipChannelRequest struct {
	Count int16 `tlv:"0,int"`
}

// GetProgramGuideRequest is the request payload for the GetProgramGuide command.
type GetProgramGuideRequest struct {
	StartTime      uint32 `tlv:"0,uint"`
	EndTime        uint32 `tlv:"1,uint"`
	ChannelList    uint8  `tlv:"2,uint"`
	PageToken      uint8  `tlv:"3,uint"`
	RecordingFlag  uint8  `tlv:"5,uint"`
	ExternalIDList uint8  `tlv:"6,uint"`
	Data           []byte `tlv:"7,bytes"`
}

// RecordProgramRequest is the request payload for the RecordProgram command.
type RecordProgramRequest struct {
	ProgramIdentifier  string `tlv:"0,utf8"`
	ShouldRecordSeries bool   `tlv:"1,bool"`
	ExternalIDList     uint8  `tlv:"2,uint"`
	Data               []byte `tlv:"3,bytes"`
}

// CancelRecordProgramRequest is the request payload for the CancelRecordProgram command.
type CancelRecordProgramRequest struct {
	ProgramIdentifier  string `tlv:"0,utf8"`
	ShouldRecordSeries bool   `tlv:"1,bool"`
	ExternalIDList     uint8  `tlv:"2,uint"`
	Data               []byte `tlv:"3,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CL", Name: "ChannelList"},
			{Bit: 1, Code: "LI", Name: "LineupInfo"},
			{Bit: 2, Code: "EG", Name: "ElectronicGuide"},
			{Bit: 3, Code: "RP", Name: "RecordProgram"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrChannelList, Name: "ChannelList", DisplayName: "ChannelList", Type: "list", Readable: true},
			{ID: AttrLineup, Name: "Lineup", DisplayName: "Lineup", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrCurrentChannel, Name: "CurrentChannel", DisplayName: "CurrentChannel", Type: "struct", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdChangeChannel, Name: "ChangeChannel", DisplayName: "ChangeChannel", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Match", DisplayName: "Match", Type: "string"},
			}},
			{ID: CmdChangeChannelByNumber, Name: "ChangeChannelByNumber", DisplayName: "ChangeChannelByNumber", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "MajorNumber", DisplayName: "MajorNumber", Type: "uint16"},
				{ID: 1, Name: "MinorNumber", DisplayName: "MinorNumber", Type: "uint16"},
			}},
			{ID: CmdSkipChannel, Name: "SkipChannel", DisplayName: "SkipChannel", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Count", DisplayName: "Count", Type: "int16"},
			}},
			{ID: CmdGetProgramGuide, Name: "GetProgramGuide", DisplayName: "GetProgramGuide", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StartTime", DisplayName: "StartTime", Type: "uint32"},
				{ID: 1, Name: "EndTime", DisplayName: "EndTime", Type: "uint32"},
				{ID: 2, Name: "ChannelList", DisplayName: "ChannelList", Type: "list", Optional: true},
				{ID: 3, Name: "PageToken", DisplayName: "PageToken", Type: "struct", Optional: true, Nullable: true},
				{ID: 5, Name: "RecordingFlag", DisplayName: "RecordingFlag", Type: "bitmap8", Optional: true, Nullable: true},
				{ID: 6, Name: "ExternalIDList", DisplayName: "ExternalIDList", Type: "list", Optional: true},
				{ID: 7, Name: "Data", DisplayName: "Data", Type: "octets", Optional: true},
			}},
			{ID: CmdRecordProgram, Name: "RecordProgram", DisplayName: "RecordProgram", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ProgramIdentifier", DisplayName: "ProgramIdentifier", Type: "string"},
				{ID: 1, Name: "ShouldRecordSeries", DisplayName: "ShouldRecordSeries", Type: "bool"},
				{ID: 2, Name: "ExternalIDList", DisplayName: "ExternalIDList", Type: "list", Optional: true},
				{ID: 3, Name: "Data", DisplayName: "Data", Type: "octets", Optional: true},
			}},
			{ID: CmdCancelRecordProgram, Name: "CancelRecordProgram", DisplayName: "CancelRecordProgram", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ProgramIdentifier", DisplayName: "ProgramIdentifier", Type: "string"},
				{ID: 1, Name: "ShouldRecordSeries", DisplayName: "ShouldRecordSeries", Type: "bool"},
				{ID: 2, Name: "ExternalIDList", DisplayName: "ExternalIDList", Type: "list", Optional: true},
				{ID: 3, Name: "Data", DisplayName: "Data", Type: "octets", Optional: true},
			}},
		},
	})
}
