// Code generated by cmd/codegen; DO NOT EDIT.

// Package energypreference implements the Matter Energy Preference cluster (0x009B).
package energypreference

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Energy Preference.
	ID uint32 = 0x009B
	// Name is the CLI-friendly cluster name.
	Name = "EnergyPreference"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Energy Preference"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureEnergyBalance           uint32 = 1 << 0 // BALA
	FeatureLowPowerModeSensitivity uint32 = 1 << 1 // LPMS
)

// Attribute IDs.
const (
	AttrEnergyBalances                 uint32 = 0x0000
	AttrCurrentEnergyBalance           uint32 = 0x0001
	AttrEnergyPriorities               uint32 = 0x0002
	AttrLowPowerModeSensitivities      uint32 = 0x0003
	AttrCurrentLowPowerModeSensitivity uint32 = 0x0004
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "BALA", Name: "EnergyBalance"},
			{Bit: 1, Code: "LPMS", Name: "LowPowerModeSensitivity"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrEnergyBalances, Name: "EnergyBalances", DisplayName: "EnergyBalances", Type: "list", Readable: true},
			{ID: AttrCurrentEnergyBalance, Name: "CurrentEnergyBalance", DisplayName: "CurrentEnergyBalance", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrEnergyPriorities, Name: "EnergyPriorities", DisplayName: "EnergyPriorities", Type: "list", Readable: true},
			{ID: AttrLowPowerModeSensitivities, Name: "LowPowerModeSensitivities", DisplayName: "LowPowerModeSensitivities", Type: "list", Readable: true},
			{ID: AttrCurrentLowPowerModeSensitivity, Name: "CurrentLowPowerModeSensitivity", DisplayName: "CurrentLowPowerModeSensitivity", Type: "uint8", Readable: true, Writable: true},
		},
	})
}
