// Code generated by cmd/codegen; DO NOT EDIT.

// Package thermostat implements the Matter Thermostat cluster (0x0201).
package thermostat

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Thermostat.
	ID uint32 = 0x0201
	// Name is the CLI-friendly cluster name.
	Name = "Thermostat"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Thermostat"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureHeating                     uint32 = 1 << 0 // HEAT
	FeatureCooling                     uint32 = 1 << 1 // COOL
	FeatureOccupancy                   uint32 = 1 << 2 // OCC
	FeatureSetback                     uint32 = 1 << 4 // SB
	FeatureAutoMode                    uint32 = 1 << 5 // AUTO
	FeatureLocalTemperatureNotExposed  uint32 = 1 << 6 // LTNE
	FeatureMatterScheduleConfiguration uint32 = 1 << 7 // MSCH
	FeaturePresets                     uint32 = 1 << 8 // PRES
)

// Attribute IDs.
const (
	AttrLocalTemperature                   uint32 = 0x0000
	AttrOutdoorTemperature                 uint32 = 0x0001
	AttrOccupancy                          uint32 = 0x0002
	AttrAbsMinHeatSetpointLimit            uint32 = 0x0003
	AttrAbsMaxHeatSetpointLimit            uint32 = 0x0004
	AttrAbsMinCoolSetpointLimit            uint32 = 0x0005
	AttrAbsMaxCoolSetpointLimit            uint32 = 0x0006
	AttrPICoolingDemand                    uint32 = 0x0007
	AttrPIHeatingDemand                    uint32 = 0x0008
	AttrHVACSystemTypeConfiguration        uint32 = 0x0009
	AttrLocalTemperatureCalibration        uint32 = 0x0010
	AttrOccupiedCoolingSetpoint            uint32 = 0x0011
	AttrOccupiedHeatingSetpoint            uint32 = 0x0012
	AttrUnoccupiedCoolingSetpoint          uint32 = 0x0013
	AttrUnoccupiedHeatingSetpoint          uint32 = 0x0014
	AttrMinHeatSetpointLimit               uint32 = 0x0015
	AttrMaxHeatSetpointLimit               uint32 = 0x0016
	AttrMinCoolSetpointLimit               uint32 = 0x0017
	AttrMaxCoolSetpointLimit               uint32 = 0x0018
	AttrMinSetpointDeadBand                uint32 = 0x0019
	AttrRemoteSensing                      uint32 = 0x001A
	AttrControlSequenceOfOperation         uint32 = 0x001B
	AttrSystemMode                         uint32 = 0x001C
	AttrThermostatRunningMode              uint32 = 0x001E
	AttrTemperatureSetpointHold            uint32 = 0x0023
	AttrTemperatureSetpointHoldDuration    uint32 = 0x0024
	AttrThermostatProgrammingOperationMode uint32 = 0x0025
	AttrThermostatRunningState             uint32 = 0x0029
	AttrSetpointChangeSource               uint32 = 0x0030
	AttrSetpointChangeAmount               uint32 = 0x0031
	AttrSetpointChangeSourceTimestamp      uint32 = 0x0032
	AttrOccupiedSetback                    uint32 = 0x0034
	AttrOccupiedSetbackMin                 uint32 = 0x0035
	AttrOccupiedSetbackMax                 uint32 = 0x0036
	AttrUnoccupiedSetback                  uint32 = 0x0037
	AttrUnoccupiedSetbackMin               uint32 = 0x0038
	AttrUnoccupiedSetbackMax               uint32 = 0x0039
	AttrEmergencyHeatDelta                 uint32 = 0x003A
	AttrACType                             uint32 = 0x0040
	AttrACCapacity                         uint32 = 0x0041
	AttrACRefrigerantType                  uint32 = 0x0042
	AttrACCompressorType                   uint32 = 0x0043
	AttrACErrorCode                        uint32 = 0x0044
	AttrACLouverPosition                   uint32 = 0x0045
	AttrACCoilTemperature                  uint32 = 0x0046
	AttrACCapacityFormat                   uint32 = 0x0047
	AttrPresetTypes                        uint32 = 0x0048
	AttrScheduleTypes                      uint32 = 0x0049
	AttrNumberOfPresets                    uint32 = 0x004A
	AttrNumberOfSchedules                  uint32 = 0x004B
	AttrNumberOfScheduleTransitions        uint32 = 0x004C
	AttrNumberOfScheduleTransitionPerDay   uint32 = 0x004D
	AttrActivePresetHandle                 uint32 = 0x004E
	AttrActiveScheduleHandle               uint32 = 0x004F
	AttrPresets                            uint32 = 0x0050
	AttrSchedules                          uint32 = 0x0051
	AttrSetpointHoldExpiryTimestamp        uint32 = 0x0052
)

// Command IDs.
const (
	CmdSetpointRaiseLower       uint32 = 0x00
	CmdSetActiveScheduleRequest uint32 = 0x05
	CmdSetActivePresetRequest   uint32 = 0x06
)

// SetpointRaiseLowerRequest is the request payload for the SetpointRaiseLower command.
type SetpointRaiseLowerRequest struct {
	Mode   uint8 `tlv:"0,uint"`
	Amount int8  `tlv:"1,int"`
}

// SetActiveScheduleRequestRequest is the request payload for the SetActiveScheduleRequest command.
type SetActiveScheduleRequestRequest struct {
	ScheduleHandle []byte `tlv:"0,bytes"`
}

// SetActivePresetRequestRequest is the request payload for the SetActivePresetRequest command.
type SetActivePresetRequestRequest struct {
	PresetHandle []byte `tlv:"0,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "HEAT", Name: "Heating"},
			{Bit: 1, Code: "COOL", Name: "Cooling"},
			{Bit: 2, Code: "OCC", Name: "Occupancy"},
			{Bit: 4, Code: "SB", Name: "Setback"},
			{Bit: 5, Code: "AUTO", Name: "AutoMode"},
			{Bit: 6, Code: "LTNE", Name: "LocalTemperatureNotExposed"},
			{Bit: 7, Code: "MSCH", Name: "MatterScheduleConfiguration"},
			{Bit: 8, Code: "PRES", Name: "Presets"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrLocalTemperature, Name: "LocalTemperature", DisplayName: "LocalTemperature", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrOutdoorTemperature, Name: "OutdoorTemperature", DisplayName: "OutdoorTemperature", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrOccupancy, Name: "Occupancy", DisplayName: "Occupancy", Type: "bitmap8", Readable: true},
			{ID: AttrAbsMinHeatSetpointLimit, Name: "AbsMinHeatSetpointLimit", DisplayName: "AbsMinHeatSetpointLimit", Type: "int16", Readable: true},
			{ID: AttrAbsMaxHeatSetpointLimit, Name: "AbsMaxHeatSetpointLimit", DisplayName: "AbsMaxHeatSetpointLimit", Type: "int16", Readable: true},
			{ID: AttrAbsMinCoolSetpointLimit, Name: "AbsMinCoolSetpointLimit", DisplayName: "AbsMinCoolSetpointLimit", Type: "int16", Readable: true},
			{ID: AttrAbsMaxCoolSetpointLimit, Name: "AbsMaxCoolSetpointLimit", DisplayName: "AbsMaxCoolSetpointLimit", Type: "int16", Readable: true},
			{ID: AttrPICoolingDemand, Name: "PICoolingDemand", DisplayName: "PICoolingDemand", Type: "uint8", Readable: false},
			{ID: AttrPIHeatingDemand, Name: "PIHeatingDemand", DisplayName: "PIHeatingDemand", Type: "uint8", Readable: false},
			{ID: AttrHVACSystemTypeConfiguration, Name: "HVACSystemTypeConfiguration", DisplayName: "HVACSystemTypeConfiguration", Type: "uint8", Readable: false},
			{ID: AttrLocalTemperatureCalibration, Name: "LocalTemperatureCalibration", DisplayName: "LocalTemperatureCalibration", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrOccupiedCoolingSetpoint, Name: "OccupiedCoolingSetpoint", DisplayName: "OccupiedCoolingSetpoint", Type: "int16", Readable: true, Writable: true},
			{ID: AttrOccupiedHeatingSetpoint, Name: "OccupiedHeatingSetpoint", DisplayName: "OccupiedHeatingSetpoint", Type: "int16", Readable: true, Writable: true},
			{ID: AttrUnoccupiedCoolingSetpoint, Name: "UnoccupiedCoolingSetpoint", DisplayName: "UnoccupiedCoolingSetpoint", Type: "int16", Readable: true, Writable: true},
			{ID: AttrUnoccupiedHeatingSetpoint, Name: "UnoccupiedHeatingSetpoint", DisplayName: "UnoccupiedHeatingSetpoint", Type: "int16", Readable: true, Writable: true},
			{ID: AttrMinHeatSetpointLimit, Name: "MinHeatSetpointLimit", DisplayName: "MinHeatSetpointLimit", Type: "int16", Readable: true, Writable: true},
			{ID: AttrMaxHeatSetpointLimit, Name: "MaxHeatSetpointLimit", DisplayName: "MaxHeatSetpointLimit", Type: "int16", Readable: true, Writable: true},
			{ID: AttrMinCoolSetpointLimit, Name: "MinCoolSetpointLimit", DisplayName: "MinCoolSetpointLimit", Type: "int16", Readable: true, Writable: true},
			{ID: AttrMaxCoolSetpointLimit, Name: "MaxCoolSetpointLimit", DisplayName: "MaxCoolSetpointLimit", Type: "int16", Readable: true, Writable: true},
			{ID: AttrMinSetpointDeadBand, Name: "MinSetpointDeadBand", DisplayName: "MinSetpointDeadBand", Type: "uint8", Readable: true},
			{ID: AttrRemoteSensing, Name: "RemoteSensing", DisplayName: "RemoteSensing", Type: "bitmap8", Readable: true, Writable: true},
			{ID: AttrControlSequenceOfOperation, Name: "ControlSequenceOfOperation", DisplayName: "ControlSequenceOfOperation", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrSystemMode, Name: "SystemMode", DisplayName: "SystemMode", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrThermostatRunningMode, Name: "ThermostatRunningMode", DisplayName: "ThermostatRunningMode", Type: "enum8", Readable: true},
			{ID: AttrTemperatureSetpointHold, Name: "TemperatureSetpointHold", DisplayName: "TemperatureSetpointHold", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrTemperatureSetpointHoldDuration, Name: "TemperatureSetpointHoldDuration", DisplayName: "TemperatureSetpointHoldDuration", Type: "uint16", Readable: true, Writable: true, Nullable: true},
			{ID: AttrThermostatProgrammingOperationMode, Name: "ThermostatProgrammingOperationMode", DisplayName: "ThermostatProgrammingOperationMode", Type: "uint8", Readable: false},
			{ID: AttrThermostatRunningState, Name: "ThermostatRunningState", DisplayName: "ThermostatRunningState", Type: "bitmap8", Readable: true},
			{ID: AttrSetpointChangeSource, Name: "SetpointChangeSource", DisplayName: "SetpointChangeSource", Type: "enum8", Readable: true},
			{ID: AttrSetpointChangeAmount, Name: "SetpointChangeAmount", DisplayName: "SetpointChangeAmount", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrSetpointChangeSourceTimestamp, Name: "SetpointChangeSourceTimestamp", DisplayName: "SetpointChangeSourceTimestamp", Type: "uint32", Readable: true},
			{ID: AttrOccupiedSetback, Name: "OccupiedSetback", DisplayName: "OccupiedSetback", Type: "uint8", Readable: false},
			{ID: AttrOccupiedSetbackMin, Name: "OccupiedSetbackMin", DisplayName: "OccupiedSetbackMin", Type: "uint8", Readable: false},
			{ID: AttrOccupiedSetbackMax, Name: "OccupiedSetbackMax", DisplayName: "OccupiedSetbackMax", Type: "uint8", Readable: false},
			{ID: AttrUnoccupiedSetback, Name: "UnoccupiedSetback", DisplayName: "UnoccupiedSetback", Type: "uint8", Readable: false},
			{ID: AttrUnoccupiedSetbackMin, Name: "UnoccupiedSetbackMin", DisplayName: "UnoccupiedSetbackMin", Type: "uint8", Readable: false},
			{ID: AttrUnoccupiedSetbackMax, Name: "UnoccupiedSetbackMax", DisplayName: "UnoccupiedSetbackMax", Type: "uint8", Readable: false},
			{ID: AttrEmergencyHeatDelta, Name: "EmergencyHeatDelta", DisplayName: "EmergencyHeatDelta", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrACType, Name: "ACType", DisplayName: "ACType", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrACCapacity, Name: "ACCapacity", DisplayName: "ACCapacity", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrACRefrigerantType, Name: "ACRefrigerantType", DisplayName: "ACRefrigerantType", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrACCompressorType, Name: "ACCompressorType", DisplayName: "ACCompressorType", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrACErrorCode, Name: "ACErrorCode", DisplayName: "ACErrorCode", Type: "bitmap8", Readable: true, Writable: true},
			{ID: AttrACLouverPosition, Name: "ACLouverPosition", DisplayName: "ACLouverPosition", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrACCoilTemperature, Name: "ACCoilTemperature", DisplayName: "ACCoilTemperature", Type: "int16", Readable: true, Nullable: true},
			{ID: AttrACCapacityFormat, Name: "ACCapacityFormat", DisplayName: "ACCapacityFormat", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrPresetTypes, Name: "PresetTypes", DisplayName: "PresetTypes", Type: "list", Readable: true},
			{ID: AttrScheduleTypes, Name: "ScheduleTypes", DisplayName: "ScheduleTypes", Type: "list", Readable: true},
			{ID: AttrNumberOfPresets, Name: "NumberOfPresets", DisplayName: "NumberOfPresets", Type: "uint8", Readable: true},
			{ID: AttrNumberOfSchedules, Name: "NumberOfSchedules", DisplayName: "NumberOfSchedules", Type: "uint8", Readable: true},
			{ID: AttrNumberOfScheduleTransitions, Name: "NumberOfScheduleTransitions", DisplayName: "NumberOfScheduleTransitions", Type: "uint8", Readable: true},
			{ID: AttrNumberOfScheduleTransitionPerDay, Name: "NumberOfScheduleTransitionPerDay", DisplayName: "NumberOfScheduleTransitionPerDay", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrActivePresetHandle, Name: "ActivePresetHandle", DisplayName: "ActivePresetHandle", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrActiveScheduleHandle, Name: "ActiveScheduleHandle", DisplayName: "ActiveScheduleHandle", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrPresets, Name: "Presets", DisplayName: "Presets", Type: "list", Readable: true, Writable: true},
			{ID: AttrSchedules, Name: "Schedules", DisplayName: "Schedules", Type: "list", Readable: true, Writable: true},
			{ID: AttrSetpointHoldExpiryTimestamp, Name: "SetpointHoldExpiryTimestamp", DisplayName: "SetpointHoldExpiryTimestamp", Type: "uint32", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSetpointRaiseLower, Name: "SetpointRaiseLower", DisplayName: "SetpointRaiseLower", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Mode", DisplayName: "Mode", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "Heat"}, {Value: 1, Name: "Cool"}, {Value: 2, Name: "Both"}}},
				{ID: 1, Name: "Amount", DisplayName: "Amount", Type: "int8"},
			}},
			{ID: CmdSetActiveScheduleRequest, Name: "SetActiveScheduleRequest", DisplayName: "SetActiveScheduleRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ScheduleHandle", DisplayName: "ScheduleHandle", Type: "octets"},
			}},
			{ID: CmdSetActivePresetRequest, Name: "SetActivePresetRequest", DisplayName: "SetActivePresetRequest", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PresetHandle", DisplayName: "PresetHandle", Type: "octets", Nullable: true},
			}},
		},
	})
}
