// Code generated by cmd/codegen; DO NOT EDIT.

// Package booleanstateconfiguration implements the Matter Boolean State Configuration cluster (0x0080).
package booleanstateconfiguration

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Boolean State Configuration.
	ID uint32 = 0x0080
	// Name is the CLI-friendly cluster name.
	Name = "BooleanStateConfiguration"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Boolean State Configuration"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureVisual           uint32 = 1 << 0 // VIS
	FeatureAudible          uint32 = 1 << 1 // AUD
	FeatureAlarmSuppress    uint32 = 1 << 2 // SPRS
	FeatureSensitivityLevel uint32 = 1 << 3 // SENSLVL
)

// Attribute IDs.
const (
	AttrCurrentSensitivityLevel    uint32 = 0x0000
	AttrSupportedSensitivityLevels uint32 = 0x0001
	AttrDefaultSensitivityLevel    uint32 = 0x0002
	AttrAlarmsActive               uint32 = 0x0003
	AttrAlarmsSuppressed           uint32 = 0x0004
	AttrAlarmsEnabled              uint32 = 0x0005
	AttrAlarmsSupported            uint32 = 0x0006
	AttrSensorFault                uint32 = 0x0007
)

// Command IDs.
const (
	CmdSuppressAlarm      uint32 = 0x00
	CmdEnableDisableAlarm uint32 = 0x01
)

// SuppressAlarmRequest is the request payload for the SuppressAlarm command.
type SuppressAlarmRequest struct {
	AlarmsToSuppress uint8 `tlv:"0,uint"`
}

// EnableDisableAlarmRequest is the request payload for the EnableDisableAlarm command.
type EnableDisableAlarmRequest struct {
	AlarmsToEnableDisable uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "VIS", Name: "Visual"},
			{Bit: 1, Code: "AUD", Name: "Audible"},
			{Bit: 2, Code: "SPRS", Name: "AlarmSuppress"},
			{Bit: 3, Code: "SENSLVL", Name: "SensitivityLevel"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCurrentSensitivityLevel, Name: "CurrentSensitivityLevel", DisplayName: "CurrentSensitivityLevel", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrSupportedSensitivityLevels, Name: "SupportedSensitivityLevels", DisplayName: "SupportedSensitivityLevels", Type: "uint8", Readable: true},
			{ID: AttrDefaultSensitivityLevel, Name: "DefaultSensitivityLevel", DisplayName: "DefaultSensitivityLevel", Type: "uint8", Readable: true},
			{ID: AttrAlarmsActive, Name: "AlarmsActive", DisplayName: "AlarmsActive", Type: "bitmap8", Readable: true},
			{ID: AttrAlarmsSuppressed, Name: "AlarmsSuppressed", DisplayName: "AlarmsSuppressed", Type: "bitmap8", Readable: true},
			{ID: AttrAlarmsEnabled, Name: "AlarmsEnabled", DisplayName: "AlarmsEnabled", Type: "bitmap8", Readable: true},
			{ID: AttrAlarmsSupported, Name: "AlarmsSupported", DisplayName: "AlarmsSupported", Type: "bitmap8", Readable: true},
			{ID: AttrSensorFault, Name: "SensorFault", DisplayName: "SensorFault", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSuppressAlarm, Name: "SuppressAlarm", DisplayName: "SuppressAlarm", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AlarmsToSuppress", DisplayName: "AlarmsToSuppress", Type: "bitmap8"},
			}},
			{ID: CmdEnableDisableAlarm, Name: "EnableDisableAlarm", DisplayName: "EnableDisableAlarm", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AlarmsToEnableDisable", DisplayName: "AlarmsToEnableDisable", Type: "bitmap8"},
			}},
		},
	})
}
