// Code generated by cmd/codegen; DO NOT EDIT.

// Package zonemanagement implements the Matter Zone Management cluster (0x0550).
package zonemanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Zone Management.
	ID uint32 = 0x0550
	// Name is the CLI-friendly cluster name.
	Name = "ZoneManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Zone Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureTwoDimensionalCartesianZone uint32 = 1 << 0 // TWODCART
	FeaturePerZoneSensitivity          uint32 = 1 << 1 // PERZONESENS
	FeatureUserDefined                 uint32 = 1 << 2 // USERDEFINED
	FeatureFocusZones                  uint32 = 1 << 3 // FOCUSZONES
)

// Attribute IDs.
const (
	AttrMaxUserDefinedZones uint32 = 0x0000
	AttrMaxZones            uint32 = 0x0001
	AttrZones               uint32 = 0x0002
	AttrTriggers            uint32 = 0x0003
	AttrSensitivityMax      uint32 = 0x0004
	AttrSensitivity         uint32 = 0x0005
	AttrTwoDCartesianMax    uint32 = 0x0006
)

// Command IDs.
const (
	CmdCreateTwoDCartesianZone uint32 = 0x00
	CmdUpdateTwoDCartesianZone uint32 = 0x02
	CmdRemoveZone              uint32 = 0x03
	CmdCreateOrUpdateTrigger   uint32 = 0x04
	CmdRemoveTrigger           uint32 = 0x05
)

// CreateTwoDCartesianZoneRequest is the request payload for the CreateTwoDCartesianZone command.
type CreateTwoDCartesianZoneRequest struct {
	Zone uint8 `tlv:"0,uint"`
}

// UpdateTwoDCartesianZoneRequest is the request payload for the UpdateTwoDCartesianZone command.
type UpdateTwoDCartesianZoneRequest struct {
	ZoneID uint8 `tlv:"0,uint"`
	Zone   uint8 `tlv:"1,uint"`
}

// RemoveZoneRequest is the request payload for the RemoveZone command.
type RemoveZoneRequest struct {
	ZoneID uint8 `tlv:"0,uint"`
}

// CreateOrUpdateTriggerRequest is the request payload for the CreateOrUpdateTrigger command.
type CreateOrUpdateTriggerRequest struct {
	Trigger uint8 `tlv:"0,uint"`
}

// RemoveTriggerRequest is the request payload for the RemoveTrigger command.
type RemoveTriggerRequest struct {
	ZoneID uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "TWODCART", Name: "TwoDimensionalCartesianZone"},
			{Bit: 1, Code: "PERZONESENS", Name: "PerZoneSensitivity"},
			{Bit: 2, Code: "USERDEFINED", Name: "UserDefined"},
			{Bit: 3, Code: "FOCUSZONES", Name: "FocusZones"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxUserDefinedZones, Name: "MaxUserDefinedZones", DisplayName: "MaxUserDefinedZones", Type: "uint8", Readable: true},
			{ID: AttrMaxZones, Name: "MaxZones", DisplayName: "MaxZones", Type: "uint8", Readable: true},
			{ID: AttrZones, Name: "Zones", DisplayName: "Zones", Type: "list", Readable: true},
			{ID: AttrTriggers, Name: "Triggers", DisplayName: "Triggers", Type: "list", Readable: true},
			{ID: AttrSensitivityMax, Name: "SensitivityMax", DisplayName: "SensitivityMax", Type: "uint8", Readable: true},
			{ID: AttrSensitivity, Name: "Sensitivity", DisplayName: "Sensitivity", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrTwoDCartesianMax, Name: "TwoDCartesianMax", DisplayName: "TwoDCartesianMax", Type: "struct", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdCreateTwoDCartesianZone, Name: "CreateTwoDCartesianZone", DisplayName: "CreateTwoDCartesianZone", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Zone", DisplayName: "Zone", Type: "struct"},
			}},
			{ID: CmdUpdateTwoDCartesianZone, Name: "UpdateTwoDCartesianZone", DisplayName: "UpdateTwoDCartesianZone", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ZoneID", DisplayName: "ZoneID", Type: "uint8"},
				{ID: 1, Name: "Zone", DisplayName: "Zone", Type: "struct"},
			}},
			{ID: CmdRemoveZone, Name: "RemoveZone", DisplayName: "RemoveZone", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ZoneID", DisplayName: "ZoneID", Type: "uint8"},
			}},
			{ID: CmdCreateOrUpdateTrigger, Name: "CreateOrUpdateTrigger", DisplayName: "CreateOrUpdateTrigger", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Trigger", DisplayName: "Trigger", Type: "struct"},
			}},
			{ID: CmdRemoveTrigger, Name: "RemoveTrigger", DisplayName: "RemoveTrigger", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ZoneID", DisplayName: "ZoneID", Type: "uint8"},
			}},
		},
	})
}
