// Code generated by cmd/codegen; DO NOT EDIT.

// Package identify implements the Matter Identify cluster (0x0003).
package identify

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Identify.
	ID uint32 = 0x0003
	// Name is the CLI-friendly cluster name.
	Name = "Identify"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Identify"
)

// Attribute IDs.
const (
	AttrIdentifyTime uint32 = 0x0000
	AttrIdentifyType uint32 = 0x0001
)

// Command IDs.
const (
	CmdIdentify      uint32 = 0x00
	CmdTriggerEffect uint32 = 0x40
)

// IdentifyRequest is the request payload for the Identify command.
type IdentifyRequest struct {
	IdentifyTime uint16 `tlv:"0,uint"`
}

// TriggerEffectRequest is the request payload for the TriggerEffect command.
type TriggerEffectRequest struct {
	EffectIdentifier uint8 `tlv:"0,uint"`
	EffectVariant    uint8 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrIdentifyTime, Name: "IdentifyTime", DisplayName: "IdentifyTime", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrIdentifyType, Name: "IdentifyType", DisplayName: "IdentifyType", Type: "enum8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdIdentify, Name: "Identify", DisplayName: "Identify", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "IdentifyTime", DisplayName: "IdentifyTime", Type: "uint16"},
			}},
			{ID: CmdTriggerEffect, Name: "TriggerEffect", DisplayName: "TriggerEffect", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EffectIdentifier", DisplayName: "EffectIdentifier", Type: "enum8"},
				{ID: 1, Name: "EffectVariant", DisplayName: "EffectVariant", Type: "enum8"},
			}},
		},
	})
}
