// Code generated by cmd/codegen; DO NOT EDIT.

// Package powersource implements the Matter Power Source cluster (0x002F).
package powersource

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Power Source.
	ID uint32 = 0x002F
	// Name is the CLI-friendly cluster name.
	Name = "PowerSource"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Power Source"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureWired        uint32 = 1 << 0 // WIRED
	FeatureBattery      uint32 = 1 << 1 // BAT
	FeatureRechargeable uint32 = 1 << 2 // RECHG
	FeatureReplaceable  uint32 = 1 << 3 // REPLC
)

// Attribute IDs.
const (
	AttrStatus                      uint32 = 0x0000
	AttrOrder                       uint32 = 0x0001
	AttrDescription                 uint32 = 0x0002
	AttrWiredAssessedInputVoltage   uint32 = 0x0003
	AttrWiredAssessedInputFrequency uint32 = 0x0004
	AttrWiredCurrentType            uint32 = 0x0005
	AttrWiredAssessedCurrent        uint32 = 0x0006
	AttrWiredNominalVoltage         uint32 = 0x0007
	AttrWiredMaximumCurrent         uint32 = 0x0008
	AttrWiredPresent                uint32 = 0x0009
	AttrActiveWiredFaults           uint32 = 0x000A
	AttrBatVoltage                  uint32 = 0x000B
	AttrBatPercentRemaining         uint32 = 0x000C
	AttrBatTimeRemaining            uint32 = 0x000D
	AttrBatChargeLevel              uint32 = 0x000E
	AttrBatReplacementNeeded        uint32 = 0x000F
	AttrBatReplaceability           uint32 = 0x0010
	AttrBatPresent                  uint32 = 0x0011
	AttrActiveBatFaults             uint32 = 0x0012
	AttrBatReplacementDescription   uint32 = 0x0013
	AttrBatCommonDesignation        uint32 = 0x0014
	AttrBatANSIDesignation          uint32 = 0x0015
	AttrBatIECDesignation           uint32 = 0x0016
	AttrBatApprovedChemistry        uint32 = 0x0017
	AttrBatCapacity                 uint32 = 0x0018
	AttrBatQuantity                 uint32 = 0x0019
	AttrBatChargeState              uint32 = 0x001A
	AttrBatTimeToFullCharge         uint32 = 0x001B
	AttrBatFunctionalWhileCharging  uint32 = 0x001C
	AttrBatChargingCurrent          uint32 = 0x001D
	AttrActiveBatChargeFaults       uint32 = 0x001E
	AttrEndpointList                uint32 = 0x001F
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "WIRED", Name: "Wired"},
			{Bit: 1, Code: "BAT", Name: "Battery"},
			{Bit: 2, Code: "RECHG", Name: "Rechargeable"},
			{Bit: 3, Code: "REPLC", Name: "Replaceable"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrStatus, Name: "Status", DisplayName: "Status", Type: "enum8", Readable: true},
			{ID: AttrOrder, Name: "Order", DisplayName: "Order", Type: "uint8", Readable: true},
			{ID: AttrDescription, Name: "Description", DisplayName: "Description", Type: "string", Readable: true},
			{ID: AttrWiredAssessedInputVoltage, Name: "WiredAssessedInputVoltage", DisplayName: "WiredAssessedInputVoltage", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrWiredAssessedInputFrequency, Name: "WiredAssessedInputFrequency", DisplayName: "WiredAssessedInputFrequency", Type: "uint16", Readable: true, Nullable: true},
			{ID: AttrWiredCurrentType, Name: "WiredCurrentType", DisplayName: "WiredCurrentType", Type: "enum8", Readable: true},
			{ID: AttrWiredAssessedCurrent, Name: "WiredAssessedCurrent", DisplayName: "WiredAssessedCurrent", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrWiredNominalVoltage, Name: "WiredNominalVoltage", DisplayName: "WiredNominalVoltage", Type: "uint32", Readable: true},
			{ID: AttrWiredMaximumCurrent, Name: "WiredMaximumCurrent", DisplayName: "WiredMaximumCurrent", Type: "uint32", Readable: true},
			{ID: AttrWiredPresent, Name: "WiredPresent", DisplayName: "WiredPresent", Type: "bool", Readable: true},
			{ID: AttrActiveWiredFaults, Name: "ActiveWiredFaults", DisplayName: "ActiveWiredFaults", Type: "list", Readable: true},
			{ID: AttrBatVoltage, Name: "BatVoltage", DisplayName: "BatVoltage", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrBatPercentRemaining, Name: "BatPercentRemaining", DisplayName: "BatPercentRemaining", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrBatTimeRemaining, Name: "BatTimeRemaining", DisplayName: "BatTimeRemaining", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrBatChargeLevel, Name: "BatChargeLevel", DisplayName: "BatChargeLevel", Type: "enum8", Readable: true},
			{ID: AttrBatReplacementNeeded, Name: "BatReplacementNeeded", DisplayName: "BatReplacementNeeded", Type: "bool", Readable: true},
			{ID: AttrBatReplaceability, Name: "BatReplaceability", DisplayName: "BatReplaceability", Type: "enum8", Readable: true},
			{ID: AttrBatPresent, Name: "BatPresent", DisplayName: "BatPresent", Type: "bool", Readable: true},
			{ID: AttrActiveBatFaults, Name: "ActiveBatFaults", DisplayName: "ActiveBatFaults", Type: "list", Readable: true},
			{ID: AttrBatReplacementDescription, Name: "BatReplacementDescription", DisplayName: "BatReplacementDescription", Type: "string", Readable: true},
			{ID: AttrBatCommonDesignation, Name: "BatCommonDesignation", DisplayName: "BatCommonDesignation", Type: "enum8", Readable: true},
			{ID: AttrBatANSIDesignation, Name: "BatANSIDesignation", DisplayName: "BatANSIDesignation", Type: "string", Readable: true},
			{ID: AttrBatIECDesignation, Name: "BatIECDesignation", DisplayName: "BatIECDesignation", Type: "string", Readable: true},
			{ID: AttrBatApprovedChemistry, Name: "BatApprovedChemistry", DisplayName: "BatApprovedChemistry", Type: "enum8", Readable: true},
			{ID: AttrBatCapacity, Name: "BatCapacity", DisplayName: "BatCapacity", Type: "uint32", Readable: true},
			{ID: AttrBatQuantity, Name: "BatQuantity", DisplayName: "BatQuantity", Type: "uint8", Readable: true},
			{ID: AttrBatChargeState, Name: "BatChargeState", DisplayName: "BatChargeState", Type: "enum8", Readable: true},
			{ID: AttrBatTimeToFullCharge, Name: "BatTimeToFullCharge", DisplayName: "BatTimeToFullCharge", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrBatFunctionalWhileCharging, Name: "BatFunctionalWhileCharging", DisplayName: "BatFunctionalWhileCharging", Type: "bool", Readable: true},
			{ID: AttrBatChargingCurrent, Name: "BatChargingCurrent", DisplayName: "BatChargingCurrent", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrActiveBatChargeFaults, Name: "ActiveBatChargeFaults", DisplayName: "ActiveBatChargeFaults", Type: "list", Readable: true},
			{ID: AttrEndpointList, Name: "EndpointList", DisplayName: "EndpointList", Type: "list", Readable: true},
		},
	})
}
