// Code generated by cmd/codegen; DO NOT EDIT.

// Package tlsclientmanagement implements the Matter TLS Client Management cluster (0x0802).
package tlsclientmanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for TLS Client Management.
	ID uint32 = 0x0802
	// Name is the CLI-friendly cluster name.
	Name = "TLSClientManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "TLS Client Management"
)

// Attribute IDs.
const (
	AttrMaxProvisioned       uint32 = 0x0000
	AttrProvisionedEndpoints uint32 = 0x0001
)

// Command IDs.
const (
	CmdProvisionEndpoint uint32 = 0x00
	CmdFindEndpoint      uint32 = 0x02
	CmdRemoveEndpoint    uint32 = 0x04
)

// ProvisionEndpointRequest is the request payload for the ProvisionEndpoint command.
type ProvisionEndpointRequest struct {
	Hostname   []byte `tlv:"0,bytes"`
	Port       uint16 `tlv:"1,uint"`
	CAID       uint8  `tlv:"2,uint"`
	CCDID      uint8  `tlv:"3,uint"`
	EndpointID uint8  `tlv:"4,uint"`
}

// FindEndpointRequest is the request payload for the FindEndpoint command.
type FindEndpointRequest struct {
	EndpointID uint8 `tlv:"0,uint"`
}

// RemoveEndpointRequest is the request payload for the RemoveEndpoint command.
type RemoveEndpointRequest struct {
	EndpointID uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxProvisioned, Name: "MaxProvisioned", DisplayName: "MaxProvisioned", Type: "uint8", Readable: true},
			{ID: AttrProvisionedEndpoints, Name: "ProvisionedEndpoints", DisplayName: "ProvisionedEndpoints", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdProvisionEndpoint, Name: "ProvisionEndpoint", DisplayName: "ProvisionEndpoint", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Hostname", DisplayName: "Hostname", Type: "octets"},
				{ID: 1, Name: "Port", DisplayName: "Port", Type: "uint16"},
				{ID: 2, Name: "CAID", DisplayName: "CAID", Type: "uint8"},
				{ID: 3, Name: "CCDID", DisplayName: "CCDID", Type: "uint8", Nullable: true},
				{ID: 4, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint8", Nullable: true},
			}},
			{ID: CmdFindEndpoint, Name: "FindEndpoint", DisplayName: "FindEndpoint", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint8"},
			}},
			{ID: CmdRemoveEndpoint, Name: "RemoveEndpoint", DisplayName: "RemoveEndpoint", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EndpointID", DisplayName: "EndpointID", Type: "uint8"},
			}},
		},
	})
}
