// Code generated by cmd/codegen; DO NOT EDIT.

// Package otasoftwareupdateprovider implements the Matter OTA Software Update Provider cluster (0x0029).
package otasoftwareupdateprovider

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for OTA Software Update Provider.
	ID uint32 = 0x0029
	// Name is the CLI-friendly cluster name.
	Name = "OTASoftwareUpdateProvider"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "OTA Software Update Provider"
)

// Command IDs.
const (
	CmdQueryImage          uint32 = 0x00
	CmdApplyUpdateRequest  uint32 = 0x02
	CmdNotifyUpdateApplied uint32 = 0x04
)

// QueryImageRequest is the request payload for the QueryImage command.
type QueryImageRequest struct {
	VendorID            uint16 `tlv:"0,uint"`
	ProductID           uint16 `tlv:"1,uint"`
	SoftwareVersion     uint32 `tlv:"2,uint"`
	ProtocolsSupported  uint8  `tlv:"3,uint"`
	HardwareVersion     uint16 `tlv:"4,uint"`
	Location            string `tlv:"5,utf8"`
	RequestorCanConsent bool   `tlv:"6,bool"`
	MetadataForProvider []byte `tlv:"7,bytes"`
}

// ApplyUpdateRequestRequest is the request payload for the ApplyUpdateRequest command.
type ApplyUpdateRequestRequest struct {
	UpdateToken []byte `tlv:"0,bytes"`
	NewVersion  uint32 `tlv:"1,uint"`
}

// NotifyUpdateAppliedRequest is the request payload for the NotifyUpdateApplied command.
type NotifyUpdateAppliedRequest struct {
	UpdateToken     []byte `tlv:"0,bytes"`
	SoftwareVersion uint32 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdQueryImage, Name: "QueryImage", DisplayName: "QueryImage", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VendorID", DisplayName: "VendorID", Type: "uint16"},
				{ID: 1, Name: "ProductID", DisplayName: "ProductID", Type: "uint16"},
				{ID: 2, Name: "SoftwareVersion", DisplayName: "SoftwareVersion", Type: "uint32"},
				{ID: 3, Name: "ProtocolsSupported", DisplayName: "ProtocolsSupported", Type: "list"},
				{ID: 4, Name: "HardwareVersion", DisplayName: "HardwareVersion", Type: "uint16", Optional: true},
				{ID: 5, Name: "Location", DisplayName: "Location", Type: "string", Optional: true},
				{ID: 6, Name: "RequestorCanConsent", DisplayName: "RequestorCanConsent", Type: "bool", Optional: true},
				{ID: 7, Name: "MetadataForProvider", DisplayName: "MetadataForProvider", Type: "octets", Optional: true},
			}},
			{ID: CmdApplyUpdateRequest, Name: "ApplyUpdateRequest", DisplayName: "ApplyUpdateRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UpdateToken", DisplayName: "UpdateToken", Type: "octets"},
				{ID: 1, Name: "NewVersion", DisplayName: "NewVersion", Type: "uint32"},
			}},
			{ID: CmdNotifyUpdateApplied, Name: "NotifyUpdateApplied", DisplayName: "NotifyUpdateApplied", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UpdateToken", DisplayName: "UpdateToken", Type: "octets"},
				{ID: 1, Name: "SoftwareVersion", DisplayName: "SoftwareVersion", Type: "uint32"},
			}},
		},
	})
}
