// Code generated by cmd/codegen; DO NOT EDIT.

// Package electricalpowermeasurement implements the Matter Electrical Power Measurement cluster (0x0090).
package electricalpowermeasurement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Electrical Power Measurement.
	ID uint32 = 0x0090
	// Name is the CLI-friendly cluster name.
	Name = "ElectricalPowerMeasurement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Electrical Power Measurement"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureDirectCurrent      uint32 = 1 << 0 // DIRC
	FeatureAlternatingCurrent uint32 = 1 << 1 // ALTC
	FeaturePolyphasePower     uint32 = 1 << 2 // POLY
	FeatureHarmonics          uint32 = 1 << 3 // HARM
	FeaturePowerQuality       uint32 = 1 << 4 // PWRQ
)

// Attribute IDs.
const (
	AttrPowerMode                uint32 = 0x0000
	AttrNumberOfMeasurementTypes uint32 = 0x0001
	AttrAccuracy                 uint32 = 0x0002
	AttrRanges                   uint32 = 0x0003
	AttrVoltage                  uint32 = 0x0004
	AttrActiveCurrent            uint32 = 0x0005
	AttrReactiveCurrent          uint32 = 0x0006
	AttrApparentCurrent          uint32 = 0x0007
	AttrActivePower              uint32 = 0x0008
	AttrReactivePower            uint32 = 0x0009
	AttrApparentPower            uint32 = 0x000A
	AttrRMSVoltage               uint32 = 0x000B
	AttrRMSCurrent               uint32 = 0x000C
	AttrRMSPower                 uint32 = 0x000D
	AttrFrequency                uint32 = 0x000E
	AttrHarmonicCurrents         uint32 = 0x000F
	AttrHarmonicPhases           uint32 = 0x0010
	AttrPowerFactor              uint32 = 0x0011
	AttrNeutralCurrent           uint32 = 0x0012
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DIRC", Name: "DirectCurrent"},
			{Bit: 1, Code: "ALTC", Name: "AlternatingCurrent"},
			{Bit: 2, Code: "POLY", Name: "PolyphasePower"},
			{Bit: 3, Code: "HARM", Name: "Harmonics"},
			{Bit: 4, Code: "PWRQ", Name: "PowerQuality"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrPowerMode, Name: "PowerMode", DisplayName: "PowerMode", Type: "enum8", Readable: true},
			{ID: AttrNumberOfMeasurementTypes, Name: "NumberOfMeasurementTypes", DisplayName: "NumberOfMeasurementTypes", Type: "uint8", Readable: true},
			{ID: AttrAccuracy, Name: "Accuracy", DisplayName: "Accuracy", Type: "list", Readable: true},
			{ID: AttrRanges, Name: "Ranges", DisplayName: "Ranges", Type: "list", Readable: true},
			{ID: AttrVoltage, Name: "Voltage", DisplayName: "Voltage", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrActiveCurrent, Name: "ActiveCurrent", DisplayName: "ActiveCurrent", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrReactiveCurrent, Name: "ReactiveCurrent", DisplayName: "ReactiveCurrent", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrApparentCurrent, Name: "ApparentCurrent", DisplayName: "ApparentCurrent", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrActivePower, Name: "ActivePower", DisplayName: "ActivePower", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrReactivePower, Name: "ReactivePower", DisplayName: "ReactivePower", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrApparentPower, Name: "ApparentPower", DisplayName: "ApparentPower", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrRMSVoltage, Name: "RMSVoltage", DisplayName: "RMSVoltage", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrRMSCurrent, Name: "RMSCurrent", DisplayName: "RMSCurrent", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrRMSPower, Name: "RMSPower", DisplayName: "RMSPower", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrFrequency, Name: "Frequency", DisplayName: "Frequency", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrHarmonicCurrents, Name: "HarmonicCurrents", DisplayName: "HarmonicCurrents", Type: "list", Readable: true, Nullable: true},
			{ID: AttrHarmonicPhases, Name: "HarmonicPhases", DisplayName: "HarmonicPhases", Type: "list", Readable: true, Nullable: true},
			{ID: AttrPowerFactor, Name: "PowerFactor", DisplayName: "PowerFactor", Type: "int64", Readable: true, Nullable: true},
			{ID: AttrNeutralCurrent, Name: "NeutralCurrent", DisplayName: "NeutralCurrent", Type: "int64", Readable: true, Nullable: true},
		},
	})
}
