// Code generated by cmd/codegen; DO NOT EDIT.

// Package booleanstate implements the Matter Boolean State cluster (0x0045).
package booleanstate

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Boolean State.
	ID uint32 = 0x0045
	// Name is the CLI-friendly cluster name.
	Name = "BooleanState"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Boolean State"
)

// Attribute IDs.
const (
	AttrStateValue uint32 = 0x0000
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrStateValue, Name: "StateValue", DisplayName: "StateValue", Type: "bool", Readable: true},
		},
	})
}
