// Code generated by cmd/codegen; DO NOT EDIT.

// Package applicationbasic implements the Matter Application Basic cluster (0x050D).
package applicationbasic

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Application Basic.
	ID uint32 = 0x050D
	// Name is the CLI-friendly cluster name.
	Name = "ApplicationBasic"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Application Basic"
)

// Attribute IDs.
const (
	AttrVendorName         uint32 = 0x0000
	AttrVendorID           uint32 = 0x0001
	AttrApplicationName    uint32 = 0x0002
	AttrProductID          uint32 = 0x0003
	AttrApplication        uint32 = 0x0004
	AttrStatus             uint32 = 0x0005
	AttrApplicationVersion uint32 = 0x0006
	AttrAllowedVendorList  uint32 = 0x0007
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrVendorName, Name: "VendorName", DisplayName: "VendorName", Type: "string", Readable: true},
			{ID: AttrVendorID, Name: "VendorID", DisplayName: "VendorID", Type: "uint16", Readable: true},
			{ID: AttrApplicationName, Name: "ApplicationName", DisplayName: "ApplicationName", Type: "string", Readable: true},
			{ID: AttrProductID, Name: "ProductID", DisplayName: "ProductID", Type: "uint16", Readable: true},
			{ID: AttrApplication, Name: "Application", DisplayName: "Application", Type: "struct", Readable: true},
			{ID: AttrStatus, Name: "Status", DisplayName: "Status", Type: "enum8", Readable: true},
			{ID: AttrApplicationVersion, Name: "ApplicationVersion", DisplayName: "ApplicationVersion", Type: "string", Readable: true},
			{ID: AttrAllowedVendorList, Name: "AllowedVendorList", DisplayName: "AllowedVendorList", Type: "list", Readable: true},
		},
	})
}
