// Code generated by cmd/codegen; DO NOT EDIT.

// Package actions implements the Matter Actions cluster (0x0025).
package actions

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Actions.
	ID uint32 = 0x0025
	// Name is the CLI-friendly cluster name.
	Name = "Actions"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Actions"
)

// Attribute IDs.
const (
	AttrActionList    uint32 = 0x0000
	AttrEndpointLists uint32 = 0x0001
	AttrSetupURL      uint32 = 0x0002
)

// Command IDs.
const (
	CmdInstantAction               uint32 = 0x00
	CmdInstantActionWithTransition uint32 = 0x01
	CmdStartAction                 uint32 = 0x02
	CmdStartActionWithDuration     uint32 = 0x03
	CmdStopAction                  uint32 = 0x04
	CmdPauseAction                 uint32 = 0x05
	CmdPauseActionWithDuration     uint32 = 0x06
	CmdResumeAction                uint32 = 0x07
	CmdEnableAction                uint32 = 0x08
	CmdEnableActionWithDuration    uint32 = 0x09
	CmdDisableAction               uint32 = 0x0A
	CmdDisableActionWithDuration   uint32 = 0x0B
)

// InstantActionRequest is the request payload for the InstantAction command.
type InstantActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// InstantActionWithTransitionRequest is the request payload for the InstantActionWithTransition command.
type InstantActionWithTransitionRequest struct {
	ActionID       uint16 `tlv:"0,uint"`
	InvokeID       uint32 `tlv:"1,uint"`
	TransitionTime uint16 `tlv:"2,uint"`
}

// StartActionRequest is the request payload for the StartAction command.
type StartActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// StartActionWithDurationRequest is the request payload for the StartActionWithDuration command.
type StartActionWithDurationRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
	Duration uint32 `tlv:"2,uint"`
}

// StopActionRequest is the request payload for the StopAction command.
type StopActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// PauseActionRequest is the request payload for the PauseAction command.
type PauseActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// PauseActionWithDurationRequest is the request payload for the PauseActionWithDuration command.
type PauseActionWithDurationRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
	Duration uint32 `tlv:"2,uint"`
}

// ResumeActionRequest is the request payload for the ResumeAction command.
type ResumeActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// EnableActionRequest is the request payload for the EnableAction command.
type EnableActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// EnableActionWithDurationRequest is the request payload for the EnableActionWithDuration command.
type EnableActionWithDurationRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
	Duration uint32 `tlv:"2,uint"`
}

// DisableActionRequest is the request payload for the DisableAction command.
type DisableActionRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
}

// DisableActionWithDurationRequest is the request payload for the DisableActionWithDuration command.
type DisableActionWithDurationRequest struct {
	ActionID uint16 `tlv:"0,uint"`
	InvokeID uint32 `tlv:"1,uint"`
	Duration uint32 `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrActionList, Name: "ActionList", DisplayName: "ActionList", Type: "list", Readable: true},
			{ID: AttrEndpointLists, Name: "EndpointLists", DisplayName: "EndpointLists", Type: "list", Readable: true},
			{ID: AttrSetupURL, Name: "SetupURL", DisplayName: "SetupURL", Type: "string", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdInstantAction, Name: "InstantAction", DisplayName: "InstantAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdInstantActionWithTransition, Name: "InstantActionWithTransition", DisplayName: "InstantActionWithTransition", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint16"},
			}},
			{ID: CmdStartAction, Name: "StartAction", DisplayName: "StartAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdStartActionWithDuration, Name: "StartActionWithDuration", DisplayName: "StartActionWithDuration", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
				{ID: 2, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
			}},
			{ID: CmdStopAction, Name: "StopAction", DisplayName: "StopAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdPauseAction, Name: "PauseAction", DisplayName: "PauseAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdPauseActionWithDuration, Name: "PauseActionWithDuration", DisplayName: "PauseActionWithDuration", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
				{ID: 2, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
			}},
			{ID: CmdResumeAction, Name: "ResumeAction", DisplayName: "ResumeAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdEnableAction, Name: "EnableAction", DisplayName: "EnableAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdEnableActionWithDuration, Name: "EnableActionWithDuration", DisplayName: "EnableActionWithDuration", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
				{ID: 2, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
			}},
			{ID: CmdDisableAction, Name: "DisableAction", DisplayName: "DisableAction", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
			}},
			{ID: CmdDisableActionWithDuration, Name: "DisableActionWithDuration", DisplayName: "DisableActionWithDuration", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ActionID", DisplayName: "ActionID", Type: "uint16"},
				{ID: 1, Name: "InvokeID", DisplayName: "InvokeID", Type: "uint32", Optional: true},
				{ID: 2, Name: "Duration", DisplayName: "Duration", Type: "uint32"},
			}},
		},
	})
}
