// Code generated by cmd/codegen; DO NOT EDIT.

// Package closuredimension implements the Matter Closure Dimension cluster (0x0105).
package closuredimension

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Closure Dimension.
	ID uint32 = 0x0105
	// Name is the CLI-friendly cluster name.
	Name = "ClosureDimension"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Closure Dimension"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePositioning    uint32 = 1 << 0 // PS
	FeatureMotionLatching uint32 = 1 << 1 // LT
	FeatureUnit           uint32 = 1 << 2 // UT
	FeatureLimitation     uint32 = 1 << 3 // LM
	FeatureSpeed          uint32 = 1 << 4 // SP
	FeatureTranslation    uint32 = 1 << 5 // TR
	FeatureRotation       uint32 = 1 << 6 // RO
	FeatureModulation     uint32 = 1 << 7 // MD
)

// Attribute IDs.
const (
	AttrCurrentState         uint32 = 0x0000
	AttrTargetState          uint32 = 0x0001
	AttrResolution           uint32 = 0x0002
	AttrStepValue            uint32 = 0x0003
	AttrUnit                 uint32 = 0x0004
	AttrUnitRange            uint32 = 0x0005
	AttrLimitRange           uint32 = 0x0006
	AttrTranslationDirection uint32 = 0x0007
	AttrRotationAxis         uint32 = 0x0008
	AttrOverflow             uint32 = 0x0009
	AttrModulationType       uint32 = 0x000A
	AttrLatchControlModes    uint32 = 0x000B
)

// Command IDs.
const (
	CmdSetTarget uint32 = 0x00
	CmdStep      uint32 = 0x01
)

// SetTargetRequest is the request payload for the SetTarget command.
type SetTargetRequest struct {
	Position uint16 `tlv:"0,uint"`
	Latch    bool   `tlv:"1,bool"`
	Speed    uint8  `tlv:"2,uint"`
}

// StepRequest is the request payload for the Step command.
type StepRequest struct {
	Direction     uint8  `tlv:"0,uint"`
	NumberOfSteps uint16 `tlv:"1,uint"`
	Speed         uint8  `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PS", Name: "Positioning"},
			{Bit: 1, Code: "LT", Name: "MotionLatching"},
			{Bit: 2, Code: "UT", Name: "Unit"},
			{Bit: 3, Code: "LM", Name: "Limitation"},
			{Bit: 4, Code: "SP", Name: "Speed"},
			{Bit: 5, Code: "TR", Name: "Translation"},
			{Bit: 6, Code: "RO", Name: "Rotation"},
			{Bit: 7, Code: "MD", Name: "Modulation"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCurrentState, Name: "CurrentState", DisplayName: "CurrentState", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrTargetState, Name: "TargetState", DisplayName: "TargetState", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrResolution, Name: "Resolution", DisplayName: "Resolution", Type: "uint16", Readable: true},
			{ID: AttrStepValue, Name: "StepValue", DisplayName: "StepValue", Type: "uint16", Readable: true},
			{ID: AttrUnit, Name: "Unit", DisplayName: "Unit", Type: "enum8", Readable: true},
			{ID: AttrUnitRange, Name: "UnitRange", DisplayName: "UnitRange", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrLimitRange, Name: "LimitRange", DisplayName: "LimitRange", Type: "struct", Readable: true},
			{ID: AttrTranslationDirection, Name: "TranslationDirection", DisplayName: "TranslationDirection", Type: "enum8", Readable: true},
			{ID: AttrRotationAxis, Name: "RotationAxis", DisplayName: "RotationAxis", Type: "enum8", Readable: true},
			{ID: AttrOverflow, Name: "Overflow", DisplayName: "Overflow", Type: "enum8", Readable: true},
			{ID: AttrModulationType, Name: "ModulationType", DisplayName: "ModulationType", Type: "enum8", Readable: true},
			{ID: AttrLatchControlModes, Name: "LatchControlModes", DisplayName: "LatchControlModes", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSetTarget, Name: "SetTarget", DisplayName: "SetTarget", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Position", DisplayName: "Position", Type: "uint16", Optional: true},
				{ID: 1, Name: "Latch", DisplayName: "Latch", Type: "bool", Optional: true},
				{ID: 2, Name: "Speed", DisplayName: "Speed", Type: "enum8", Optional: true},
			}},
			{ID: CmdStep, Name: "Step", DisplayName: "Step", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Direction", DisplayName: "Direction", Type: "enum8"},
				{ID: 1, Name: "NumberOfSteps", DisplayName: "NumberOfSteps", Type: "uint16"},
				{ID: 2, Name: "Speed", DisplayName: "Speed", Type: "enum8", Optional: true},
			}},
		},
	})
}
