// Code generated by cmd/codegen; DO NOT EDIT.

// Package chime implements the Matter Chime cluster (0x0556).
package chime

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Chime.
	ID uint32 = 0x0556
	// Name is the CLI-friendly cluster name.
	Name = "Chime"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Chime"
)

// Attribute IDs.
const (
	AttrInstalledChimeSounds uint32 = 0x0000
	AttrSelectedChime        uint32 = 0x0001
	AttrEnabled              uint32 = 0x0002
)

// Command IDs.
const (
	CmdPlayChimeSound uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrInstalledChimeSounds, Name: "InstalledChimeSounds", DisplayName: "InstalledChimeSounds", Type: "list", Readable: true},
			{ID: AttrSelectedChime, Name: "SelectedChime", DisplayName: "SelectedChime", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrEnabled, Name: "Enabled", DisplayName: "Enabled", Type: "bool", Readable: true, Writable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdPlayChimeSound, Name: "PlayChimeSound", DisplayName: "PlayChimeSound", HasResponse: true},
		},
	})
}
