// Code generated by cmd/codegen; DO NOT EDIT.

// Package tlscertificatemanagement implements the Matter TLS Certificate Management cluster (0x0801).
package tlscertificatemanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for TLS Certificate Management.
	ID uint32 = 0x0801
	// Name is the CLI-friendly cluster name.
	Name = "TLSCertificateManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "TLS Certificate Management"
)

// Attribute IDs.
const (
	AttrMaxRootCertificates           uint32 = 0x0000
	AttrProvisionedRootCertificates   uint32 = 0x0001
	AttrMaxClientCertificates         uint32 = 0x0002
	AttrProvisionedClientCertificates uint32 = 0x0003
)

// Command IDs.
const (
	CmdProvisionRootCertificate   uint32 = 0x00
	CmdFindRootCertificate        uint32 = 0x02
	CmdLookupRootCertificate      uint32 = 0x04
	CmdRemoveRootCertificate      uint32 = 0x06
	CmdClientCSR                  uint32 = 0x07
	CmdProvisionClientCertificate uint32 = 0x09
	CmdFindClientCertificate      uint32 = 0x0A
	CmdLookupClientCertificate    uint32 = 0x0C
	CmdRemoveClientCertificate    uint32 = 0x0E
)

// ProvisionRootCertificateRequest is the request payload for the ProvisionRootCertificate command.
type ProvisionRootCertificateRequest struct {
	Certificate []byte `tlv:"0,bytes"`
	CAID        uint8  `tlv:"1,uint"`
}

// FindRootCertificateRequest is the request payload for the FindRootCertificate command.
type FindRootCertificateRequest struct {
	CAID uint8 `tlv:"0,uint"`
}

// LookupRootCertificateRequest is the request payload for the LookupRootCertificate command.
type LookupRootCertificateRequest struct {
	Fingerprint []byte `tlv:"0,bytes"`
}

// RemoveRootCertificateRequest is the request payload for the RemoveRootCertificate command.
type RemoveRootCertificateRequest struct {
	CAID uint8 `tlv:"0,uint"`
}

// ClientCSRRequest is the request payload for the ClientCSR command.
type ClientCSRRequest struct {
	Nonce []byte `tlv:"0,bytes"`
	CCDID uint8  `tlv:"1,uint"`
}

// ProvisionClientCertificateRequest is the request payload for the ProvisionClientCertificate command.
type ProvisionClientCertificateRequest struct {
	CCDID                    uint8  `tlv:"0,uint"`
	ClientCertificate        []byte `tlv:"1,bytes"`
	IntermediateCertificates uint8  `tlv:"2,uint"`
}

// FindClientCertificateRequest is the request payload for the FindClientCertificate command.
type FindClientCertificateRequest struct {
	CCDID uint8 `tlv:"0,uint"`
}

// LookupClientCertificateRequest is the request payload for the LookupClientCertificate command.
type LookupClientCertificateRequest struct {
	Fingerprint []byte `tlv:"0,bytes"`
}

// RemoveClientCertificateRequest is the request payload for the RemoveClientCertificate command.
type RemoveClientCertificateRequest struct {
	CCDID uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxRootCertificates, Name: "MaxRootCertificates", DisplayName: "MaxRootCertificates", Type: "uint8", Readable: true},
			{ID: AttrProvisionedRootCertificates, Name: "ProvisionedRootCertificates", DisplayName: "ProvisionedRootCertificates", Type: "list", Readable: true},
			{ID: AttrMaxClientCertificates, Name: "MaxClientCertificates", DisplayName: "MaxClientCertificates", Type: "uint8", Readable: true},
			{ID: AttrProvisionedClientCertificates, Name: "ProvisionedClientCertificates", DisplayName: "ProvisionedClientCertificates", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdProvisionRootCertificate, Name: "ProvisionRootCertificate", DisplayName: "ProvisionRootCertificate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Certificate", DisplayName: "Certificate", Type: "octets"},
				{ID: 1, Name: "CAID", DisplayName: "CAID", Type: "uint8", Nullable: true},
			}},
			{ID: CmdFindRootCertificate, Name: "FindRootCertificate", DisplayName: "FindRootCertificate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CAID", DisplayName: "CAID", Type: "uint8", Nullable: true},
			}},
			{ID: CmdLookupRootCertificate, Name: "LookupRootCertificate", DisplayName: "LookupRootCertificate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Fingerprint", DisplayName: "Fingerprint", Type: "octets"},
			}},
			{ID: CmdRemoveRootCertificate, Name: "RemoveRootCertificate", DisplayName: "RemoveRootCertificate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CAID", DisplayName: "CAID", Type: "uint8"},
			}},
			{ID: CmdClientCSR, Name: "ClientCSR", DisplayName: "ClientCSR", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Nonce", DisplayName: "Nonce", Type: "octets"},
				{ID: 1, Name: "CCDID", DisplayName: "CCDID", Type: "uint8", Nullable: true},
			}},
			{ID: CmdProvisionClientCertificate, Name: "ProvisionClientCertificate", DisplayName: "ProvisionClientCertificate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CCDID", DisplayName: "CCDID", Type: "uint8"},
				{ID: 1, Name: "ClientCertificate", DisplayName: "ClientCertificate", Type: "octets"},
				{ID: 2, Name: "IntermediateCertificates", DisplayName: "IntermediateCertificates", Type: "list"},
			}},
			{ID: CmdFindClientCertificate, Name: "FindClientCertificate", DisplayName: "FindClientCertificate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CCDID", DisplayName: "CCDID", Type: "uint8", Nullable: true},
			}},
			{ID: CmdLookupClientCertificate, Name: "LookupClientCertificate", DisplayName: "LookupClientCertificate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Fingerprint", DisplayName: "Fingerprint", Type: "octets"},
			}},
			{ID: CmdRemoveClientCertificate, Name: "RemoveClientCertificate", DisplayName: "RemoveClientCertificate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CCDID", DisplayName: "CCDID", Type: "uint8"},
			}},
		},
	})
}
