// Code generated by cmd/codegen; DO NOT EDIT.

// Package doorlock implements the Matter Door Lock cluster (0x0101).
package doorlock

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Door Lock.
	ID uint32 = 0x0101
	// Name is the CLI-friendly cluster name.
	Name = "DoorLock"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Door Lock"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePINCredential              uint32 = 1 << 0  // PIN
	FeatureRFIDCredential             uint32 = 1 << 1  // RID
	FeatureFingerCredentials          uint32 = 1 << 2  // FGP
	FeatureWeekDayAccessSchedules     uint32 = 1 << 4  // WDSCH
	FeatureDoorPositionSensor         uint32 = 1 << 5  // DPS
	FeatureFaceCredentials            uint32 = 1 << 6  // FACE
	FeatureCredentialOverTheAirAccess uint32 = 1 << 7  // COTA
	FeatureUser                       uint32 = 1 << 8  // USR
	FeatureYearDayAccessSchedules     uint32 = 1 << 10 // YDSCH
	FeatureHolidaySchedules           uint32 = 1 << 11 // HDSCH
	FeatureUnbolting                  uint32 = 1 << 12 // UBOLT
	FeatureAliroProvisioning          uint32 = 1 << 13 // ALIRO
	FeatureAliroBLEUWB                uint32 = 1 << 14 // ALBU
)

// Attribute IDs.
const (
	AttrLockState                                          uint32 = 0x0000
	AttrLockType                                           uint32 = 0x0001
	AttrActuatorEnabled                                    uint32 = 0x0002
	AttrDoorState                                          uint32 = 0x0003
	AttrDoorOpenEvents                                     uint32 = 0x0004
	AttrDoorClosedEvents                                   uint32 = 0x0005
	AttrOpenPeriod                                         uint32 = 0x0006
	AttrNumberOfTotalUsersSupported                        uint32 = 0x0011
	AttrNumberOfPINUsersSupported                          uint32 = 0x0012
	AttrNumberOfRFIDUsersSupported                         uint32 = 0x0013
	AttrNumberOfWeekDaySchedulesSupportedPerUser           uint32 = 0x0014
	AttrNumberOfYearDaySchedulesSupportedPerUser           uint32 = 0x0015
	AttrNumberOfHolidaySchedulesSupported                  uint32 = 0x0016
	AttrMaxPINCodeLength                                   uint32 = 0x0017
	AttrMinPINCodeLength                                   uint32 = 0x0018
	AttrMaxRFIDCodeLength                                  uint32 = 0x0019
	AttrMinRFIDCodeLength                                  uint32 = 0x001A
	AttrCredentialRulesSupport                             uint32 = 0x001B
	AttrNumberOfCredentialsSupportedPerUser                uint32 = 0x001C
	AttrLanguage                                           uint32 = 0x0021
	AttrLEDSettings                                        uint32 = 0x0022
	AttrAutoRelockTime                                     uint32 = 0x0023
	AttrSoundVolume                                        uint32 = 0x0024
	AttrOperatingMode                                      uint32 = 0x0025
	AttrSupportedOperatingModes                            uint32 = 0x0026
	AttrDefaultConfigurationRegister                       uint32 = 0x0027
	AttrEnableLocalProgramming                             uint32 = 0x0028
	AttrEnableOneTouchLocking                              uint32 = 0x0029
	AttrEnableInsideStatusLED                              uint32 = 0x002A
	AttrEnablePrivacyModeButton                            uint32 = 0x002B
	AttrLocalProgrammingFeatures                           uint32 = 0x002C
	AttrWrongCodeEntryLimit                                uint32 = 0x0030
	AttrUserCodeTemporaryDisableTime                       uint32 = 0x0031
	AttrSendPINOverTheAir                                  uint32 = 0x0032
	AttrRequirePINforRemoteOperation                       uint32 = 0x0033
	AttrSecurityLevel                                      uint32 = 0x0034
	AttrExpiringUserTimeout                                uint32 = 0x0035
	AttrAliroReaderVerificationKey                         uint32 = 0x0080
	AttrAliroReaderGroupIdentifier                         uint32 = 0x0081
	AttrAliroReaderGroupSubIdentifier                      uint32 = 0x0082
	AttrAliroExpeditedTransactionSupportedProtocolVersions uint32 = 0x0083
	AttrAliroGroupResolvingKey                             uint32 = 0x0084
	AttrAliroSupportedBLEUWBProtocolVersions               uint32 = 0x0085
	AttrAliroBLEAdvertisingVersion                         uint32 = 0x0086
	AttrNumberOfAliroCredentialIssuerKeysSupported         uint32 = 0x0087
	AttrNumberOfAliroEndpointKeysSupported                 uint32 = 0x0088
)

// Command IDs.
const (
	CmdLockDoor               uint32 = 0x00
	CmdUnlockDoor             uint32 = 0x01
	CmdToggle                 uint32 = 0x02
	CmdUnlockWithTimeout      uint32 = 0x03
	CmdSetWeekDaySchedule     uint32 = 0x0B
	CmdGetWeekDaySchedule     uint32 = 0x0C
	CmdClearWeekDaySchedule   uint32 = 0x0D
	CmdSetYearDaySchedule     uint32 = 0x0E
	CmdGetYearDaySchedule     uint32 = 0x0F
	CmdClearYearDaySchedule   uint32 = 0x10
	CmdSetHolidaySchedule     uint32 = 0x11
	CmdGetHolidaySchedule     uint32 = 0x12
	CmdClearHolidaySchedule   uint32 = 0x13
	CmdSetUser                uint32 = 0x1A
	CmdGetUser                uint32 = 0x1B
	CmdClearUser              uint32 = 0x1D
	CmdSetCredential          uint32 = 0x22
	CmdGetCredentialStatus    uint32 = 0x24
	CmdClearCredential        uint32 = 0x26
	CmdUnboltDoor             uint32 = 0x27
	CmdSetAliroReaderConfig   uint32 = 0x28
	CmdClearAliroReaderConfig uint32 = 0x29
)

// LockDoorRequest is the request payload for the LockDoor command.
type LockDoorRequest struct {
	PINCode []byte `tlv:"0,bytes"`
}

// UnlockDoorRequest is the request payload for the UnlockDoor command.
type UnlockDoorRequest struct {
	PINCode []byte `tlv:"0,bytes"`
}

// UnlockWithTimeoutRequest is the request payload for the UnlockWithTimeout command.
type UnlockWithTimeoutRequest struct {
	Timeout uint16 `tlv:"0,uint"`
	PINCode []byte `tlv:"1,bytes"`
}

// SetWeekDayScheduleRequest is the request payload for the SetWeekDaySchedule command.
type SetWeekDayScheduleRequest struct {
	WeekDayIndex uint8  `tlv:"0,uint"`
	UserIndex    uint16 `tlv:"1,uint"`
	DaysMask     uint8  `tlv:"2,uint"`
	StartHour    uint8  `tlv:"3,uint"`
	StartMinute  uint8  `tlv:"4,uint"`
	EndHour      uint8  `tlv:"5,uint"`
	EndMinute    uint8  `tlv:"6,uint"`
}

// GetWeekDayScheduleRequest is the request payload for the GetWeekDaySchedule command.
type GetWeekDayScheduleRequest struct {
	WeekDayIndex uint8  `tlv:"0,uint"`
	UserIndex    uint16 `tlv:"1,uint"`
}

// ClearWeekDayScheduleRequest is the request payload for the ClearWeekDaySchedule command.
type ClearWeekDayScheduleRequest struct {
	WeekDayIndex uint8  `tlv:"0,uint"`
	UserIndex    uint16 `tlv:"1,uint"`
}

// SetYearDayScheduleRequest is the request payload for the SetYearDaySchedule command.
type SetYearDayScheduleRequest struct {
	YearDayIndex   uint8  `tlv:"0,uint"`
	UserIndex      uint16 `tlv:"1,uint"`
	LocalStartTime uint32 `tlv:"2,uint"`
	LocalEndTime   uint32 `tlv:"3,uint"`
}

// GetYearDayScheduleRequest is the request payload for the GetYearDaySchedule command.
type GetYearDayScheduleRequest struct {
	YearDayIndex uint8  `tlv:"0,uint"`
	UserIndex    uint16 `tlv:"1,uint"`
}

// ClearYearDayScheduleRequest is the request payload for the ClearYearDaySchedule command.
type ClearYearDayScheduleRequest struct {
	YearDayIndex uint8  `tlv:"0,uint"`
	UserIndex    uint16 `tlv:"1,uint"`
}

// SetHolidayScheduleRequest is the request payload for the SetHolidaySchedule command.
type SetHolidayScheduleRequest struct {
	HolidayIndex   uint8  `tlv:"0,uint"`
	LocalStartTime uint32 `tlv:"1,uint"`
	LocalEndTime   uint32 `tlv:"2,uint"`
	OperatingMode  uint8  `tlv:"3,uint"`
}

// GetHolidayScheduleRequest is the request payload for the GetHolidaySchedule command.
type GetHolidayScheduleRequest struct {
	HolidayIndex uint8 `tlv:"0,uint"`
}

// ClearHolidayScheduleRequest is the request payload for the ClearHolidaySchedule command.
type ClearHolidayScheduleRequest struct {
	HolidayIndex uint8 `tlv:"0,uint"`
}

// SetUserRequest is the request payload for the SetUser command.
type SetUserRequest struct {
	OperationType  uint8  `tlv:"0,uint"`
	UserIndex      uint16 `tlv:"1,uint"`
	UserName       string `tlv:"2,utf8"`
	UserUniqueID   uint32 `tlv:"3,uint"`
	UserStatus     uint8  `tlv:"4,uint"`
	UserType       uint8  `tlv:"5,uint"`
	CredentialRule uint8  `tlv:"6,uint"`
}

// GetUserRequest is the request payload for the GetUser command.
type GetUserRequest struct {
	UserIndex uint16 `tlv:"0,uint"`
}

// ClearUserRequest is the request payload for the ClearUser command.
type ClearUserRequest struct {
	UserIndex uint16 `tlv:"0,uint"`
}

// SetCredentialRequest is the request payload for the SetCredential command.
type SetCredentialRequest struct {
	OperationType  uint8  `tlv:"0,uint"`
	Credential     uint8  `tlv:"1,uint"`
	CredentialData []byte `tlv:"2,bytes"`
	UserIndex      uint16 `tlv:"3,uint"`
	UserStatus     uint8  `tlv:"4,uint"`
	UserType       uint8  `tlv:"5,uint"`
}

// GetCredentialStatusRequest is the request payload for the GetCredentialStatus command.
type GetCredentialStatusRequest struct {
	Credential uint8 `tlv:"0,uint"`
}

// ClearCredentialRequest is the request payload for the ClearCredential command.
type ClearCredentialRequest struct {
	Credential uint8 `tlv:"0,uint"`
}

// UnboltDoorRequest is the request payload for the UnboltDoor command.
type UnboltDoorRequest struct {
	PINCode []byte `tlv:"0,bytes"`
}

// SetAliroReaderConfigRequest is the request payload for the SetAliroReaderConfig command.
type SetAliroReaderConfigRequest struct {
	SigningKey        []byte `tlv:"0,bytes"`
	VerificationKey   []byte `tlv:"1,bytes"`
	GroupIdentifier   []byte `tlv:"2,bytes"`
	GroupResolvingKey []byte `tlv:"3,bytes"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PIN", Name: "PINCredential"},
			{Bit: 1, Code: "RID", Name: "RFIDCredential"},
			{Bit: 2, Code: "FGP", Name: "FingerCredentials"},
			{Bit: 4, Code: "WDSCH", Name: "WeekDayAccessSchedules"},
			{Bit: 5, Code: "DPS", Name: "DoorPositionSensor"},
			{Bit: 6, Code: "FACE", Name: "FaceCredentials"},
			{Bit: 7, Code: "COTA", Name: "CredentialOverTheAirAccess"},
			{Bit: 8, Code: "USR", Name: "User"},
			{Bit: 10, Code: "YDSCH", Name: "YearDayAccessSchedules"},
			{Bit: 11, Code: "HDSCH", Name: "HolidaySchedules"},
			{Bit: 12, Code: "UBOLT", Name: "Unbolting"},
			{Bit: 13, Code: "ALIRO", Name: "AliroProvisioning"},
			{Bit: 14, Code: "ALBU", Name: "AliroBLEUWB"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrLockState, Name: "LockState", DisplayName: "LockState", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrLockType, Name: "LockType", DisplayName: "LockType", Type: "enum8", Readable: true},
			{ID: AttrActuatorEnabled, Name: "ActuatorEnabled", DisplayName: "ActuatorEnabled", Type: "bool", Readable: true},
			{ID: AttrDoorState, Name: "DoorState", DisplayName: "DoorState", Type: "enum8", Readable: true, Nullable: true},
			{ID: AttrDoorOpenEvents, Name: "DoorOpenEvents", DisplayName: "DoorOpenEvents", Type: "uint32", Readable: true, Writable: true},
			{ID: AttrDoorClosedEvents, Name: "DoorClosedEvents", DisplayName: "DoorClosedEvents", Type: "uint32", Readable: true, Writable: true},
			{ID: AttrOpenPeriod, Name: "OpenPeriod", DisplayName: "OpenPeriod", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrNumberOfTotalUsersSupported, Name: "NumberOfTotalUsersSupported", DisplayName: "NumberOfTotalUsersSupported", Type: "uint16", Readable: true},
			{ID: AttrNumberOfPINUsersSupported, Name: "NumberOfPINUsersSupported", DisplayName: "NumberOfPINUsersSupported", Type: "uint16", Readable: true},
			{ID: AttrNumberOfRFIDUsersSupported, Name: "NumberOfRFIDUsersSupported", DisplayName: "NumberOfRFIDUsersSupported", Type: "uint16", Readable: true},
			{ID: AttrNumberOfWeekDaySchedulesSupportedPerUser, Name: "NumberOfWeekDaySchedulesSupportedPerUser", DisplayName: "NumberOfWeekDaySchedulesSupportedPerUser", Type: "uint8", Readable: true},
			{ID: AttrNumberOfYearDaySchedulesSupportedPerUser, Name: "NumberOfYearDaySchedulesSupportedPerUser", DisplayName: "NumberOfYearDaySchedulesSupportedPerUser", Type: "uint8", Readable: true},
			{ID: AttrNumberOfHolidaySchedulesSupported, Name: "NumberOfHolidaySchedulesSupported", DisplayName: "NumberOfHolidaySchedulesSupported", Type: "uint8", Readable: true},
			{ID: AttrMaxPINCodeLength, Name: "MaxPINCodeLength", DisplayName: "MaxPINCodeLength", Type: "uint8", Readable: true},
			{ID: AttrMinPINCodeLength, Name: "MinPINCodeLength", DisplayName: "MinPINCodeLength", Type: "uint8", Readable: true},
			{ID: AttrMaxRFIDCodeLength, Name: "MaxRFIDCodeLength", DisplayName: "MaxRFIDCodeLength", Type: "uint8", Readable: true},
			{ID: AttrMinRFIDCodeLength, Name: "MinRFIDCodeLength", DisplayName: "MinRFIDCodeLength", Type: "uint8", Readable: true},
			{ID: AttrCredentialRulesSupport, Name: "CredentialRulesSupport", DisplayName: "CredentialRulesSupport", Type: "bitmap8", Readable: true},
			{ID: AttrNumberOfCredentialsSupportedPerUser, Name: "NumberOfCredentialsSupportedPerUser", DisplayName: "NumberOfCredentialsSupportedPerUser", Type: "uint8", Readable: true},
			{ID: AttrLanguage, Name: "Language", DisplayName: "Language", Type: "string", Readable: true},
			{ID: AttrLEDSettings, Name: "LEDSettings", DisplayName: "LEDSettings", Type: "enum8", Readable: true},
			{ID: AttrAutoRelockTime, Name: "AutoRelockTime", DisplayName: "AutoRelockTime", Type: "uint32", Readable: true},
			{ID: AttrSoundVolume, Name: "SoundVolume", DisplayName: "SoundVolume", Type: "enum8", Readable: true},
			{ID: AttrOperatingMode, Name: "OperatingMode", DisplayName: "OperatingMode", Type: "enum8", Readable: true},
			{ID: AttrSupportedOperatingModes, Name: "SupportedOperatingModes", DisplayName: "SupportedOperatingModes", Type: "bitmap8", Readable: true},
			{ID: AttrDefaultConfigurationRegister, Name: "DefaultConfigurationRegister", DisplayName: "DefaultConfigurationRegister", Type: "bitmap8", Readable: true},
			{ID: AttrEnableLocalProgramming, Name: "EnableLocalProgramming", DisplayName: "EnableLocalProgramming", Type: "bool", Readable: true},
			{ID: AttrEnableOneTouchLocking, Name: "EnableOneTouchLocking", DisplayName: "EnableOneTouchLocking", Type: "bool", Readable: true, Writable: true},
			{ID: AttrEnableInsideStatusLED, Name: "EnableInsideStatusLED", DisplayName: "EnableInsideStatusLED", Type: "bool", Readable: true, Writable: true},
			{ID: AttrEnablePrivacyModeButton, Name: "EnablePrivacyModeButton", DisplayName: "EnablePrivacyModeButton", Type: "bool", Readable: true, Writable: true},
			{ID: AttrLocalProgrammingFeatures, Name: "LocalProgrammingFeatures", DisplayName: "LocalProgrammingFeatures", Type: "bitmap8", Readable: true},
			{ID: AttrWrongCodeEntryLimit, Name: "WrongCodeEntryLimit", DisplayName: "WrongCodeEntryLimit", Type: "uint8", Readable: true},
			{ID: AttrUserCodeTemporaryDisableTime, Name: "UserCodeTemporaryDisableTime", DisplayName: "UserCodeTemporaryDisableTime", Type: "uint8", Readable: true},
			{ID: AttrSendPINOverTheAir, Name: "SendPINOverTheAir", DisplayName: "SendPINOverTheAir", Type: "bool", Readable: true},
			{ID: AttrRequirePINforRemoteOperation, Name: "RequirePINforRemoteOperation", DisplayName: "RequirePINforRemoteOperation", Type: "bool", Readable: true},
			{ID: AttrSecurityLevel, Name: "SecurityLevel", DisplayName: "SecurityLevel", Type: "uint8", Readable: true},
			{ID: AttrExpiringUserTimeout, Name: "ExpiringUserTimeout", DisplayName: "ExpiringUserTimeout", Type: "uint16", Readable: true},
			{ID: AttrAliroReaderVerificationKey, Name: "AliroReaderVerificationKey", DisplayName: "AliroReaderVerificationKey", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrAliroReaderGroupIdentifier, Name: "AliroReaderGroupIdentifier", DisplayName: "AliroReaderGroupIdentifier", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrAliroReaderGroupSubIdentifier, Name: "AliroReaderGroupSubIdentifier", DisplayName: "AliroReaderGroupSubIdentifier", Type: "octets", Readable: true},
			{ID: AttrAliroExpeditedTransactionSupportedProtocolVersions, Name: "AliroExpeditedTransactionSupportedProtocolVersions", DisplayName: "AliroExpeditedTransactionSupportedProtocolVersions", Type: "list", Readable: true},
			{ID: AttrAliroGroupResolvingKey, Name: "AliroGroupResolvingKey", DisplayName: "AliroGroupResolvingKey", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrAliroSupportedBLEUWBProtocolVersions, Name: "AliroSupportedBLEUWBProtocolVersions", DisplayName: "AliroSupportedBLEUWBProtocolVersions", Type: "list", Readable: true},
			{ID: AttrAliroBLEAdvertisingVersion, Name: "AliroBLEAdvertisingVersion", DisplayName: "AliroBLEAdvertisingVersion", Type: "uint8", Readable: true},
			{ID: AttrNumberOfAliroCredentialIssuerKeysSupported, Name: "NumberOfAliroCredentialIssuerKeysSupported", DisplayName: "NumberOfAliroCredentialIssuerKeysSupported", Type: "uint16", Readable: true},
			{ID: AttrNumberOfAliroEndpointKeysSupported, Name: "NumberOfAliroEndpointKeysSupported", DisplayName: "NumberOfAliroEndpointKeysSupported", Type: "uint16", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdLockDoor, Name: "LockDoor", DisplayName: "LockDoor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PINCode", DisplayName: "PINCode", Type: "octets", Optional: true},
			}},
			{ID: CmdUnlockDoor, Name: "UnlockDoor", DisplayName: "UnlockDoor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PINCode", DisplayName: "PINCode", Type: "octets", Optional: true},
			}},
			{ID: CmdToggle, Name: "Toggle", DisplayName: "Toggle"},
			{ID: CmdUnlockWithTimeout, Name: "UnlockWithTimeout", DisplayName: "UnlockWithTimeout", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Timeout", DisplayName: "Timeout", Type: "uint16"},
				{ID: 1, Name: "PINCode", DisplayName: "PINCode", Type: "octets", Optional: true},
			}},
			{ID: CmdSetWeekDaySchedule, Name: "SetWeekDaySchedule", DisplayName: "SetWeekDaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WeekDayIndex", DisplayName: "WeekDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
				{ID: 2, Name: "DaysMask", DisplayName: "DaysMask", Type: "bitmap8"},
				{ID: 3, Name: "StartHour", DisplayName: "StartHour", Type: "uint8"},
				{ID: 4, Name: "StartMinute", DisplayName: "StartMinute", Type: "uint8"},
				{ID: 5, Name: "EndHour", DisplayName: "EndHour", Type: "uint8"},
				{ID: 6, Name: "EndMinute", DisplayName: "EndMinute", Type: "uint8"},
			}},
			{ID: CmdGetWeekDaySchedule, Name: "GetWeekDaySchedule", DisplayName: "GetWeekDaySchedule", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WeekDayIndex", DisplayName: "WeekDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdClearWeekDaySchedule, Name: "ClearWeekDaySchedule", DisplayName: "ClearWeekDaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "WeekDayIndex", DisplayName: "WeekDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdSetYearDaySchedule, Name: "SetYearDaySchedule", DisplayName: "SetYearDaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "YearDayIndex", DisplayName: "YearDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
				{ID: 2, Name: "LocalStartTime", DisplayName: "LocalStartTime", Type: "uint32"},
				{ID: 3, Name: "LocalEndTime", DisplayName: "LocalEndTime", Type: "uint32"},
			}},
			{ID: CmdGetYearDaySchedule, Name: "GetYearDaySchedule", DisplayName: "GetYearDaySchedule", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "YearDayIndex", DisplayName: "YearDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdClearYearDaySchedule, Name: "ClearYearDaySchedule", DisplayName: "ClearYearDaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "YearDayIndex", DisplayName: "YearDayIndex", Type: "uint8"},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdSetHolidaySchedule, Name: "SetHolidaySchedule", DisplayName: "SetHolidaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "HolidayIndex", DisplayName: "HolidayIndex", Type: "uint8"},
				{ID: 1, Name: "LocalStartTime", DisplayName: "LocalStartTime", Type: "uint32"},
				{ID: 2, Name: "LocalEndTime", DisplayName: "LocalEndTime", Type: "uint32"},
				{ID: 3, Name: "OperatingMode", DisplayName: "OperatingMode", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "Normal"}, {Value: 1, Name: "Vacation"}, {Value: 2, Name: "Privacy"}, {Value: 3, Name: "NoRemoteLockUnlock"}, {Value: 4, Name: "Passage"}}},
			}},
			{ID: CmdGetHolidaySchedule, Name: "GetHolidaySchedule", DisplayName: "GetHolidaySchedule", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "HolidayIndex", DisplayName: "HolidayIndex", Type: "uint8"},
			}},
			{ID: CmdClearHolidaySchedule, Name: "ClearHolidaySchedule", DisplayName: "ClearHolidaySchedule", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "HolidayIndex", DisplayName: "HolidayIndex", Type: "uint8"},
			}},
			{ID: CmdSetUser, Name: "SetUser", DisplayName: "SetUser", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OperationType", DisplayName: "OperationType", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "Add"}, {Value: 1, Name: "Clear"}, {Value: 2, Name: "Modify"}}},
				{ID: 1, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
				{ID: 2, Name: "UserName", DisplayName: "UserName", Type: "string", Nullable: true},
				{ID: 3, Name: "UserUniqueID", DisplayName: "UserUniqueID", Type: "uint32", Nullable: true},
				{ID: 4, Name: "UserStatus", DisplayName: "UserStatus", Type: "enum8", Nullable: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "Available"}, {Value: 1, Name: "OccupiedEnabled"}, {Value: 3, Name: "OccupiedDisabled"}}},
				{ID: 5, Name: "UserType", DisplayName: "UserType", Type: "enum8", Nullable: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "UnrestrictedUser"}, {Value: 1, Name: "YearDayScheduleUser"}, {Value: 2, Name: "WeekDayScheduleUser"}, {Value: 3, Name: "ProgrammingUser"}, {Value: 4, Name: "NonAccessUser"}, {Value: 5, Name: "ForcedUser"}, {Value: 6, Name: "DisposableUser"}, {Value: 7, Name: "ExpiringUser"}, {Value: 8, Name: "ScheduleRestrictedUser"}, {Value: 9, Name: "RemoteOnlyUser"}}},
				{ID: 6, Name: "CredentialRule", DisplayName: "CredentialRule", Type: "enum8", Nullable: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "Single"}, {Value: 1, Name: "Dual"}, {Value: 2, Name: "Tri"}}},
			}},
			{ID: CmdGetUser, Name: "GetUser", DisplayName: "GetUser", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdClearUser, Name: "ClearUser", DisplayName: "ClearUser", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16"},
			}},
			{ID: CmdSetCredential, Name: "SetCredential", DisplayName: "SetCredential", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OperationType", DisplayName: "OperationType", Type: "enum8", EnumValues: []clusters.EnumValue{{Value: 0, Name: "Add"}, {Value: 1, Name: "Clear"}, {Value: 2, Name: "Modify"}}},
				{ID: 1, Name: "Credential", DisplayName: "Credential", Type: "struct"},
				{ID: 2, Name: "CredentialData", DisplayName: "CredentialData", Type: "octets"},
				{ID: 3, Name: "UserIndex", DisplayName: "UserIndex", Type: "uint16", Nullable: true},
				{ID: 4, Name: "UserStatus", DisplayName: "UserStatus", Type: "enum8", Nullable: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "Available"}, {Value: 1, Name: "OccupiedEnabled"}, {Value: 3, Name: "OccupiedDisabled"}}},
				{ID: 5, Name: "UserType", DisplayName: "UserType", Type: "enum8", Nullable: true, EnumValues: []clusters.EnumValue{{Value: 0, Name: "UnrestrictedUser"}, {Value: 1, Name: "YearDayScheduleUser"}, {Value: 2, Name: "WeekDayScheduleUser"}, {Value: 3, Name: "ProgrammingUser"}, {Value: 4, Name: "NonAccessUser"}, {Value: 5, Name: "ForcedUser"}, {Value: 6, Name: "DisposableUser"}, {Value: 7, Name: "ExpiringUser"}, {Value: 8, Name: "ScheduleRestrictedUser"}, {Value: 9, Name: "RemoteOnlyUser"}}},
			}},
			{ID: CmdGetCredentialStatus, Name: "GetCredentialStatus", DisplayName: "GetCredentialStatus", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Credential", DisplayName: "Credential", Type: "struct"},
			}},
			{ID: CmdClearCredential, Name: "ClearCredential", DisplayName: "ClearCredential", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Credential", DisplayName: "Credential", Type: "struct", Nullable: true},
			}},
			{ID: CmdUnboltDoor, Name: "UnboltDoor", DisplayName: "UnboltDoor", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PINCode", DisplayName: "PINCode", Type: "octets", Optional: true},
			}},
			{ID: CmdSetAliroReaderConfig, Name: "SetAliroReaderConfig", DisplayName: "SetAliroReaderConfig", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SigningKey", DisplayName: "SigningKey", Type: "octets"},
				{ID: 1, Name: "VerificationKey", DisplayName: "VerificationKey", Type: "octets"},
				{ID: 2, Name: "GroupIdentifier", DisplayName: "GroupIdentifier", Type: "octets"},
				{ID: 3, Name: "GroupResolvingKey", DisplayName: "GroupResolvingKey", Type: "octets"},
			}},
			{ID: CmdClearAliroReaderConfig, Name: "ClearAliroReaderConfig", DisplayName: "ClearAliroReaderConfig"},
		},
	})
}
