// Code generated by cmd/codegen; DO NOT EDIT.

// Package cameraavstreammanagement implements the Matter Camera AV Stream Management cluster (0x0551).
package cameraavstreammanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Camera AV Stream Management.
	ID uint32 = 0x0551
	// Name is the CLI-friendly cluster name.
	Name = "CameraAVStreamManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Camera AV Stream Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureAudio            uint32 = 1 << 0  // ADO
	FeatureVideo            uint32 = 1 << 1  // VDO
	FeatureSnapshot         uint32 = 1 << 2  // SNP
	FeaturePrivacy          uint32 = 1 << 3  // PRIV
	FeatureSpeaker          uint32 = 1 << 4  // SPKR
	FeatureImageControl     uint32 = 1 << 5  // ICTL
	FeatureWatermark        uint32 = 1 << 6  // WMARK
	FeatureOnScreenDisplay  uint32 = 1 << 7  // OSD
	FeatureLocalStorage     uint32 = 1 << 8  // STOR
	FeatureHighDynamicRange uint32 = 1 << 9  // HDR
	FeatureNightVision      uint32 = 1 << 10 // NV
)

// Attribute IDs.
const (
	AttrMaxConcurrentEncoders            uint32 = 0x0000
	AttrMaxEncodedPixelRate              uint32 = 0x0001
	AttrVideoSensorParams                uint32 = 0x0002
	AttrNightVisionUsesInfrared          uint32 = 0x0003
	AttrMinViewportResolution            uint32 = 0x0004
	AttrRateDistortionTradeOffPoints     uint32 = 0x0005
	AttrMaxContentBufferSize             uint32 = 0x0006
	AttrMicrophoneCapabilities           uint32 = 0x0007
	AttrSpeakerCapabilities              uint32 = 0x0008
	AttrTwoWayTalkSupport                uint32 = 0x0009
	AttrSnapshotCapabilities             uint32 = 0x000A
	AttrMaxNetworkBandwidth              uint32 = 0x000B
	AttrCurrentFrameRate                 uint32 = 0x000C
	AttrHDRModeEnabled                   uint32 = 0x000D
	AttrSupportedStreamUsages            uint32 = 0x000E
	AttrAllocatedVideoStreams            uint32 = 0x000F
	AttrAllocatedAudioStreams            uint32 = 0x0010
	AttrAllocatedSnapshotStreams         uint32 = 0x0011
	AttrStreamUsagePriorities            uint32 = 0x0012
	AttrSoftRecordingPrivacyModeEnabled  uint32 = 0x0013
	AttrSoftLivestreamPrivacyModeEnabled uint32 = 0x0014
	AttrHardPrivacyModeOn                uint32 = 0x0015
	AttrNightVision                      uint32 = 0x0016
	AttrNightVisionIllum                 uint32 = 0x0017
	AttrViewport                         uint32 = 0x0018
	AttrSpeakerMuted                     uint32 = 0x0019
	AttrSpeakerVolumeLevel               uint32 = 0x001A
	AttrSpeakerMaxLevel                  uint32 = 0x001B
	AttrSpeakerMinLevel                  uint32 = 0x001C
	AttrMicrophoneMuted                  uint32 = 0x001D
	AttrMicrophoneVolumeLevel            uint32 = 0x001E
	AttrMicrophoneMaxLevel               uint32 = 0x001F
	AttrMicrophoneMinLevel               uint32 = 0x0020
	AttrMicrophoneAGCEnabled             uint32 = 0x0021
	AttrImageRotation                    uint32 = 0x0022
	AttrImageFlipHorizontal              uint32 = 0x0023
	AttrImageFlipVertical                uint32 = 0x0024
	AttrLocalVideoRecordingEnabled       uint32 = 0x0025
	AttrLocalSnapshotRecordingEnabled    uint32 = 0x0026
	AttrStatusLightEnabled               uint32 = 0x0027
	AttrStatusLightBrightness            uint32 = 0x0028
)

// Command IDs.
const (
	CmdAudioStreamAllocate      uint32 = 0x00
	CmdAudioStreamDeallocate    uint32 = 0x02
	CmdVideoStreamAllocate      uint32 = 0x03
	CmdVideoStreamModify        uint32 = 0x05
	CmdVideoStreamDeallocate    uint32 = 0x06
	CmdSnapshotStreamAllocate   uint32 = 0x07
	CmdSnapshotStreamModify     uint32 = 0x09
	CmdSnapshotStreamDeallocate uint32 = 0x0A
	CmdSetStreamPriorities      uint32 = 0x0B
	CmdCaptureSnapshot          uint32 = 0x0C
)

// AudioStreamAllocateRequest is the request payload for the AudioStreamAllocate command.
type AudioStreamAllocateRequest struct {
	StreamUsage  uint8  `tlv:"0,uint"`
	AudioCodec   uint8  `tlv:"1,uint"`
	ChannelCount uint8  `tlv:"2,uint"`
	SampleRate   uint32 `tlv:"3,uint"`
	BitRate      uint32 `tlv:"4,uint"`
	BitDepth     uint8  `tlv:"5,uint"`
}

// AudioStreamDeallocateRequest is the request payload for the AudioStreamDeallocate command.
type AudioStreamDeallocateRequest struct {
	AudioStreamID uint8 `tlv:"0,uint"`
}

// VideoStreamAllocateRequest is the request payload for the VideoStreamAllocate command.
type VideoStreamAllocateRequest struct {
	StreamUsage      uint8  `tlv:"0,uint"`
	VideoCodec       uint8  `tlv:"1,uint"`
	MinFrameRate     uint16 `tlv:"2,uint"`
	MaxFrameRate     uint16 `tlv:"3,uint"`
	MinResolution    uint8  `tlv:"4,uint"`
	MaxResolution    uint8  `tlv:"5,uint"`
	MinBitRate       uint32 `tlv:"6,uint"`
	MaxBitRate       uint32 `tlv:"7,uint"`
	KeyFrameInterval uint16 `tlv:"8,uint"`
	WatermarkEnabled bool   `tlv:"9,bool"`
	OSDEnabled       bool   `tlv:"10,bool"`
}

// VideoStreamModifyRequest is the request payload for the VideoStreamModify command.
type VideoStreamModifyRequest struct {
	VideoStreamID    uint8 `tlv:"0,uint"`
	WatermarkEnabled bool  `tlv:"1,bool"`
	OSDEnabled       bool  `tlv:"2,bool"`
}

// VideoStreamDeallocateRequest is the request payload for the VideoStreamDeallocate command.
type VideoStreamDeallocateRequest struct {
	VideoStreamID uint8 `tlv:"0,uint"`
}

// SnapshotStreamAllocateRequest is the request payload for the SnapshotStreamAllocate command.
type SnapshotStreamAllocateRequest struct {
	ImageCodec       uint8  `tlv:"0,uint"`
	MaxFrameRate     uint16 `tlv:"1,uint"`
	MinResolution    uint8  `tlv:"2,uint"`
	MaxResolution    uint8  `tlv:"3,uint"`
	Quality          uint8  `tlv:"4,uint"`
	WatermarkEnabled bool   `tlv:"5,bool"`
	OSDEnabled       bool   `tlv:"6,bool"`
}

// SnapshotStreamModifyRequest is the request payload for the SnapshotStreamModify command.
type SnapshotStreamModifyRequest struct {
	SnapshotStreamID uint8 `tlv:"0,uint"`
	WatermarkEnabled bool  `tlv:"1,bool"`
	OSDEnabled       bool  `tlv:"2,bool"`
}

// SnapshotStreamDeallocateRequest is the request payload for the SnapshotStreamDeallocate command.
type SnapshotStreamDeallocateRequest struct {
	SnapshotStreamID uint8 `tlv:"0,uint"`
}

// SetStreamPrioritiesRequest is the request payload for the SetStreamPriorities command.
type SetStreamPrioritiesRequest struct {
	StreamPriorities uint8 `tlv:"0,uint"`
}

// CaptureSnapshotRequest is the request payload for the CaptureSnapshot command.
type CaptureSnapshotRequest struct {
	SnapshotStreamID    uint8 `tlv:"0,uint"`
	RequestedResolution uint8 `tlv:"1,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "ADO", Name: "Audio"},
			{Bit: 1, Code: "VDO", Name: "Video"},
			{Bit: 2, Code: "SNP", Name: "Snapshot"},
			{Bit: 3, Code: "PRIV", Name: "Privacy"},
			{Bit: 4, Code: "SPKR", Name: "Speaker"},
			{Bit: 5, Code: "ICTL", Name: "ImageControl"},
			{Bit: 6, Code: "WMARK", Name: "Watermark"},
			{Bit: 7, Code: "OSD", Name: "OnScreenDisplay"},
			{Bit: 8, Code: "STOR", Name: "LocalStorage"},
			{Bit: 9, Code: "HDR", Name: "HighDynamicRange"},
			{Bit: 10, Code: "NV", Name: "NightVision"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMaxConcurrentEncoders, Name: "MaxConcurrentEncoders", DisplayName: "MaxConcurrentEncoders", Type: "uint8", Readable: true},
			{ID: AttrMaxEncodedPixelRate, Name: "MaxEncodedPixelRate", DisplayName: "MaxEncodedPixelRate", Type: "uint32", Readable: true},
			{ID: AttrVideoSensorParams, Name: "VideoSensorParams", DisplayName: "VideoSensorParams", Type: "struct", Readable: true},
			{ID: AttrNightVisionUsesInfrared, Name: "NightVisionUsesInfrared", DisplayName: "NightVisionUsesInfrared", Type: "bool", Readable: true},
			{ID: AttrMinViewportResolution, Name: "MinViewportResolution", DisplayName: "MinViewportResolution", Type: "struct", Readable: true},
			{ID: AttrRateDistortionTradeOffPoints, Name: "RateDistortionTradeOffPoints", DisplayName: "RateDistortionTradeOffPoints", Type: "list", Readable: true},
			{ID: AttrMaxContentBufferSize, Name: "MaxContentBufferSize", DisplayName: "MaxContentBufferSize", Type: "uint32", Readable: true},
			{ID: AttrMicrophoneCapabilities, Name: "MicrophoneCapabilities", DisplayName: "MicrophoneCapabilities", Type: "struct", Readable: true},
			{ID: AttrSpeakerCapabilities, Name: "SpeakerCapabilities", DisplayName: "SpeakerCapabilities", Type: "struct", Readable: true},
			{ID: AttrTwoWayTalkSupport, Name: "TwoWayTalkSupport", DisplayName: "TwoWayTalkSupport", Type: "enum8", Readable: true},
			{ID: AttrSnapshotCapabilities, Name: "SnapshotCapabilities", DisplayName: "SnapshotCapabilities", Type: "list", Readable: true},
			{ID: AttrMaxNetworkBandwidth, Name: "MaxNetworkBandwidth", DisplayName: "MaxNetworkBandwidth", Type: "uint32", Readable: true},
			{ID: AttrCurrentFrameRate, Name: "CurrentFrameRate", DisplayName: "CurrentFrameRate", Type: "uint16", Readable: true},
			{ID: AttrHDRModeEnabled, Name: "HDRModeEnabled", DisplayName: "HDRModeEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrSupportedStreamUsages, Name: "SupportedStreamUsages", DisplayName: "SupportedStreamUsages", Type: "list", Readable: true},
			{ID: AttrAllocatedVideoStreams, Name: "AllocatedVideoStreams", DisplayName: "AllocatedVideoStreams", Type: "list", Readable: true},
			{ID: AttrAllocatedAudioStreams, Name: "AllocatedAudioStreams", DisplayName: "AllocatedAudioStreams", Type: "list", Readable: true},
			{ID: AttrAllocatedSnapshotStreams, Name: "AllocatedSnapshotStreams", DisplayName: "AllocatedSnapshotStreams", Type: "list", Readable: true},
			{ID: AttrStreamUsagePriorities, Name: "StreamUsagePriorities", DisplayName: "StreamUsagePriorities", Type: "list", Readable: true},
			{ID: AttrSoftRecordingPrivacyModeEnabled, Name: "SoftRecordingPrivacyModeEnabled", DisplayName: "SoftRecordingPrivacyModeEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrSoftLivestreamPrivacyModeEnabled, Name: "SoftLivestreamPrivacyModeEnabled", DisplayName: "SoftLivestreamPrivacyModeEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrHardPrivacyModeOn, Name: "HardPrivacyModeOn", DisplayName: "HardPrivacyModeOn", Type: "bool", Readable: true},
			{ID: AttrNightVision, Name: "NightVision", DisplayName: "NightVision", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrNightVisionIllum, Name: "NightVisionIllum", DisplayName: "NightVisionIllum", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrViewport, Name: "Viewport", DisplayName: "Viewport", Type: "struct", Readable: true, Writable: true},
			{ID: AttrSpeakerMuted, Name: "SpeakerMuted", DisplayName: "SpeakerMuted", Type: "bool", Readable: true, Writable: true},
			{ID: AttrSpeakerVolumeLevel, Name: "SpeakerVolumeLevel", DisplayName: "SpeakerVolumeLevel", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrSpeakerMaxLevel, Name: "SpeakerMaxLevel", DisplayName: "SpeakerMaxLevel", Type: "uint8", Readable: true},
			{ID: AttrSpeakerMinLevel, Name: "SpeakerMinLevel", DisplayName: "SpeakerMinLevel", Type: "uint8", Readable: true},
			{ID: AttrMicrophoneMuted, Name: "MicrophoneMuted", DisplayName: "MicrophoneMuted", Type: "bool", Readable: true, Writable: true},
			{ID: AttrMicrophoneVolumeLevel, Name: "MicrophoneVolumeLevel", DisplayName: "MicrophoneVolumeLevel", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrMicrophoneMaxLevel, Name: "MicrophoneMaxLevel", DisplayName: "MicrophoneMaxLevel", Type: "uint8", Readable: true},
			{ID: AttrMicrophoneMinLevel, Name: "MicrophoneMinLevel", DisplayName: "MicrophoneMinLevel", Type: "uint8", Readable: true},
			{ID: AttrMicrophoneAGCEnabled, Name: "MicrophoneAGCEnabled", DisplayName: "MicrophoneAGCEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrImageRotation, Name: "ImageRotation", DisplayName: "ImageRotation", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrImageFlipHorizontal, Name: "ImageFlipHorizontal", DisplayName: "ImageFlipHorizontal", Type: "bool", Readable: true, Writable: true},
			{ID: AttrImageFlipVertical, Name: "ImageFlipVertical", DisplayName: "ImageFlipVertical", Type: "bool", Readable: true, Writable: true},
			{ID: AttrLocalVideoRecordingEnabled, Name: "LocalVideoRecordingEnabled", DisplayName: "LocalVideoRecordingEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrLocalSnapshotRecordingEnabled, Name: "LocalSnapshotRecordingEnabled", DisplayName: "LocalSnapshotRecordingEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrStatusLightEnabled, Name: "StatusLightEnabled", DisplayName: "StatusLightEnabled", Type: "bool", Readable: true, Writable: true},
			{ID: AttrStatusLightBrightness, Name: "StatusLightBrightness", DisplayName: "StatusLightBrightness", Type: "enum8", Readable: true, Writable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAudioStreamAllocate, Name: "AudioStreamAllocate", DisplayName: "AudioStreamAllocate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StreamUsage", DisplayName: "StreamUsage", Type: "enum8"},
				{ID: 1, Name: "AudioCodec", DisplayName: "AudioCodec", Type: "enum8"},
				{ID: 2, Name: "ChannelCount", DisplayName: "ChannelCount", Type: "uint8"},
				{ID: 3, Name: "SampleRate", DisplayName: "SampleRate", Type: "uint32"},
				{ID: 4, Name: "BitRate", DisplayName: "BitRate", Type: "uint32"},
				{ID: 5, Name: "BitDepth", DisplayName: "BitDepth", Type: "uint8"},
			}},
			{ID: CmdAudioStreamDeallocate, Name: "AudioStreamDeallocate", DisplayName: "AudioStreamDeallocate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AudioStreamID", DisplayName: "AudioStreamID", Type: "uint8"},
			}},
			{ID: CmdVideoStreamAllocate, Name: "VideoStreamAllocate", DisplayName: "VideoStreamAllocate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StreamUsage", DisplayName: "StreamUsage", Type: "enum8"},
				{ID: 1, Name: "VideoCodec", DisplayName: "VideoCodec", Type: "enum8"},
				{ID: 2, Name: "MinFrameRate", DisplayName: "MinFrameRate", Type: "uint16"},
				{ID: 3, Name: "MaxFrameRate", DisplayName: "MaxFrameRate", Type: "uint16"},
				{ID: 4, Name: "MinResolution", DisplayName: "MinResolution", Type: "struct"},
				{ID: 5, Name: "MaxResolution", DisplayName: "MaxResolution", Type: "struct"},
				{ID: 6, Name: "MinBitRate", DisplayName: "MinBitRate", Type: "uint32"},
				{ID: 7, Name: "MaxBitRate", DisplayName: "MaxBitRate", Type: "uint32"},
				{ID: 8, Name: "KeyFrameInterval", DisplayName: "KeyFrameInterval", Type: "uint16"},
				{ID: 9, Name: "WatermarkEnabled", DisplayName: "WatermarkEnabled", Type: "bool"},
				{ID: 10, Name: "OSDEnabled", DisplayName: "OSDEnabled", Type: "bool"},
			}},
			{ID: CmdVideoStreamModify, Name: "VideoStreamModify", DisplayName: "VideoStreamModify", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VideoStreamID", DisplayName: "VideoStreamID", Type: "uint8"},
				{ID: 1, Name: "WatermarkEnabled", DisplayName: "WatermarkEnabled", Type: "bool", Optional: true},
				{ID: 2, Name: "OSDEnabled", DisplayName: "OSDEnabled", Type: "bool", Optional: true},
			}},
			{ID: CmdVideoStreamDeallocate, Name: "VideoStreamDeallocate", DisplayName: "VideoStreamDeallocate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VideoStreamID", DisplayName: "VideoStreamID", Type: "uint8"},
			}},
			{ID: CmdSnapshotStreamAllocate, Name: "SnapshotStreamAllocate", DisplayName: "SnapshotStreamAllocate", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ImageCodec", DisplayName: "ImageCodec", Type: "enum8"},
				{ID: 1, Name: "MaxFrameRate", DisplayName: "MaxFrameRate", Type: "uint16"},
				{ID: 2, Name: "MinResolution", DisplayName: "MinResolution", Type: "struct"},
				{ID: 3, Name: "MaxResolution", DisplayName: "MaxResolution", Type: "struct"},
				{ID: 4, Name: "Quality", DisplayName: "Quality", Type: "uint8"},
				{ID: 5, Name: "WatermarkEnabled", DisplayName: "WatermarkEnabled", Type: "bool"},
				{ID: 6, Name: "OSDEnabled", DisplayName: "OSDEnabled", Type: "bool"},
			}},
			{ID: CmdSnapshotStreamModify, Name: "SnapshotStreamModify", DisplayName: "SnapshotStreamModify", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SnapshotStreamID", DisplayName: "SnapshotStreamID", Type: "uint8"},
				{ID: 1, Name: "WatermarkEnabled", DisplayName: "WatermarkEnabled", Type: "bool", Optional: true},
				{ID: 2, Name: "OSDEnabled", DisplayName: "OSDEnabled", Type: "bool", Optional: true},
			}},
			{ID: CmdSnapshotStreamDeallocate, Name: "SnapshotStreamDeallocate", DisplayName: "SnapshotStreamDeallocate", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SnapshotStreamID", DisplayName: "SnapshotStreamID", Type: "uint8"},
			}},
			{ID: CmdSetStreamPriorities, Name: "SetStreamPriorities", DisplayName: "SetStreamPriorities", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StreamPriorities", DisplayName: "StreamPriorities", Type: "list"},
			}},
			{ID: CmdCaptureSnapshot, Name: "CaptureSnapshot", DisplayName: "CaptureSnapshot", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "SnapshotStreamID", DisplayName: "SnapshotStreamID", Type: "uint8", Nullable: true},
				{ID: 1, Name: "RequestedResolution", DisplayName: "RequestedResolution", Type: "struct"},
			}},
		},
	})
}
