// Code generated by cmd/codegen; DO NOT EDIT.

// Package generaldiagnostics implements the Matter General Diagnostics cluster (0x0033).
package generaldiagnostics

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for General Diagnostics.
	ID uint32 = 0x0033
	// Name is the CLI-friendly cluster name.
	Name = "GeneralDiagnostics"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "General Diagnostics"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureDataModelTest uint32 = 1 << 0 // DMTEST
)

// Attribute IDs.
const (
	AttrNetworkInterfaces        uint32 = 0x0000
	AttrRebootCount              uint32 = 0x0001
	AttrUpTime                   uint32 = 0x0002
	AttrTotalOperationalHours    uint32 = 0x0003
	AttrBootReason               uint32 = 0x0004
	AttrActiveHardwareFaults     uint32 = 0x0005
	AttrActiveRadioFaults        uint32 = 0x0006
	AttrActiveNetworkFaults      uint32 = 0x0007
	AttrTestEventTriggersEnabled uint32 = 0x0008
	AttrDoNotUse                 uint32 = 0x0009
)

// Command IDs.
const (
	CmdTestEventTrigger   uint32 = 0x00
	CmdTimeSnapshot       uint32 = 0x01
	CmdPayloadTestRequest uint32 = 0x03
)

// TestEventTriggerRequest is the request payload for the TestEventTrigger command.
type TestEventTriggerRequest struct {
	EnableKey    []byte `tlv:"0,bytes"`
	EventTrigger uint64 `tlv:"1,uint"`
}

// PayloadTestRequestRequest is the request payload for the PayloadTestRequest command.
type PayloadTestRequestRequest struct {
	EnableKey []byte `tlv:"0,bytes"`
	Value     uint8  `tlv:"1,uint"`
	Count     uint16 `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DMTEST", Name: "DataModelTest"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrNetworkInterfaces, Name: "NetworkInterfaces", DisplayName: "NetworkInterfaces", Type: "list", Readable: true},
			{ID: AttrRebootCount, Name: "RebootCount", DisplayName: "RebootCount", Type: "uint16", Readable: true},
			{ID: AttrUpTime, Name: "UpTime", DisplayName: "UpTime", Type: "uint64", Readable: true},
			{ID: AttrTotalOperationalHours, Name: "TotalOperationalHours", DisplayName: "TotalOperationalHours", Type: "uint32", Readable: true},
			{ID: AttrBootReason, Name: "BootReason", DisplayName: "BootReason", Type: "enum8", Readable: true},
			{ID: AttrActiveHardwareFaults, Name: "ActiveHardwareFaults", DisplayName: "ActiveHardwareFaults", Type: "list", Readable: true},
			{ID: AttrActiveRadioFaults, Name: "ActiveRadioFaults", DisplayName: "ActiveRadioFaults", Type: "list", Readable: true},
			{ID: AttrActiveNetworkFaults, Name: "ActiveNetworkFaults", DisplayName: "ActiveNetworkFaults", Type: "list", Readable: true},
			{ID: AttrTestEventTriggersEnabled, Name: "TestEventTriggersEnabled", DisplayName: "TestEventTriggersEnabled", Type: "bool", Readable: true},
			{ID: AttrDoNotUse, Name: "DoNotUse", DisplayName: "DoNotUse", Type: "uint8", Readable: false},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdTestEventTrigger, Name: "TestEventTrigger", DisplayName: "TestEventTrigger", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EnableKey", DisplayName: "EnableKey", Type: "octets"},
				{ID: 1, Name: "EventTrigger", DisplayName: "EventTrigger", Type: "uint64"},
			}},
			{ID: CmdTimeSnapshot, Name: "TimeSnapshot", DisplayName: "TimeSnapshot", HasResponse: true},
			{ID: CmdPayloadTestRequest, Name: "PayloadTestRequest", DisplayName: "PayloadTestRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EnableKey", DisplayName: "EnableKey", Type: "octets"},
				{ID: 1, Name: "Value", DisplayName: "Value", Type: "uint8"},
				{ID: 2, Name: "Count", DisplayName: "Count", Type: "uint16"},
			}},
		},
	})
}
