// Code generated by cmd/codegen; DO NOT EDIT.

// Package refrigeratoralarm implements the Matter Refrigerator Alarm cluster (0x0057).
package refrigeratoralarm

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Refrigerator Alarm.
	ID uint32 = 0x0057
	// Name is the CLI-friendly cluster name.
	Name = "RefrigeratorAlarm"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Refrigerator Alarm"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureReset uint32 = 1 << 0 // RESET
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "RESET", Name: "Reset"},
		},
	})
}
