// Code generated by cmd/codegen; DO NOT EDIT.

// Package operationalstate implements the Matter Operational State cluster (0x0060).
package operationalstate

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Operational State.
	ID uint32 = 0x0060
	// Name is the CLI-friendly cluster name.
	Name = "OperationalState"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Operational State"
)

// Attribute IDs.
const (
	AttrPhaseList            uint32 = 0x0000
	AttrCurrentPhase         uint32 = 0x0001
	AttrCountdownTime        uint32 = 0x0002
	AttrOperationalStateList uint32 = 0x0003
	AttrOperationalState     uint32 = 0x0004
	AttrOperationalError     uint32 = 0x0005
)

// Command IDs.
const (
	CmdPause  uint32 = 0x00
	CmdStop   uint32 = 0x01
	CmdStart  uint32 = 0x02
	CmdResume uint32 = 0x03
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrPhaseList, Name: "PhaseList", DisplayName: "PhaseList", Type: "list", Readable: true, Nullable: true},
			{ID: AttrCurrentPhase, Name: "CurrentPhase", DisplayName: "CurrentPhase", Type: "uint8", Readable: true, Nullable: true},
			{ID: AttrCountdownTime, Name: "CountdownTime", DisplayName: "CountdownTime", Type: "uint32", Readable: true, Nullable: true},
			{ID: AttrOperationalStateList, Name: "OperationalStateList", DisplayName: "OperationalStateList", Type: "list", Readable: true},
			{ID: AttrOperationalState, Name: "OperationalState", DisplayName: "OperationalState", Type: "enum8", Readable: true},
			{ID: AttrOperationalError, Name: "OperationalError", DisplayName: "OperationalError", Type: "struct", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdPause, Name: "Pause", DisplayName: "Pause", HasResponse: true},
			{ID: CmdStop, Name: "Stop", DisplayName: "Stop", HasResponse: true},
			{ID: CmdStart, Name: "Start", DisplayName: "Start", HasResponse: true},
			{ID: CmdResume, Name: "Resume", DisplayName: "Resume", HasResponse: true},
		},
	})
}
