// Code generated by cmd/codegen; DO NOT EDIT.

// Package localizationconfiguration implements the Matter Localization Configuration cluster (0x002B).
package localizationconfiguration

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Localization Configuration.
	ID uint32 = 0x002B
	// Name is the CLI-friendly cluster name.
	Name = "LocalizationConfiguration"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Localization Configuration"
)

// Attribute IDs.
const (
	AttrActiveLocale     uint32 = 0x0000
	AttrSupportedLocales uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrActiveLocale, Name: "ActiveLocale", DisplayName: "ActiveLocale", Type: "string", Readable: true, Writable: true},
			{ID: AttrSupportedLocales, Name: "SupportedLocales", DisplayName: "SupportedLocales", Type: "list", Readable: true},
		},
	})
}
