// Code generated by cmd/codegen; DO NOT EDIT.

// Package softwarediagnostics implements the Matter Software Diagnostics cluster (0x0034).
package softwarediagnostics

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Software Diagnostics.
	ID uint32 = 0x0034
	// Name is the CLI-friendly cluster name.
	Name = "SoftwareDiagnostics"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Software Diagnostics"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureWatermarks uint32 = 1 << 0 // WTRMRK
)

// Attribute IDs.
const (
	AttrThreadMetrics            uint32 = 0x0000
	AttrCurrentHeapFree          uint32 = 0x0001
	AttrCurrentHeapUsed          uint32 = 0x0002
	AttrCurrentHeapHighWatermark uint32 = 0x0003
)

// Command IDs.
const (
	CmdResetWatermarks uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "WTRMRK", Name: "Watermarks"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrThreadMetrics, Name: "ThreadMetrics", DisplayName: "ThreadMetrics", Type: "list", Readable: true},
			{ID: AttrCurrentHeapFree, Name: "CurrentHeapFree", DisplayName: "CurrentHeapFree", Type: "uint64", Readable: true},
			{ID: AttrCurrentHeapUsed, Name: "CurrentHeapUsed", DisplayName: "CurrentHeapUsed", Type: "uint64", Readable: true},
			{ID: AttrCurrentHeapHighWatermark, Name: "CurrentHeapHighWatermark", DisplayName: "CurrentHeapHighWatermark", Type: "uint64", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdResetWatermarks, Name: "ResetWatermarks", DisplayName: "ResetWatermarks"},
		},
	})
}
