// Code generated by cmd/codegen; DO NOT EDIT.

// Package fixedlabel implements the Matter Fixed Label cluster (0x0040).
package fixedlabel

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Fixed Label.
	ID uint32 = 0x0040
	// Name is the CLI-friendly cluster name.
	Name = "FixedLabel"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Fixed Label"
)

// Attribute IDs.
const (
	AttrLabelList uint32 = 0x0000
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrLabelList, Name: "LabelList", DisplayName: "LabelList", Type: "list", Readable: true},
		},
	})
}
