// Code generated by cmd/codegen; DO NOT EDIT.

// Package onoff implements the Matter On/Off cluster (0x0006).
package onoff

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for On/Off.
	ID uint32 = 0x0006
	// Name is the CLI-friendly cluster name.
	Name = "OnOff"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "On/Off"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureLighting          uint32 = 1 << 0 // LT
	FeatureDeadFrontBehavior uint32 = 1 << 1 // DF
	FeatureOffOnly           uint32 = 1 << 2 // OFFONLY
)

// Attribute IDs.
const (
	AttrOnOff              uint32 = 0x0000
	AttrGlobalSceneControl uint32 = 0x4000
	AttrOnTime             uint32 = 0x4001
	AttrOffWaitTime        uint32 = 0x4002
	AttrStartUpOnOff       uint32 = 0x4003
)

// Command IDs.
const (
	CmdOff                     uint32 = 0x00
	CmdOn                      uint32 = 0x01
	CmdToggle                  uint32 = 0x02
	CmdOffWithEffect           uint32 = 0x40
	CmdOnWithRecallGlobalScene uint32 = 0x41
	CmdOnWithTimedOff          uint32 = 0x42
)

// OffWithEffectRequest is the request payload for the OffWithEffect command.
type OffWithEffectRequest struct {
	EffectIdentifier uint8 `tlv:"0,uint"`
	EffectVariant    uint8 `tlv:"1,uint"`
}

// OnWithTimedOffRequest is the request payload for the OnWithTimedOff command.
type OnWithTimedOffRequest struct {
	OnOffControl uint8  `tlv:"0,uint"`
	OnTime       uint16 `tlv:"1,uint"`
	OffWaitTime  uint16 `tlv:"2,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "LT", Name: "Lighting"},
			{Bit: 1, Code: "DF", Name: "DeadFrontBehavior"},
			{Bit: 2, Code: "OFFONLY", Name: "OffOnly"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrOnOff, Name: "OnOff", DisplayName: "OnOff", Type: "bool", Readable: true},
			{ID: AttrGlobalSceneControl, Name: "GlobalSceneControl", DisplayName: "GlobalSceneControl", Type: "bool", Readable: true},
			{ID: AttrOnTime, Name: "OnTime", DisplayName: "OnTime", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrOffWaitTime, Name: "OffWaitTime", DisplayName: "OffWaitTime", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrStartUpOnOff, Name: "StartUpOnOff", DisplayName: "StartUpOnOff", Type: "enum8", Readable: true, Writable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdOff, Name: "Off", DisplayName: "Off"},
			{ID: CmdOn, Name: "On", DisplayName: "On"},
			{ID: CmdToggle, Name: "Toggle", DisplayName: "Toggle"},
			{ID: CmdOffWithEffect, Name: "OffWithEffect", DisplayName: "OffWithEffect", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "EffectIdentifier", DisplayName: "EffectIdentifier", Type: "enum8"},
				{ID: 1, Name: "EffectVariant", DisplayName: "EffectVariant", Type: "enum8"},
			}},
			{ID: CmdOnWithRecallGlobalScene, Name: "OnWithRecallGlobalScene", DisplayName: "OnWithRecallGlobalScene"},
			{ID: CmdOnWithTimedOff, Name: "OnWithTimedOff", DisplayName: "OnWithTimedOff", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "OnOffControl", DisplayName: "OnOffControl", Type: "bitmap8"},
				{ID: 1, Name: "OnTime", DisplayName: "OnTime", Type: "uint16"},
				{ID: 2, Name: "OffWaitTime", DisplayName: "OffWaitTime", Type: "uint16"},
			}},
		},
	})
}
