// Code generated by cmd/codegen; DO NOT EDIT.

// Package rvcrunmode implements the Matter RVC Run Mode cluster (0x0054).
package rvcrunmode

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for RVC Run Mode.
	ID uint32 = 0x0054
	// Name is the CLI-friendly cluster name.
	Name = "RVCRunMode"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "RVC Run Mode"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureOnOff            uint32 = 1 << 0  // DEPONOFF
	FeatureDirectModeChange uint32 = 1 << 20 // DIRECTMODECH
)

// Attribute IDs.
const (
	AttrSupportedModes uint32 = 0x0000
	AttrCurrentMode    uint32 = 0x0001
	AttrStartUpMode    uint32 = 0x0002
	AttrOnMode         uint32 = 0x0003
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DEPONOFF", Name: "OnOff"},
			{Bit: 20, Code: "DIRECTMODECH", Name: "DirectModeChange"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedModes, Name: "SupportedModes", DisplayName: "SupportedModes", Type: "uint8", Readable: false},
			{ID: AttrCurrentMode, Name: "CurrentMode", DisplayName: "CurrentMode", Type: "uint8", Readable: false},
			{ID: AttrStartUpMode, Name: "StartUpMode", DisplayName: "StartUpMode", Type: "uint8", Readable: false},
			{ID: AttrOnMode, Name: "OnMode", DisplayName: "OnMode", Type: "uint8", Readable: false},
		},
	})
}
