// Code generated by cmd/codegen; DO NOT EDIT.

// Package laundrywashercontrols implements the Matter Laundry Washer Controls cluster (0x0053).
package laundrywashercontrols

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Laundry Washer Controls.
	ID uint32 = 0x0053
	// Name is the CLI-friendly cluster name.
	Name = "LaundryWasherControls"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Laundry Washer Controls"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureSpin  uint32 = 1 << 0 // SPIN
	FeatureRinse uint32 = 1 << 1 // RINSE
)

// Attribute IDs.
const (
	AttrSpinSpeeds       uint32 = 0x0000
	AttrSpinSpeedCurrent uint32 = 0x0001
	AttrNumberOfRinses   uint32 = 0x0002
	AttrSupportedRinses  uint32 = 0x0003
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "SPIN", Name: "Spin"},
			{Bit: 1, Code: "RINSE", Name: "Rinse"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSpinSpeeds, Name: "SpinSpeeds", DisplayName: "SpinSpeeds", Type: "list", Readable: true},
			{ID: AttrSpinSpeedCurrent, Name: "SpinSpeedCurrent", DisplayName: "SpinSpeedCurrent", Type: "uint8", Readable: true, Writable: true, Nullable: true},
			{ID: AttrNumberOfRinses, Name: "NumberOfRinses", DisplayName: "NumberOfRinses", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrSupportedRinses, Name: "SupportedRinses", DisplayName: "SupportedRinses", Type: "list", Readable: true},
		},
	})
}
