// Code generated by cmd/codegen; DO NOT EDIT.

// Package scenesmanagement implements the Matter Scenes Management cluster (0x0062).
package scenesmanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Scenes Management.
	ID uint32 = 0x0062
	// Name is the CLI-friendly cluster name.
	Name = "ScenesManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Scenes Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureSceneNames uint32 = 1 << 0 // SN
)

// Attribute IDs.
const (
	AttrDoNotUse        uint32 = 0x0000
	AttrSceneTableSize  uint32 = 0x0001
	AttrFabricSceneInfo uint32 = 0x0002
)

// Command IDs.
const (
	CmdAddScene           uint32 = 0x00
	CmdViewScene          uint32 = 0x01
	CmdRemoveScene        uint32 = 0x02
	CmdRemoveAllScenes    uint32 = 0x03
	CmdStoreScene         uint32 = 0x04
	CmdRecallScene        uint32 = 0x05
	CmdGetSceneMembership uint32 = 0x06
	CmdCopyScene          uint32 = 0x40
)

// AddSceneRequest is the request payload for the AddScene command.
type AddSceneRequest struct {
	GroupID                  uint16 `tlv:"0,uint"`
	SceneID                  uint8  `tlv:"1,uint"`
	TransitionTime           uint32 `tlv:"2,uint"`
	SceneName                string `tlv:"3,utf8"`
	ExtensionFieldSetStructs uint8  `tlv:"4,uint"`
}

// ViewSceneRequest is the request payload for the ViewScene command.
type ViewSceneRequest struct {
	GroupID uint16 `tlv:"0,uint"`
	SceneID uint8  `tlv:"1,uint"`
}

// RemoveSceneRequest is the request payload for the RemoveScene command.
type RemoveSceneRequest struct {
	GroupID uint16 `tlv:"0,uint"`
	SceneID uint8  `tlv:"1,uint"`
}

// RemoveAllScenesRequest is the request payload for the RemoveAllScenes command.
type RemoveAllScenesRequest struct {
	GroupID uint16 `tlv:"0,uint"`
}

// StoreSceneRequest is the request payload for the StoreScene command.
type StoreSceneRequest struct {
	GroupID uint16 `tlv:"0,uint"`
	SceneID uint8  `tlv:"1,uint"`
}

// RecallSceneRequest is the request payload for the RecallScene command.
type RecallSceneRequest struct {
	GroupID        uint16 `tlv:"0,uint"`
	SceneID        uint8  `tlv:"1,uint"`
	TransitionTime uint32 `tlv:"2,uint"`
}

// GetSceneMembershipRequest is the request payload for the GetSceneMembership command.
type GetSceneMembershipRequest struct {
	GroupID uint16 `tlv:"0,uint"`
}

// CopySceneRequest is the request payload for the CopyScene command.
type CopySceneRequest struct {
	Mode                uint8  `tlv:"0,uint"`
	GroupIdentifierFrom uint16 `tlv:"1,uint"`
	SceneIdentifierFrom uint8  `tlv:"2,uint"`
	GroupIdentifierTo   uint16 `tlv:"3,uint"`
	SceneIdentifierTo   uint8  `tlv:"4,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "SN", Name: "SceneNames"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrDoNotUse, Name: "DoNotUse", DisplayName: "DoNotUse", Type: "uint8", Readable: true},
			{ID: AttrSceneTableSize, Name: "SceneTableSize", DisplayName: "SceneTableSize", Type: "uint16", Readable: true},
			{ID: AttrFabricSceneInfo, Name: "FabricSceneInfo", DisplayName: "FabricSceneInfo", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdAddScene, Name: "AddScene", DisplayName: "AddScene", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "SceneID", DisplayName: "SceneID", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint32"},
				{ID: 3, Name: "SceneName", DisplayName: "SceneName", Type: "string"},
				{ID: 4, Name: "ExtensionFieldSetStructs", DisplayName: "ExtensionFieldSetStructs", Type: "list"},
			}},
			{ID: CmdViewScene, Name: "ViewScene", DisplayName: "ViewScene", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "SceneID", DisplayName: "SceneID", Type: "uint8"},
			}},
			{ID: CmdRemoveScene, Name: "RemoveScene", DisplayName: "RemoveScene", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "SceneID", DisplayName: "SceneID", Type: "uint8"},
			}},
			{ID: CmdRemoveAllScenes, Name: "RemoveAllScenes", DisplayName: "RemoveAllScenes", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdStoreScene, Name: "StoreScene", DisplayName: "StoreScene", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "SceneID", DisplayName: "SceneID", Type: "uint8"},
			}},
			{ID: CmdRecallScene, Name: "RecallScene", DisplayName: "RecallScene", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
				{ID: 1, Name: "SceneID", DisplayName: "SceneID", Type: "uint8"},
				{ID: 2, Name: "TransitionTime", DisplayName: "TransitionTime", Type: "uint32", Optional: true, Nullable: true},
			}},
			{ID: CmdGetSceneMembership, Name: "GetSceneMembership", DisplayName: "GetSceneMembership", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "GroupID", DisplayName: "GroupID", Type: "uint16"},
			}},
			{ID: CmdCopyScene, Name: "CopyScene", DisplayName: "CopyScene", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Mode", DisplayName: "Mode", Type: "bitmap8"},
				{ID: 1, Name: "GroupIdentifierFrom", DisplayName: "GroupIdentifierFrom", Type: "uint16"},
				{ID: 2, Name: "SceneIdentifierFrom", DisplayName: "SceneIdentifierFrom", Type: "uint8"},
				{ID: 3, Name: "GroupIdentifierTo", DisplayName: "GroupIdentifierTo", Type: "uint16"},
				{ID: 4, Name: "SceneIdentifierTo", DisplayName: "SceneIdentifierTo", Type: "uint8"},
			}},
		},
	})
}
