// Code generated by cmd/codegen; DO NOT EDIT.

// Package microwaveovencontrol implements the Matter Microwave Oven Control cluster (0x005F).
package microwaveovencontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Microwave Oven Control.
	ID uint32 = 0x005F
	// Name is the CLI-friendly cluster name.
	Name = "MicrowaveOvenControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Microwave Oven Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeaturePowerAsNumber     uint32 = 1 << 0 // PWRNUM
	FeaturePowerInWatts      uint32 = 1 << 1 // WATTS
	FeaturePowerNumberLimits uint32 = 1 << 2 // PWRLMTS
)

// Attribute IDs.
const (
	AttrCookTime          uint32 = 0x0000
	AttrMaxCookTime       uint32 = 0x0001
	AttrPowerSetting      uint32 = 0x0002
	AttrMinPower          uint32 = 0x0003
	AttrMaxPower          uint32 = 0x0004
	AttrPowerStep         uint32 = 0x0005
	AttrSupportedWatts    uint32 = 0x0006
	AttrSelectedWattIndex uint32 = 0x0007
	AttrWattRating        uint32 = 0x0008
)

// Command IDs.
const (
	CmdSetCookingParameters uint32 = 0x00
	CmdAddMoreTime          uint32 = 0x01
)

// SetCookingParametersRequest is the request payload for the SetCookingParameters command.
type SetCookingParametersRequest struct {
	CookMode          uint8  `tlv:"0,uint"`
	CookTime          uint32 `tlv:"1,uint"`
	PowerSetting      uint8  `tlv:"2,uint"`
	WattSettingIndex  uint8  `tlv:"3,uint"`
	StartAfterSetting bool   `tlv:"4,bool"`
}

// AddMoreTimeRequest is the request payload for the AddMoreTime command.
type AddMoreTimeRequest struct {
	TimeToAdd uint32 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "PWRNUM", Name: "PowerAsNumber"},
			{Bit: 1, Code: "WATTS", Name: "PowerInWatts"},
			{Bit: 2, Code: "PWRLMTS", Name: "PowerNumberLimits"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCookTime, Name: "CookTime", DisplayName: "CookTime", Type: "uint32", Readable: true},
			{ID: AttrMaxCookTime, Name: "MaxCookTime", DisplayName: "MaxCookTime", Type: "uint32", Readable: true},
			{ID: AttrPowerSetting, Name: "PowerSetting", DisplayName: "PowerSetting", Type: "uint8", Readable: true},
			{ID: AttrMinPower, Name: "MinPower", DisplayName: "MinPower", Type: "uint8", Readable: true},
			{ID: AttrMaxPower, Name: "MaxPower", DisplayName: "MaxPower", Type: "uint8", Readable: true},
			{ID: AttrPowerStep, Name: "PowerStep", DisplayName: "PowerStep", Type: "uint8", Readable: true},
			{ID: AttrSupportedWatts, Name: "SupportedWatts", DisplayName: "SupportedWatts", Type: "list", Readable: true},
			{ID: AttrSelectedWattIndex, Name: "SelectedWattIndex", DisplayName: "SelectedWattIndex", Type: "uint8", Readable: true},
			{ID: AttrWattRating, Name: "WattRating", DisplayName: "WattRating", Type: "uint16", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSetCookingParameters, Name: "SetCookingParameters", DisplayName: "SetCookingParameters", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CookMode", DisplayName: "CookMode", Type: "uint8", Optional: true},
				{ID: 1, Name: "CookTime", DisplayName: "CookTime", Type: "uint32", Optional: true},
				{ID: 2, Name: "PowerSetting", DisplayName: "PowerSetting", Type: "uint8", Optional: true},
				{ID: 3, Name: "WattSettingIndex", DisplayName: "WattSettingIndex", Type: "uint8", Optional: true},
				{ID: 4, Name: "StartAfterSetting", DisplayName: "StartAfterSetting", Type: "bool", Optional: true},
			}},
			{ID: CmdAddMoreTime, Name: "AddMoreTime", DisplayName: "AddMoreTime", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TimeToAdd", DisplayName: "TimeToAdd", Type: "uint32"},
			}},
		},
	})
}
