// Code generated by cmd/codegen; DO NOT EDIT.

// Package ecosysteminformation implements the Matter Ecosystem Information cluster (0x0750).
package ecosysteminformation

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Ecosystem Information.
	ID uint32 = 0x0750
	// Name is the CLI-friendly cluster name.
	Name = "EcosystemInformation"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Ecosystem Information"
)

// Attribute IDs.
const (
	AttrDeviceDirectory   uint32 = 0x0000
	AttrLocationDirectory uint32 = 0x0001
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrDeviceDirectory, Name: "DeviceDirectory", DisplayName: "DeviceDirectory", Type: "list", Readable: true},
			{ID: AttrLocationDirectory, Name: "LocationDirectory", DisplayName: "LocationDirectory", Type: "list", Readable: true},
		},
	})
}
