// Code generated by cmd/codegen; DO NOT EDIT.

// Package modeselect implements the Matter Mode Select cluster (0x0050).
package modeselect

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Mode Select.
	ID uint32 = 0x0050
	// Name is the CLI-friendly cluster name.
	Name = "ModeSelect"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Mode Select"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureOnOff uint32 = 1 << 0 // DEPONOFF
)

// Attribute IDs.
const (
	AttrDescription       uint32 = 0x0000
	AttrStandardNamespace uint32 = 0x0001
	AttrSupportedModes    uint32 = 0x0002
	AttrCurrentMode       uint32 = 0x0003
	AttrStartUpMode       uint32 = 0x0004
	AttrOnMode            uint32 = 0x0005
)

// Command IDs.
const (
	CmdChangeToMode uint32 = 0x00
)

// ChangeToModeRequest is the request payload for the ChangeToMode command.
type ChangeToModeRequest struct {
	NewMode uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DEPONOFF", Name: "OnOff"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrDescription, Name: "Description", DisplayName: "Description", Type: "string", Readable: true},
			{ID: AttrStandardNamespace, Name: "StandardNamespace", DisplayName: "StandardNamespace", Type: "enum16", Readable: true, Nullable: true},
			{ID: AttrSupportedModes, Name: "SupportedModes", DisplayName: "SupportedModes", Type: "list", Readable: true},
			{ID: AttrCurrentMode, Name: "CurrentMode", DisplayName: "CurrentMode", Type: "uint8", Readable: true},
			{ID: AttrStartUpMode, Name: "StartUpMode", DisplayName: "StartUpMode", Type: "uint8", Readable: true, Writable: true, Nullable: true},
			{ID: AttrOnMode, Name: "OnMode", DisplayName: "OnMode", Type: "uint8", Readable: true, Writable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdChangeToMode, Name: "ChangeToMode", DisplayName: "ChangeToMode", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "NewMode", DisplayName: "NewMode", Type: "uint8"},
			}},
		},
	})
}
