// Code generated by cmd/codegen; DO NOT EDIT.

// Package contentlauncher implements the Matter Content Launcher cluster (0x050A).
package contentlauncher

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Content Launcher.
	ID uint32 = 0x050A
	// Name is the CLI-friendly cluster name.
	Name = "ContentLauncher"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Content Launcher"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureContentSearch uint32 = 1 << 0 // CS
	FeatureURLPlayback   uint32 = 1 << 1 // UP
	FeatureAdvancedSeek  uint32 = 1 << 2 // AS
	FeatureTextTracks    uint32 = 1 << 3 // TT
	FeatureAudioTracks   uint32 = 1 << 4 // AT
)

// Attribute IDs.
const (
	AttrAcceptHeader                uint32 = 0x0000
	AttrSupportedStreamingProtocols uint32 = 0x0001
)

// Command IDs.
const (
	CmdLaunchContent uint32 = 0x00
	CmdLaunchURL     uint32 = 0x01
)

// LaunchContentRequest is the request payload for the LaunchContent command.
type LaunchContentRequest struct {
	Search              uint8  `tlv:"0,uint"`
	AutoPlay            bool   `tlv:"1,bool"`
	Data                string `tlv:"2,utf8"`
	PlaybackPreferences uint8  `tlv:"3,uint"`
	UseCurrentContext   bool   `tlv:"4,bool"`
}

// LaunchURLRequest is the request payload for the LaunchURL command.
type LaunchURLRequest struct {
	ContentURL          string `tlv:"0,utf8"`
	DisplayString       string `tlv:"1,utf8"`
	BrandingInformation uint8  `tlv:"2,uint"`
	PlaybackPreferences uint8  `tlv:"3,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CS", Name: "ContentSearch"},
			{Bit: 1, Code: "UP", Name: "URLPlayback"},
			{Bit: 2, Code: "AS", Name: "AdvancedSeek"},
			{Bit: 3, Code: "TT", Name: "TextTracks"},
			{Bit: 4, Code: "AT", Name: "AudioTracks"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrAcceptHeader, Name: "AcceptHeader", DisplayName: "AcceptHeader", Type: "list", Readable: true},
			{ID: AttrSupportedStreamingProtocols, Name: "SupportedStreamingProtocols", DisplayName: "SupportedStreamingProtocols", Type: "bitmap8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdLaunchContent, Name: "LaunchContent", DisplayName: "LaunchContent", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Search", DisplayName: "Search", Type: "struct"},
				{ID: 1, Name: "AutoPlay", DisplayName: "AutoPlay", Type: "bool"},
				{ID: 2, Name: "Data", DisplayName: "Data", Type: "string", Optional: true},
				{ID: 3, Name: "PlaybackPreferences", DisplayName: "PlaybackPreferences", Type: "struct", Optional: true},
				{ID: 4, Name: "UseCurrentContext", DisplayName: "UseCurrentContext", Type: "bool", Optional: true},
			}},
			{ID: CmdLaunchURL, Name: "LaunchURL", DisplayName: "LaunchURL", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ContentURL", DisplayName: "ContentURL", Type: "string"},
				{ID: 1, Name: "DisplayString", DisplayName: "DisplayString", Type: "string", Optional: true},
				{ID: 2, Name: "BrandingInformation", DisplayName: "BrandingInformation", Type: "struct", Optional: true},
				{ID: 3, Name: "PlaybackPreferences", DisplayName: "PlaybackPreferences", Type: "struct", Optional: true},
			}},
		},
	})
}
