// Code generated by cmd/codegen; DO NOT EDIT.

// Package cameraavsettingsuserlevelmanagement implements the Matter Camera AV Settings User Level Management cluster (0x0552).
package cameraavsettingsuserlevelmanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Camera AV Settings User Level Management.
	ID uint32 = 0x0552
	// Name is the CLI-friendly cluster name.
	Name = "CameraAVSettingsUserLevelManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Camera AV Settings User Level Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureDigitalPTZ        uint32 = 1 << 0 // DPTZ
	FeatureMechanicalPan     uint32 = 1 << 1 // MPAN
	FeatureMechanicalTilt    uint32 = 1 << 2 // MTILT
	FeatureMechanicalZoom    uint32 = 1 << 3 // MZOOM
	FeatureMechanicalPresets uint32 = 1 << 4 // MPRESETS
)

// Attribute IDs.
const (
	AttrMPTZPosition  uint32 = 0x0000
	AttrMaxPresets    uint32 = 0x0001
	AttrMPTZPresets   uint32 = 0x0002
	AttrDPTZStreams   uint32 = 0x0003
	AttrZoomMax       uint32 = 0x0004
	AttrTiltMin       uint32 = 0x0005
	AttrTiltMax       uint32 = 0x0006
	AttrPanMin        uint32 = 0x0007
	AttrPanMax        uint32 = 0x0008
	AttrMovementState uint32 = 0x0009
)

// Command IDs.
const (
	CmdMPTZSetPosition  uint32 = 0x00
	CmdMPTZRelativeMove uint32 = 0x01
	CmdMPTZMoveToPreset uint32 = 0x02
	CmdMPTZSavePreset   uint32 = 0x03
	CmdMPTZRemovePreset uint32 = 0x04
	CmdDPTZSetViewport  uint32 = 0x05
	CmdDPTZRelativeMove uint32 = 0x06
)

// MPTZSetPositionRequest is the request payload for the MPTZSetPosition command.
type MPTZSetPositionRequest struct {
	Pan  int16 `tlv:"0,int"`
	Tilt int16 `tlv:"1,int"`
	Zoom uint8 `tlv:"2,uint"`
}

// MPTZRelativeMoveRequest is the request payload for the MPTZRelativeMove command.
type MPTZRelativeMoveRequest struct {
	PanDelta  int16 `tlv:"0,int"`
	TiltDelta int16 `tlv:"1,int"`
	ZoomDelta int8  `tlv:"2,int"`
}

// MPTZMoveToPresetRequest is the request payload for the MPTZMoveToPreset command.
type MPTZMoveToPresetRequest struct {
	PresetID uint8 `tlv:"0,uint"`
}

// MPTZSavePresetRequest is the request payload for the MPTZSavePreset command.
type MPTZSavePresetRequest struct {
	PresetID uint8  `tlv:"0,uint"`
	Name     string `tlv:"1,utf8"`
}

// MPTZRemovePresetRequest is the request payload for the MPTZRemovePreset command.
type MPTZRemovePresetRequest struct {
	PresetID uint8 `tlv:"0,uint"`
}

// DPTZSetViewportRequest is the request payload for the DPTZSetViewport command.
type DPTZSetViewportRequest struct {
	VideoStreamID uint8 `tlv:"0,uint"`
	Viewport      uint8 `tlv:"1,uint"`
}

// DPTZRelativeMoveRequest is the request payload for the DPTZRelativeMove command.
type DPTZRelativeMoveRequest struct {
	VideoStreamID uint8 `tlv:"0,uint"`
	DeltaX        int16 `tlv:"1,int"`
	DeltaY        int16 `tlv:"2,int"`
	ZoomDelta     int8  `tlv:"3,int"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DPTZ", Name: "DigitalPTZ"},
			{Bit: 1, Code: "MPAN", Name: "MechanicalPan"},
			{Bit: 2, Code: "MTILT", Name: "MechanicalTilt"},
			{Bit: 3, Code: "MZOOM", Name: "MechanicalZoom"},
			{Bit: 4, Code: "MPRESETS", Name: "MechanicalPresets"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrMPTZPosition, Name: "MPTZPosition", DisplayName: "MPTZPosition", Type: "struct", Readable: true},
			{ID: AttrMaxPresets, Name: "MaxPresets", DisplayName: "MaxPresets", Type: "uint8", Readable: true},
			{ID: AttrMPTZPresets, Name: "MPTZPresets", DisplayName: "MPTZPresets", Type: "list", Readable: true},
			{ID: AttrDPTZStreams, Name: "DPTZStreams", DisplayName: "DPTZStreams", Type: "list", Readable: true},
			{ID: AttrZoomMax, Name: "ZoomMax", DisplayName: "ZoomMax", Type: "uint8", Readable: true},
			{ID: AttrTiltMin, Name: "TiltMin", DisplayName: "TiltMin", Type: "int16", Readable: true},
			{ID: AttrTiltMax, Name: "TiltMax", DisplayName: "TiltMax", Type: "int16", Readable: true},
			{ID: AttrPanMin, Name: "PanMin", DisplayName: "PanMin", Type: "int16", Readable: true},
			{ID: AttrPanMax, Name: "PanMax", DisplayName: "PanMax", Type: "int16", Readable: true},
			{ID: AttrMovementState, Name: "MovementState", DisplayName: "MovementState", Type: "enum8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdMPTZSetPosition, Name: "MPTZSetPosition", DisplayName: "MPTZSetPosition", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Pan", DisplayName: "Pan", Type: "int16", Optional: true},
				{ID: 1, Name: "Tilt", DisplayName: "Tilt", Type: "int16", Optional: true},
				{ID: 2, Name: "Zoom", DisplayName: "Zoom", Type: "uint8", Optional: true},
			}},
			{ID: CmdMPTZRelativeMove, Name: "MPTZRelativeMove", DisplayName: "MPTZRelativeMove", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PanDelta", DisplayName: "PanDelta", Type: "int16", Optional: true},
				{ID: 1, Name: "TiltDelta", DisplayName: "TiltDelta", Type: "int16", Optional: true},
				{ID: 2, Name: "ZoomDelta", DisplayName: "ZoomDelta", Type: "int8", Optional: true},
			}},
			{ID: CmdMPTZMoveToPreset, Name: "MPTZMoveToPreset", DisplayName: "MPTZMoveToPreset", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PresetID", DisplayName: "PresetID", Type: "uint8"},
			}},
			{ID: CmdMPTZSavePreset, Name: "MPTZSavePreset", DisplayName: "MPTZSavePreset", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PresetID", DisplayName: "PresetID", Type: "uint8", Optional: true},
				{ID: 1, Name: "Name", DisplayName: "Name", Type: "string"},
			}},
			{ID: CmdMPTZRemovePreset, Name: "MPTZRemovePreset", DisplayName: "MPTZRemovePreset", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "PresetID", DisplayName: "PresetID", Type: "uint8"},
			}},
			{ID: CmdDPTZSetViewport, Name: "DPTZSetViewport", DisplayName: "DPTZSetViewport", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VideoStreamID", DisplayName: "VideoStreamID", Type: "uint8"},
				{ID: 1, Name: "Viewport", DisplayName: "Viewport", Type: "struct"},
			}},
			{ID: CmdDPTZRelativeMove, Name: "DPTZRelativeMove", DisplayName: "DPTZRelativeMove", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "VideoStreamID", DisplayName: "VideoStreamID", Type: "uint8"},
				{ID: 1, Name: "DeltaX", DisplayName: "DeltaX", Type: "int16", Optional: true},
				{ID: 2, Name: "DeltaY", DisplayName: "DeltaY", Type: "int16", Optional: true},
				{ID: 3, Name: "ZoomDelta", DisplayName: "ZoomDelta", Type: "int8", Optional: true},
			}},
		},
	})
}
