// Code generated by cmd/codegen; DO NOT EDIT.

// Package userlabel implements the Matter User Label cluster (0x0041).
package userlabel

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for User Label.
	ID uint32 = 0x0041
	// Name is the CLI-friendly cluster name.
	Name = "UserLabel"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "User Label"
)

// Attribute IDs.
const (
	AttrLabelList uint32 = 0x0000
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrLabelList, Name: "LabelList", DisplayName: "LabelList", Type: "list", Readable: true, Writable: true},
		},
	})
}
