// Code generated by cmd/codegen; DO NOT EDIT.

// Package occupancysensing implements the Matter Occupancy Sensing cluster (0x0406).
package occupancysensing

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Occupancy Sensing.
	ID uint32 = 0x0406
	// Name is the CLI-friendly cluster name.
	Name = "OccupancySensing"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Occupancy Sensing"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureOther           uint32 = 1 << 0 // OTHER
	FeaturePassiveInfrared uint32 = 1 << 1 // PIR
	FeatureUltrasonic      uint32 = 1 << 2 // US
	FeaturePhysicalContact uint32 = 1 << 3 // PHY
	FeatureActiveInfrared  uint32 = 1 << 4 // AIR
	FeatureRadar           uint32 = 1 << 5 // RAD
	FeatureRFSensing       uint32 = 1 << 6 // RFS
	FeatureVision          uint32 = 1 << 7 // VIS
)

// Attribute IDs.
const (
	AttrOccupancy                                    uint32 = 0x0000
	AttrOccupancySensorType                          uint32 = 0x0001
	AttrOccupancySensorTypeBitmap                    uint32 = 0x0002
	AttrHoldTime                                     uint32 = 0x0003
	AttrHoldTimeLimits                               uint32 = 0x0004
	AttrPIROccupiedToUnoccupiedDelay                 uint32 = 0x0010
	AttrPIRUnoccupiedToOccupiedDelay                 uint32 = 0x0011
	AttrPIRUnoccupiedToOccupiedThreshold             uint32 = 0x0012
	AttrUltrasonicOccupiedToUnoccupiedDelay          uint32 = 0x0020
	AttrUltrasonicUnoccupiedToOccupiedDelay          uint32 = 0x0021
	AttrUltrasonicUnoccupiedToOccupiedThreshold      uint32 = 0x0022
	AttrPhysicalContactOccupiedToUnoccupiedDelay     uint32 = 0x0030
	AttrPhysicalContactUnoccupiedToOccupiedDelay     uint32 = 0x0031
	AttrPhysicalContactUnoccupiedToOccupiedThreshold uint32 = 0x0032
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "OTHER", Name: "Other"},
			{Bit: 1, Code: "PIR", Name: "PassiveInfrared"},
			{Bit: 2, Code: "US", Name: "Ultrasonic"},
			{Bit: 3, Code: "PHY", Name: "PhysicalContact"},
			{Bit: 4, Code: "AIR", Name: "ActiveInfrared"},
			{Bit: 5, Code: "RAD", Name: "Radar"},
			{Bit: 6, Code: "RFS", Name: "RFSensing"},
			{Bit: 7, Code: "VIS", Name: "Vision"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrOccupancy, Name: "Occupancy", DisplayName: "Occupancy", Type: "bitmap8", Readable: true},
			{ID: AttrOccupancySensorType, Name: "OccupancySensorType", DisplayName: "OccupancySensorType", Type: "enum8", Readable: true},
			{ID: AttrOccupancySensorTypeBitmap, Name: "OccupancySensorTypeBitmap", DisplayName: "OccupancySensorTypeBitmap", Type: "bitmap8", Readable: true},
			{ID: AttrHoldTime, Name: "HoldTime", DisplayName: "HoldTime", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrHoldTimeLimits, Name: "HoldTimeLimits", DisplayName: "HoldTimeLimits", Type: "struct", Readable: true},
			{ID: AttrPIROccupiedToUnoccupiedDelay, Name: "PIROccupiedToUnoccupiedDelay", DisplayName: "PIROccupiedToUnoccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrPIRUnoccupiedToOccupiedDelay, Name: "PIRUnoccupiedToOccupiedDelay", DisplayName: "PIRUnoccupiedToOccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrPIRUnoccupiedToOccupiedThreshold, Name: "PIRUnoccupiedToOccupiedThreshold", DisplayName: "PIRUnoccupiedToOccupiedThreshold", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrUltrasonicOccupiedToUnoccupiedDelay, Name: "UltrasonicOccupiedToUnoccupiedDelay", DisplayName: "UltrasonicOccupiedToUnoccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrUltrasonicUnoccupiedToOccupiedDelay, Name: "UltrasonicUnoccupiedToOccupiedDelay", DisplayName: "UltrasonicUnoccupiedToOccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrUltrasonicUnoccupiedToOccupiedThreshold, Name: "UltrasonicUnoccupiedToOccupiedThreshold", DisplayName: "UltrasonicUnoccupiedToOccupiedThreshold", Type: "uint8", Readable: true, Writable: true},
			{ID: AttrPhysicalContactOccupiedToUnoccupiedDelay, Name: "PhysicalContactOccupiedToUnoccupiedDelay", DisplayName: "PhysicalContactOccupiedToUnoccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrPhysicalContactUnoccupiedToOccupiedDelay, Name: "PhysicalContactUnoccupiedToOccupiedDelay", DisplayName: "PhysicalContactUnoccupiedToOccupiedDelay", Type: "uint16", Readable: true, Writable: true},
			{ID: AttrPhysicalContactUnoccupiedToOccupiedThreshold, Name: "PhysicalContactUnoccupiedToOccupiedThreshold", DisplayName: "PhysicalContactUnoccupiedToOccupiedThreshold", Type: "uint8", Readable: true, Writable: true},
		},
	})
}
