// Code generated by cmd/codegen; DO NOT EDIT.

// Package applicationlauncher implements the Matter Application Launcher cluster (0x050C).
package applicationlauncher

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Application Launcher.
	ID uint32 = 0x050C
	// Name is the CLI-friendly cluster name.
	Name = "ApplicationLauncher"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Application Launcher"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureApplicationPlatform uint32 = 1 << 0 // AP
)

// Attribute IDs.
const (
	AttrCatalogList uint32 = 0x0000
	AttrCurrentApp  uint32 = 0x0001
)

// Command IDs.
const (
	CmdLaunchApp uint32 = 0x00
	CmdStopApp   uint32 = 0x01
	CmdHideApp   uint32 = 0x02
)

// LaunchAppRequest is the request payload for the LaunchApp command.
type LaunchAppRequest struct {
	Application uint8  `tlv:"0,uint"`
	Data        []byte `tlv:"1,bytes"`
}

// StopAppRequest is the request payload for the StopApp command.
type StopAppRequest struct {
	Application uint8 `tlv:"0,uint"`
}

// HideAppRequest is the request payload for the HideApp command.
type HideAppRequest struct {
	Application uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "AP", Name: "ApplicationPlatform"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCatalogList, Name: "CatalogList", DisplayName: "CatalogList", Type: "list", Readable: true},
			{ID: AttrCurrentApp, Name: "CurrentApp", DisplayName: "CurrentApp", Type: "struct", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdLaunchApp, Name: "LaunchApp", DisplayName: "LaunchApp", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Application", DisplayName: "Application", Type: "struct"},
				{ID: 1, Name: "Data", DisplayName: "Data", Type: "octets", Optional: true},
			}},
			{ID: CmdStopApp, Name: "StopApp", DisplayName: "StopApp", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Application", DisplayName: "Application", Type: "struct"},
			}},
			{ID: CmdHideApp, Name: "HideApp", DisplayName: "HideApp", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Application", DisplayName: "Application", Type: "struct"},
			}},
		},
	})
}
