// Copyright 2026 matter-cli contributors
// SPDX-License-Identifier: Apache-2.0

// gen-vendordb fetches the current vendor list from the CSA Distributed
// Compliance Ledger (DCL) and regenerates internal/vendordb/vendors.gen.go.
//
// Usage:
//
//	go run ./cmd/gen-vendordb [-out <path>]
//
// The -out flag defaults to internal/vendordb/vendors.gen.go relative to the
// module root (i.e. the directory containing go.mod).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"
)

const dclBaseURL = "https://on.dcl.csa-iot.org/dcl/vendorinfo/vendors"

// dclVendorInfo mirrors the JSON shape returned by the DCL API.
type dclVendorInfo struct {
	VendorID             int    `json:"vendorID"`
	VendorName           string `json:"vendorName"`
	CompanyPreferredName string `json:"companyPreferredName"`
}

type dclPage struct {
	VendorInfo []dclVendorInfo `json:"vendorInfo"`
	Pagination struct {
		NextKey string `json:"next_key"`
	} `json:"pagination"`
}

// vendor holds the cleaned-up data used for code generation.
type vendor struct {
	ID   uint16
	Name string
}

// displayName picks the best human-readable name for a DCL entry.
// It prefers companyPreferredName when it is set and meaningfully different
// from the vendorName, then falls back to vendorName.
func displayName(v dclVendorInfo) string {
	preferred := strings.TrimSpace(v.CompanyPreferredName)
	name := strings.TrimSpace(v.VendorName)

	if preferred != "" {
		return preferred
	}
	return name
}

func fetchAll() ([]vendor, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	var result []vendor
	nextKey := ""

	for {
		reqURL := dclBaseURL
		if nextKey != "" {
			reqURL += "?pagination.key=" + url.QueryEscape(nextKey)
		}

		resp, err := client.Get(reqURL)
		if err != nil {
			return nil, fmt.Errorf("GET %s: %w", reqURL, err)
		}
		body, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			return nil, fmt.Errorf("reading response: %w", err)
		}
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, reqURL)
		}

		var page dclPage
		if err := json.Unmarshal(body, &page); err != nil {
			return nil, fmt.Errorf("decoding JSON: %w", err)
		}

		for _, vi := range page.VendorInfo {
			if vi.VendorID < 0 || vi.VendorID > 0xFFFF {
				continue // outside uint16 range — skip
			}
			name := displayName(vi)
			if name == "" || strings.EqualFold(name, "none") {
				continue
			}
			result = append(result, vendor{ID: uint16(vi.VendorID), Name: name})
		}

		nextKey = page.Pagination.NextKey
		if nextKey == "" {
			break
		}
		log.Printf("fetched %d vendors so far, fetching next page…", len(result))
	}

	// Append well-known test vendor IDs (reserved range 0xFFF1–0xFFF4).
	// These are never registered on the DCL but are used extensively by the
	// Matter SDK and development tools.
	testVendors := []vendor{
		{0xFFF1, "Test Vendor 1"},
		{0xFFF2, "Test Vendor 2"},
		{0xFFF3, "Test Vendor 3"},
		{0xFFF4, "Test Vendor 4"},
	}
	result = append(result, testVendors...)

	// Sort by ID for a stable, diff-friendly output.
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })

	return result, nil
}

var fileTemplate = template.Must(template.New("vendors").Parse(`// Copyright 2026 matter-cli contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen-vendordb. DO NOT EDIT.
// Source: https://on.dcl.csa-iot.org/dcl/vendorinfo/vendors
// Generated: {{ .Timestamp }}
//
// Regenerate with:
//
//	go generate ./internal/vendordb/...

package vendordb

//go:generate go run ../../cmd/gen-vendordb -out vendors.gen.go

// vendors maps Matter vendor IDs to their registered vendor names from the
// CSA Distributed Compliance Ledger (DCL).
var vendors = map[uint16]string{
{{- range .Vendors}}
	{{ printf "%-6d" .ID }}: {{ printf "%q" .Name }},
{{- end}}

	// Well-known test vendor IDs used by the Matter SDK and development tools.
	// Range 0xFFF1–0xFFF4 is reserved for testing (not registered on the DCL).
}
`))

func main() {
	outFlag := flag.String("out", "vendors.gen.go", "output file path")
	flag.Parse()

	log.SetFlags(0)
	log.SetPrefix("gen-vendordb: ")

	log.Println("fetching vendor list from DCL…")
	vendors, err := fetchAll()
	if err != nil {
		log.Fatalf("fetch failed: %v", err)
	}
	log.Printf("fetched %d vendors total", len(vendors))

	// Separate out the test vendors so the template can render them in a
	// dedicated comment block at the end.
	var regular, test []vendor
	for _, v := range vendors {
		if v.ID >= 0xFFF1 && v.ID <= 0xFFF4 {
			test = append(test, v)
		} else {
			regular = append(regular, v)
		}
	}

	type templateData struct {
		Timestamp string
		Vendors   []vendor
		Test      []vendor
	}

	data := templateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Vendors:   regular,
		Test:      test,
	}

	// Redefine the template here to handle the test section properly.
	tmpl := template.Must(template.New("vendors").Parse(`// Copyright 2026 matter-cli contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen-vendordb. DO NOT EDIT.
// Source: https://on.dcl.csa-iot.org/dcl/vendorinfo/vendors
// Generated: {{ .Timestamp }}
//
// Regenerate with:
//
//	go generate ./internal/vendordb/...

package vendordb

//go:generate go run ../../cmd/gen-vendordb -out vendors.gen.go

// vendors maps Matter vendor IDs to their registered vendor names from the
// CSA Distributed Compliance Ledger (DCL).
var vendors = map[uint16]string{
{{- range .Vendors}}
	{{ printf "%-6d" .ID }}: {{ printf "%q" .Name }},
{{- end}}

	// Well-known test vendor IDs used by the Matter SDK and development tools.
	// Range 0xFFF1–0xFFF4 is reserved for testing (not registered on the DCL).
{{- range .Test}}
	{{ printf "0x%04X" .ID }}: {{ printf "%q" .Name }},
{{- end}}
}
`))

	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		log.Fatalf("template: %v", err)
	}

	if err := os.WriteFile(*outFlag, []byte(sb.String()), 0644); err != nil {
		log.Fatalf("write %s: %v", *outFlag, err)
	}
	log.Printf("wrote %s (%d bytes)", *outFlag, len(sb.String()))
}
