// Code generated by cmd/codegen; DO NOT EDIT.

// Package accesscontrol implements the Matter Access Control cluster (0x001F).
package accesscontrol

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Access Control.
	ID uint32 = 0x001F
	// Name is the CLI-friendly cluster name.
	Name = "AccessControl"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Access Control"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureExtension     uint32 = 1 << 0 // EXTS
	FeatureManagedDevice uint32 = 1 << 1 // MNGD
)

// Attribute IDs.
const (
	AttrACL                           uint32 = 0x0000
	AttrExtension                     uint32 = 0x0001
	AttrSubjectsPerAccessControlEntry uint32 = 0x0002
	AttrTargetsPerAccessControlEntry  uint32 = 0x0003
	AttrAccessControlEntriesPerFabric uint32 = 0x0004
	AttrCommissioningARL              uint32 = 0x0005
	AttrARL                           uint32 = 0x0006
)

// Command IDs.
const (
	CmdReviewFabricRestrictions uint32 = 0x00
)

// ReviewFabricRestrictionsRequest is the request payload for the ReviewFabricRestrictions command.
type ReviewFabricRestrictionsRequest struct {
	ARL uint8 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "EXTS", Name: "Extension"},
			{Bit: 1, Code: "MNGD", Name: "ManagedDevice"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrACL, Name: "ACL", DisplayName: "ACL", Type: "list", Readable: true, Writable: true},
			{ID: AttrExtension, Name: "Extension", DisplayName: "Extension", Type: "list", Readable: true, Writable: true},
			{ID: AttrSubjectsPerAccessControlEntry, Name: "SubjectsPerAccessControlEntry", DisplayName: "SubjectsPerAccessControlEntry", Type: "uint16", Readable: true},
			{ID: AttrTargetsPerAccessControlEntry, Name: "TargetsPerAccessControlEntry", DisplayName: "TargetsPerAccessControlEntry", Type: "uint16", Readable: true},
			{ID: AttrAccessControlEntriesPerFabric, Name: "AccessControlEntriesPerFabric", DisplayName: "AccessControlEntriesPerFabric", Type: "uint16", Readable: true},
			{ID: AttrCommissioningARL, Name: "CommissioningARL", DisplayName: "CommissioningARL", Type: "list", Readable: true},
			{ID: AttrARL, Name: "ARL", DisplayName: "ARL", Type: "list", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdReviewFabricRestrictions, Name: "ReviewFabricRestrictions", DisplayName: "ReviewFabricRestrictions", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "ARL", DisplayName: "ARL", Type: "list"},
			}},
		},
	})
}
