// Code generated by cmd/codegen; DO NOT EDIT.

// Package contentappobserver implements the Matter Content App Observer cluster (0x0510).
package contentappobserver

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Content App Observer.
	ID uint32 = 0x0510
	// Name is the CLI-friendly cluster name.
	Name = "ContentAppObserver"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Content App Observer"
)

// Command IDs.
const (
	CmdContentAppMessage uint32 = 0x00
)

// ContentAppMessageRequest is the request payload for the ContentAppMessage command.
type ContentAppMessageRequest struct {
	Data         string `tlv:"0,utf8"`
	EncodingHint string `tlv:"1,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Commands: []clusters.CommandInfo{
			{ID: CmdContentAppMessage, Name: "ContentAppMessage", DisplayName: "ContentAppMessage", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Data", DisplayName: "Data", Type: "string"},
				{ID: 1, Name: "EncodingHint", DisplayName: "EncodingHint", Type: "string", Optional: true},
			}},
		},
	})
}
