// Code generated by cmd/codegen; DO NOT EDIT.

// Package audiooutput implements the Matter Audio Output cluster (0x050B).
package audiooutput

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Audio Output.
	ID uint32 = 0x050B
	// Name is the CLI-friendly cluster name.
	Name = "AudioOutput"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Audio Output"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureNameUpdates uint32 = 1 << 0 // NU
)

// Attribute IDs.
const (
	AttrOutputList    uint32 = 0x0000
	AttrCurrentOutput uint32 = 0x0001
)

// Command IDs.
const (
	CmdSelectOutput uint32 = 0x00
	CmdRenameOutput uint32 = 0x01
)

// SelectOutputRequest is the request payload for the SelectOutput command.
type SelectOutputRequest struct {
	Index uint8 `tlv:"0,uint"`
}

// RenameOutputRequest is the request payload for the RenameOutput command.
type RenameOutputRequest struct {
	Index uint8  `tlv:"0,uint"`
	Name  string `tlv:"1,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "NU", Name: "NameUpdates"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrOutputList, Name: "OutputList", DisplayName: "OutputList", Type: "list", Readable: true},
			{ID: AttrCurrentOutput, Name: "CurrentOutput", DisplayName: "CurrentOutput", Type: "uint8", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdSelectOutput, Name: "SelectOutput", DisplayName: "SelectOutput", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Index", DisplayName: "Index", Type: "uint8"},
			}},
			{ID: CmdRenameOutput, Name: "RenameOutput", DisplayName: "RenameOutput", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Index", DisplayName: "Index", Type: "uint8"},
				{ID: 1, Name: "Name", DisplayName: "Name", Type: "string"},
			}},
		},
	})
}
