// Code generated by cmd/codegen; DO NOT EDIT.

// Package ovencavityoperationalstate implements the Matter Oven Cavity Operational State cluster (0x0048).
package ovencavityoperationalstate

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Oven Cavity Operational State.
	ID uint32 = 0x0048
	// Name is the CLI-friendly cluster name.
	Name = "OvenCavityOperationalState"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Oven Cavity Operational State"
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
	})
}
