// Code generated by cmd/codegen; DO NOT EDIT.

// Package wifinetworkmanagement implements the Matter Wi-Fi Network Management cluster (0x0451).
package wifinetworkmanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Wi-Fi Network Management.
	ID uint32 = 0x0451
	// Name is the CLI-friendly cluster name.
	Name = "WiFiNetworkManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Wi-Fi Network Management"
)

// Attribute IDs.
const (
	AttrSSID                uint32 = 0x0000
	AttrPassphraseSurrogate uint32 = 0x0001
)

// Command IDs.
const (
	CmdNetworkPassphraseRequest uint32 = 0x00
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSSID, Name: "SSID", DisplayName: "SSID", Type: "octets", Readable: true, Nullable: true},
			{ID: AttrPassphraseSurrogate, Name: "PassphraseSurrogate", DisplayName: "PassphraseSurrogate", Type: "uint64", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdNetworkPassphraseRequest, Name: "NetworkPassphraseRequest", DisplayName: "NetworkPassphraseRequest", HasResponse: true},
		},
	})
}
