// Code generated by cmd/codegen; DO NOT EDIT.

// Package ovenmode implements the Matter Oven Mode cluster (0x0049).
package ovenmode

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Oven Mode.
	ID uint32 = 0x0049
	// Name is the CLI-friendly cluster name.
	Name = "OvenMode"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Oven Mode"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureOnOff uint32 = 1 << 0 // DEPONOFF
)

// Attribute IDs.
const (
	AttrSupportedModes uint32 = 0x0000
	AttrCurrentMode    uint32 = 0x0001
	AttrStartUpMode    uint32 = 0x0002
	AttrOnMode         uint32 = 0x0003
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "DEPONOFF", Name: "OnOff"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSupportedModes, Name: "SupportedModes", DisplayName: "SupportedModes", Type: "uint8", Readable: false},
			{ID: AttrCurrentMode, Name: "CurrentMode", DisplayName: "CurrentMode", Type: "uint8", Readable: false},
			{ID: AttrStartUpMode, Name: "StartUpMode", DisplayName: "StartUpMode", Type: "uint8", Readable: false},
			{ID: AttrOnMode, Name: "OnMode", DisplayName: "OnMode", Type: "uint8", Readable: false},
		},
	})
}
