// Code generated by cmd/codegen; DO NOT EDIT.

// Package icdmanagement implements the Matter ICD Management cluster (0x0046).
package icdmanagement

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for ICD Management.
	ID uint32 = 0x0046
	// Name is the CLI-friendly cluster name.
	Name = "ICDManagement"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "ICD Management"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureCheckInProtocolSupport uint32 = 1 << 0 // CIP
	FeatureUserActiveModeTrigger  uint32 = 1 << 1 // UAT
	FeatureLongIdleTimeSupport    uint32 = 1 << 2 // LITS
	FeatureDynamicSitLitSupport   uint32 = 1 << 3 // DSLS
)

// Attribute IDs.
const (
	AttrIdleModeDuration                 uint32 = 0x0000
	AttrActiveModeDuration               uint32 = 0x0001
	AttrActiveModeThreshold              uint32 = 0x0002
	AttrRegisteredClients                uint32 = 0x0003
	AttrICDCounter                       uint32 = 0x0004
	AttrClientsSupportedPerFabric        uint32 = 0x0005
	AttrUserActiveModeTriggerHint        uint32 = 0x0006
	AttrUserActiveModeTriggerInstruction uint32 = 0x0007
	AttrOperatingMode                    uint32 = 0x0008
	AttrMaximumCheckInBackoff            uint32 = 0x0009
)

// Command IDs.
const (
	CmdRegisterClient    uint32 = 0x00
	CmdUnregisterClient  uint32 = 0x02
	CmdStayActiveRequest uint32 = 0x03
)

// RegisterClientRequest is the request payload for the RegisterClient command.
type RegisterClientRequest struct {
	CheckInNodeID    uint64 `tlv:"0,uint"`
	MonitoredSubject uint64 `tlv:"1,uint"`
	Key              []byte `tlv:"2,bytes"`
	VerificationKey  []byte `tlv:"3,bytes"`
	ClientType       uint8  `tlv:"4,uint"`
}

// UnregisterClientRequest is the request payload for the UnregisterClient command.
type UnregisterClientRequest struct {
	CheckInNodeID   uint64 `tlv:"0,uint"`
	VerificationKey []byte `tlv:"1,bytes"`
}

// StayActiveRequestRequest is the request payload for the StayActiveRequest command.
type StayActiveRequestRequest struct {
	StayActiveDuration uint32 `tlv:"0,uint"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "CIP", Name: "CheckInProtocolSupport"},
			{Bit: 1, Code: "UAT", Name: "UserActiveModeTrigger"},
			{Bit: 2, Code: "LITS", Name: "LongIdleTimeSupport"},
			{Bit: 3, Code: "DSLS", Name: "DynamicSitLitSupport"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrIdleModeDuration, Name: "IdleModeDuration", DisplayName: "IdleModeDuration", Type: "uint32", Readable: true},
			{ID: AttrActiveModeDuration, Name: "ActiveModeDuration", DisplayName: "ActiveModeDuration", Type: "uint32", Readable: true},
			{ID: AttrActiveModeThreshold, Name: "ActiveModeThreshold", DisplayName: "ActiveModeThreshold", Type: "uint16", Readable: true},
			{ID: AttrRegisteredClients, Name: "RegisteredClients", DisplayName: "RegisteredClients", Type: "list", Readable: true},
			{ID: AttrICDCounter, Name: "ICDCounter", DisplayName: "ICDCounter", Type: "uint32", Readable: true},
			{ID: AttrClientsSupportedPerFabric, Name: "ClientsSupportedPerFabric", DisplayName: "ClientsSupportedPerFabric", Type: "uint16", Readable: true},
			{ID: AttrUserActiveModeTriggerHint, Name: "UserActiveModeTriggerHint", DisplayName: "UserActiveModeTriggerHint", Type: "bitmap8", Readable: true},
			{ID: AttrUserActiveModeTriggerInstruction, Name: "UserActiveModeTriggerInstruction", DisplayName: "UserActiveModeTriggerInstruction", Type: "string", Readable: true},
			{ID: AttrOperatingMode, Name: "OperatingMode", DisplayName: "OperatingMode", Type: "enum8", Readable: true},
			{ID: AttrMaximumCheckInBackoff, Name: "MaximumCheckInBackoff", DisplayName: "MaximumCheckInBackoff", Type: "uint32", Readable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdRegisterClient, Name: "RegisterClient", DisplayName: "RegisterClient", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CheckInNodeID", DisplayName: "CheckInNodeID", Type: "uint64"},
				{ID: 1, Name: "MonitoredSubject", DisplayName: "MonitoredSubject", Type: "uint64"},
				{ID: 2, Name: "Key", DisplayName: "Key", Type: "octets"},
				{ID: 3, Name: "VerificationKey", DisplayName: "VerificationKey", Type: "octets", Optional: true},
				{ID: 4, Name: "ClientType", DisplayName: "ClientType", Type: "enum8"},
			}},
			{ID: CmdUnregisterClient, Name: "UnregisterClient", DisplayName: "UnregisterClient", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "CheckInNodeID", DisplayName: "CheckInNodeID", Type: "uint64"},
				{ID: 1, Name: "VerificationKey", DisplayName: "VerificationKey", Type: "octets", Optional: true},
			}},
			{ID: CmdStayActiveRequest, Name: "StayActiveRequest", DisplayName: "StayActiveRequest", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "StayActiveDuration", DisplayName: "StayActiveDuration", Type: "uint32"},
			}},
		},
	})
}
