// Code generated by cmd/codegen; DO NOT EDIT.

// Package thermostatuserinterfaceconfiguration implements the Matter Thermostat User Interface Configuration cluster (0x0204).
package thermostatuserinterfaceconfiguration

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Thermostat User Interface Configuration.
	ID uint32 = 0x0204
	// Name is the CLI-friendly cluster name.
	Name = "ThermostatUserInterfaceConfiguration"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Thermostat User Interface Configuration"
)

// Attribute IDs.
const (
	AttrTemperatureDisplayMode        uint32 = 0x0000
	AttrKeypadLockout                 uint32 = 0x0001
	AttrScheduleProgrammingVisibility uint32 = 0x0002
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrTemperatureDisplayMode, Name: "TemperatureDisplayMode", DisplayName: "TemperatureDisplayMode", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrKeypadLockout, Name: "KeypadLockout", DisplayName: "KeypadLockout", Type: "enum8", Readable: true, Writable: true},
			{ID: AttrScheduleProgrammingVisibility, Name: "ScheduleProgrammingVisibility", DisplayName: "ScheduleProgrammingVisibility", Type: "enum8", Readable: true, Writable: true},
		},
	})
}
