// Code generated by cmd/codegen; DO NOT EDIT.

// Package mediaplayback implements the Matter Media Playback cluster (0x0506).
package mediaplayback

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Media Playback.
	ID uint32 = 0x0506
	// Name is the CLI-friendly cluster name.
	Name = "MediaPlayback"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Media Playback"
)

// Feature bits for the FeatureMap attribute.
const (
	FeatureAdvancedSeek  uint32 = 1 << 0 // AS
	FeatureVariableSpeed uint32 = 1 << 1 // VS
	FeatureTextTracks    uint32 = 1 << 2 // TT
	FeatureAudioTracks   uint32 = 1 << 3 // AT
	FeatureAudioAdvance  uint32 = 1 << 4 // AA
)

// Attribute IDs.
const (
	AttrCurrentState         uint32 = 0x0000
	AttrStartTime            uint32 = 0x0001
	AttrDuration             uint32 = 0x0002
	AttrSampledPosition      uint32 = 0x0003
	AttrPlaybackSpeed        uint32 = 0x0004
	AttrSeekRangeEnd         uint32 = 0x0005
	AttrSeekRangeStart       uint32 = 0x0006
	AttrActiveAudioTrack     uint32 = 0x0007
	AttrAvailableAudioTracks uint32 = 0x0008
	AttrActiveTextTrack      uint32 = 0x0009
	AttrAvailableTextTracks  uint32 = 0x000A
)

// Command IDs.
const (
	CmdPlay                uint32 = 0x00
	CmdPause               uint32 = 0x01
	CmdStop                uint32 = 0x02
	CmdStartOver           uint32 = 0x03
	CmdPrevious            uint32 = 0x04
	CmdNext                uint32 = 0x05
	CmdRewind              uint32 = 0x06
	CmdFastForward         uint32 = 0x07
	CmdSkipForward         uint32 = 0x08
	CmdSkipBackward        uint32 = 0x09
	CmdSeek                uint32 = 0x0B
	CmdActivateAudioTrack  uint32 = 0x0C
	CmdActivateTextTrack   uint32 = 0x0D
	CmdDeactivateTextTrack uint32 = 0x0E
)

// RewindRequest is the request payload for the Rewind command.
type RewindRequest struct {
	AudioAdvanceUnmuted bool `tlv:"0,bool"`
}

// FastForwardRequest is the request payload for the FastForward command.
type FastForwardRequest struct {
	AudioAdvanceUnmuted bool `tlv:"0,bool"`
}

// SkipForwardRequest is the request payload for the SkipForward command.
type SkipForwardRequest struct {
	DeltaPositionMilliseconds uint64 `tlv:"0,uint"`
}

// SkipBackwardRequest is the request payload for the SkipBackward command.
type SkipBackwardRequest struct {
	DeltaPositionMilliseconds uint64 `tlv:"0,uint"`
}

// SeekRequest is the request payload for the Seek command.
type SeekRequest struct {
	Position uint64 `tlv:"0,uint"`
}

// ActivateAudioTrackRequest is the request payload for the ActivateAudioTrack command.
type ActivateAudioTrackRequest struct {
	TrackID          string `tlv:"0,utf8"`
	AudioOutputIndex uint8  `tlv:"1,uint"`
}

// ActivateTextTrackRequest is the request payload for the ActivateTextTrack command.
type ActivateTextTrackRequest struct {
	TrackID string `tlv:"0,utf8"`
}

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Features: []clusters.FeatureInfo{
			{Bit: 0, Code: "AS", Name: "AdvancedSeek"},
			{Bit: 1, Code: "VS", Name: "VariableSpeed"},
			{Bit: 2, Code: "TT", Name: "TextTracks"},
			{Bit: 3, Code: "AT", Name: "AudioTracks"},
			{Bit: 4, Code: "AA", Name: "AudioAdvance"},
		},
		Attributes: []clusters.AttributeInfo{
			{ID: AttrCurrentState, Name: "CurrentState", DisplayName: "CurrentState", Type: "enum8", Readable: true},
			{ID: AttrStartTime, Name: "StartTime", DisplayName: "StartTime", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrDuration, Name: "Duration", DisplayName: "Duration", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrSampledPosition, Name: "SampledPosition", DisplayName: "SampledPosition", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrPlaybackSpeed, Name: "PlaybackSpeed", DisplayName: "PlaybackSpeed", Type: "float32", Readable: true},
			{ID: AttrSeekRangeEnd, Name: "SeekRangeEnd", DisplayName: "SeekRangeEnd", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrSeekRangeStart, Name: "SeekRangeStart", DisplayName: "SeekRangeStart", Type: "uint64", Readable: true, Nullable: true},
			{ID: AttrActiveAudioTrack, Name: "ActiveAudioTrack", DisplayName: "ActiveAudioTrack", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrAvailableAudioTracks, Name: "AvailableAudioTracks", DisplayName: "AvailableAudioTracks", Type: "list", Readable: true, Nullable: true},
			{ID: AttrActiveTextTrack, Name: "ActiveTextTrack", DisplayName: "ActiveTextTrack", Type: "struct", Readable: true, Nullable: true},
			{ID: AttrAvailableTextTracks, Name: "AvailableTextTracks", DisplayName: "AvailableTextTracks", Type: "list", Readable: true, Nullable: true},
		},
		Commands: []clusters.CommandInfo{
			{ID: CmdPlay, Name: "Play", DisplayName: "Play", HasResponse: true},
			{ID: CmdPause, Name: "Pause", DisplayName: "Pause", HasResponse: true},
			{ID: CmdStop, Name: "Stop", DisplayName: "Stop", HasResponse: true},
			{ID: CmdStartOver, Name: "StartOver", DisplayName: "StartOver", HasResponse: true},
			{ID: CmdPrevious, Name: "Previous", DisplayName: "Previous", HasResponse: true},
			{ID: CmdNext, Name: "Next", DisplayName: "Next", HasResponse: true},
			{ID: CmdRewind, Name: "Rewind", DisplayName: "Rewind", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AudioAdvanceUnmuted", DisplayName: "AudioAdvanceUnmuted", Type: "bool"},
			}},
			{ID: CmdFastForward, Name: "FastForward", DisplayName: "FastForward", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "AudioAdvanceUnmuted", DisplayName: "AudioAdvanceUnmuted", Type: "bool"},
			}},
			{ID: CmdSkipForward, Name: "SkipForward", DisplayName: "SkipForward", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DeltaPositionMilliseconds", DisplayName: "DeltaPositionMilliseconds", Type: "uint64"},
			}},
			{ID: CmdSkipBackward, Name: "SkipBackward", DisplayName: "SkipBackward", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "DeltaPositionMilliseconds", DisplayName: "DeltaPositionMilliseconds", Type: "uint64"},
			}},
			{ID: CmdSeek, Name: "Seek", DisplayName: "Seek", HasRequest: true, HasResponse: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "Position", DisplayName: "Position", Type: "uint64"},
			}},
			{ID: CmdActivateAudioTrack, Name: "ActivateAudioTrack", DisplayName: "ActivateAudioTrack", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TrackID", DisplayName: "TrackID", Type: "string"},
				{ID: 1, Name: "AudioOutputIndex", DisplayName: "AudioOutputIndex", Type: "uint8", Nullable: true},
			}},
			{ID: CmdActivateTextTrack, Name: "ActivateTextTrack", DisplayName: "ActivateTextTrack", HasRequest: true, RequestFields: []clusters.CommandFieldInfo{
				{ID: 0, Name: "TrackID", DisplayName: "TrackID", Type: "string"},
			}},
			{ID: CmdDeactivateTextTrack, Name: "DeactivateTextTrack", DisplayName: "DeactivateTextTrack"},
		},
	})
}
