// Code generated by cmd/codegen; DO NOT EDIT.

// Package powersourceconfiguration implements the Matter Power Source Configuration cluster (0x002E).
package powersourceconfiguration

import "github.com/p0fi/matter-cli/internal/clusters"

const (
	// ID is the Matter cluster ID for Power Source Configuration.
	ID uint32 = 0x002E
	// Name is the CLI-friendly cluster name.
	Name = "PowerSourceConfiguration"
	// DisplayName is the human-friendly cluster name.
	DisplayName = "Power Source Configuration"
)

// Attribute IDs.
const (
	AttrSources uint32 = 0x0000
)

func init() {
	clusters.Global.Register(clusters.ClusterInfo{
		ID:          ID,
		Name:        Name,
		DisplayName: DisplayName,
		Attributes: []clusters.AttributeInfo{
			{ID: AttrSources, Name: "Sources", DisplayName: "Sources", Type: "list", Readable: true},
		},
	})
}
